### ISSUE TITLE
issue.update() is failing: Field 'description' cannot be set. It is not on the appropriate screen, or unknown.

### ISSUE THREAD

**Issue by cocobuster** [pycontribs/jira#1]
Hi,

  I am trying to update certain fields on an issue, but I am getting the following error:

python> issue.update(description='some text')
ERROR:root:[u"Field 'description' cannot be set. It is not on the appropriate screen, or unknown."]
*** JIRAError: HTTP 400: "Field 'description' cannot be set. It is not on the appropriate screen, or unknown."

But looking at the issue fields, description field is quite a valid field (jira default field...):
python>issue.fields.description
'old description'

thanks for your help,

**Comment by lorrin** [comment]
Hi, I just bumped into this as well. The user did not have access to edit issues, as @ssbarnea suggested. Seems like an unfortunate error message. :-(

**Comment by ebarojas** [comment]
For future reference, I stumbled upon this problem when migrating to ```api_token``` instead of password. **It seems you need to use an admin email address** instead of the user who created the token. More info in issue: https://github.com/pycontribs/jira/issues/808
