### ISSUE TITLE
Show whether comment is internal or public (or at least allow expansion on comments)

### ISSUE THREAD

**Issue by nico-cs50** [pycontribs/jira#1011]
**Is your feature request related to a problem? Please describe.**
I have been struggling for a while to find a way to distinguish between public and internal comments coming from a server instance. On a cloud instance I managed to find the jsdPublic attribute of Comment which returns False for internal comments (this is not well documented on Jira's website and not documented at all on this library's docs, AFAIK), but that attribute is absent for comments on my server instance.

**Describe the solution you'd like**
Since this information is available through the REST API when using /rest/api/latest/issue/<issu-key>comment**?expand=properties**, it would be great to use that to display the comment status.

**Describe alternatives you've considered**
If that's too much work, having the chance of expanding comments to return the properties fields would be already a great step forward, since from them it would be actually possible to extract the data on the comment's status.

**Additional context**
I have close to zero experience with APIs, but I am more than open to putting some time in to come up with some sort of implementation of this myself, if anybody has any pointers on it :)

**Comment by studioj** [comment]
would this help?
https://github.com/pycontribs/jira/pull/1003/files

**Comment by studioj** [comment]
@nico-cs50 => after the merge of https://github.com/pycontribs/jira/pull/1003 this is assumed fixed.

it should become available in the next public release

if this assumption would be wrong, please reopen the issue.
