### ISSUE TITLE
`rename_version` is not supported yet

### ISSUE THREAD

**Issue by ym1220** [pycontribs/jira#1016]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**

**To Reproduce**
```
call the api rename_version as described in API-document
JIRA.rename_version(<JiraProject>,<oldnmae>,<newname>)
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**

**Stack Trace**
```
'JIRA' object has no attribute 'rename_version'
```

**Version Information**
Python Interpreter: python3
jira-python: 2.0.0
OS: Windows
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by studioj** [comment]
you might want to have a look at the version resource

https://github.com/pycontribs/jira/blob/master/jira/resources.py#L873

how to find a version id is explained here
https://community.atlassian.com/t5/Jira-questions/How-do-I-get-the-fixversion-ID/qaq-p/395216#:~:text=Browse%20to%20a%20version%20in,where%2010100%20is%20the%20id.&text=so%20how%20or%20where%20do,fixversion%20IDs%20on%20Jira%206.1.

**Comment by studioj** [comment]
@ym1220 
closing this issue 
See following links in the documentation:
- https://jira.readthedocs.io/en/master/api.html#jira.client.JIRA.rename_version
- https://jira.readthedocs.io/en/master/api.html#jira.resources.Version.update

if these items dont solve your question, please reopen and clarify
