### ISSUE TITLE
assign_issue() raises User JIRAUSER<id> does not exist error

### ISSUE THREAD

**Issue by ankitrbansal** [pycontribs/jira#1049]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
jira.assign_issue(issue_key, assignee) raises 
```
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://<jira_host>/rest/api/latest/issue/<issue_key>/assignee
        text: User 'JIRAUSER<id>' does not exist.
```
Despite the same key being returned from https://<jira_host>/rest/api/2/user?username=<username> .
The user does exist and this error seems to have manifested only recently (past few weeks)

**To Reproduce**
```
jira.assign_issue("some_issue_key", "email_address")
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**
assign_issue should return a successful response, resulting in the issue being assigned to the user

**Stack Trace**
```
A code block with the any trace messages.
```

**Version Information**
Type of Jira instance:
- [ ] Jira Cloud (Hosted by Atlassian)
- [X] Jira Server or Data Center (Self-hosted)
Python Interpreter: 3.6.9
jira-python: 3.0.1
OS: Linux
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by ankitrbansal** [comment]
I think the bug seems to be in the assign_issue function [while creating the payload](https://github.com/pycontribs/jira/blob/master/jira/client.py#L1625). It seems the payload is created as 
`payload = {"name": self._get_user_key(assignee)}`
but instead should be 
`payload = {"key": self._get_user_key(assignee)}`

**Comment by adehad** [comment]
Yep you are right, the tests missed this as the `key` and `name` of our test user are identical.
![image](https://user-images.githubusercontent.com/26027314/119175037-40ff4f80-ba61-11eb-8623-47f8f228d640.png)

It seems like we were using `accountId` originally in 3.0 which appears to only be supported on Jira Cloud.
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-assignee-put

Compared to Server:
https://docs.atlassian.com/software/jira/docs/api/REST/8.13.6/#api/2/issue-assign

I introduced this bug so I'll make a PR to fix it any hopefully make sure our tests don't let something like this through.

**Comment by ankitrbansal** [comment]
Thanks! do you have a tentative estimate of when the new version will be released with the fix?

**Comment by adehad** [comment]
Not sure. If you aren't able to rollback, my advice would be to override the class method, by creating a new class like so:

```python
from jira import JIRA

class MyJira(JIRA):
    # refer: https://github.com/pycontribs/jira/issues/1049
    def _get_user_key(self, user: str) -> str:
        """Internal method for translating an user (str) to an name."""
        try:
            name = self.search_users(user, maxResults=1)[0].name
        except Exception as e:
            raise JIRAError(str(e))
        return name

# now use MyJira as you normally would the JIRA class.
```
