### ISSUE TITLE
Set check_update to False by default

### ISSUE THREAD

**Issue by metashock** [pycontribs/jira#105]
Currently the value is set to True by default which means it will issue an HTTPS request to pypi each time the client is initiated plus it polutes the output with the following misleading comment:

    You are running an outdated version of JIRA Python %s. Current version is %s. Do not file any bugs against older versions.

Misleading because the version is not outdated, it is the version I've tested my software against and the users MUST NOT upgrading it as long as they want support for my software. Issuing an HTTPS request on client instantiation does not makes sense IMHO - from the technical perspective as from the privacy perspective. I don't want that someone can track when I call a program which is using the library and I also don't want a program that performs an HTTPS request before it is starting to do it's millisecond work plus emiting a warning that it cannot reach the internet where it is meant to run as an intranet application.

To specify requirements with a specific version using requirements.txt and then running it in a virtualenv is one of the common ways to deploy python applications. IMHO the version check is contra productive because of this and I've never seen a library which is doing such a thing.

Please set it to `False` by default or remove it completely.

**Comment by asqui** [comment]
Seconded

**Comment by ssbarnea** [comment]
As long GitHub will not provide a way to to prevent people from raising bugs that were identified in an old version I am forced to use this this approach. So far 2 out of 3 issues were already solved or duplicate and I do not have the time to deal with all of these.

Please note that I am open to suggestions and contributions. Note that current behaviour does allow advanced users to disable this functionality.
