### ISSUE TITLE
Specify different UA

### ISSUE THREAD

**Issue by G4bbix** [pycontribs/jira#1066]
In our envoirement we have by default blocked any traffic having the UA "python-requests" since we've had a bunch of DDoS attacks coming with it.

We'd love to have the possibility to set an alternate UA. 

Cheers G4bbix

**Comment by studioj** [comment]
@G4bbix thx for your ticket.  I can tell you the people currently spending time and effort on the project are trying to get the typehinting in order and to provide better CI for jira cloud. next to that trying to get open Pr's merged.

The issue carries some value, so if you would be open to creating a fork and opening a PR, you're very welcome we'll gladly spend the time reviewing it.
Kr

**Comment by adehad** [comment]
Something like what was proposed in #958 might be a good fit for this case. As, if I understand the report correctly, the User Agent is just specified as a header.
