### ISSUE TITLE
No tag for latest release, RELEASE is stale

### ISSUE THREAD

**Issue by asqui** [pycontribs/jira#107]
Could the package maintainer please provide a tag or SHA1 that points to the latest stable release on pypi?!

Also, the latest commit on master appears to have bumped the version to 1.0.1 -- was that intentional?!

**Comment by metashock** [comment]
Also I'm missing all the tags above 0.43. Setting the version from 0.50 (a non existing tag) to 1.0.1 astonishes me. What are you guys doing here? I you want to loose existing users, you are on the best way.

**Comment by brianwallace** [comment]
+1

I am confused by this as well.  It would be great to have it sorted out.

**Comment by ssbarnea** [comment]
RELEASE tag is the one currently pushed to pypi, or at least it supposed to. I am trying to remind you that this is a community driven project and the release is supposed to happen directory from Travis when all the tests are passing.

This means that it should not depend on a single current maintainer (me ATM). 
So if you want contribute, I am more than willing to welcome new PyContribs members.

**Comment by metashock** [comment]
@ssbarnea Good to hear that. I've offered my help here already and I'm still willing to help maintaining the project. I can respond to bug reports, help with bugfixes or even add features. I'm using the project at work.

**Comment by asqui** [comment]
Is there contributors guide? How to get started. How to run the tests. How to contribute pull requests, (e.g. make sure that your patch is based off the latest version on master and has a corresponding test.) How the automated build and release process is supposed to work?

Having such a guide would make it a lot easier for willing helpers to contribute, and unfortunately it's hard for such willing helpers to reverse engineer such a guide.

For example you mention that the release should be fully automated. I had a look at the release script and it looks reasonable, however it makes some commits to version.py with a standard commit message and I can't see any commits with that message in the history on master making me question if this script is actually in use, or if it's successfully pushing its commits.

If there are known issues in the infrastructure those should be documented as issues (perhaps with a particular tag) so that people are aware of what needs fixing.

**Comment by joshfriend** [comment]
For anyone wondering, the commits associated with the missing git tags appear to be as follows:

`1.0.3` = 0ad3c352839060da9dc146df635a97119eccd114
`1.0.1` = 877e9b395dc05dc758336eb0b1fc5702a109131c
`0.50` = 3383ecdb80151f36a88048b7b38953a20020a5b5
`0.49` = c815fea7cf14a2ece1db7da1bf5c857890693ee8
`0.48.1` = aef78a1088a1d1b47efe4500dccc13e8cd49b3a9
`0.48` = 85f391bf7abadc270ca3e7eff610d653f6bde185
`0.47` = 18ad3ced8260584ee6eed44701d41205194e7f13

That's as much as I was able to determine from looking at the history for [`version.py`](https://github.com/pycontribs/jira/commits/master/jira/version.py)

You may also notice that some of those versions (`1.0.1`, `0.48.1`) were never pushed to PyPI either: https://pypi.python.org/simple/jira/

**Comment by asqui** [comment]
Thanks for working out the historic release refs @joshfriend!

**Comment by abdarraafi** [comment]
@ssbarnea, I'd like to help, at least with getting the tags pushed to GitHub and with the BitBucket repo synchronized with GitHub, or wherever `master` ought to be.

In the meantime, could you please push your tags? I'm happy to help publish packages to PyPI, though I am not at all certain how.

**Comment by joshfriend** [comment]
@abdarraafi basically you would just do whatever the release scripts do, but manually so that it actually works.

https://github.com/pycontribs/jira/blob/2ddb19f66dbec563cc9a0d9a9cfc925ba4f34289/.travis.yml#L66
https://github.com/pycontribs/jira/blob/2ddb19f66dbec563cc9a0d9a9cfc925ba4f34289/.travis.yml#L71

**Comment by abdarraafi** [comment]
@joshfriend whoa, are those the actual private keys used to push packages to PyPI? O_o

Would @ssbarnea be okay with me using them?

**Comment by joshfriend** [comment]
@abdarraafi no way, Travis lets you encrypt secrets and put them in `.travis.yml` though: http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by ak-ambi** [comment]
@ssbarnea could you add git tags to commits listed by joshfriend?

**Comment by ssbarnea** [comment]
i will be trying to fix the build and release process this weekend but is going slow because some tests are failing and their failure is partially random. Without passng test I cannot release.

**Comment by ssbarnea** [comment]
@joshfriend I added you to PyContribs.

**Comment by ssbarnea** [comment]
I manually added the missing tags and the next ones are supposed to be updated automatically. I will try to modify the code to make the tagging before publishing to pypi, just in order to be sure that we do not publish something that is not tagged.
