### ISSUE TITLE
update() got multiple values for keyword argument 'fields'

### ISSUE THREAD

**Issue by marcoconti83** [pycontribs/jira#11]
Issue
=============
I'm running the following snippet:
    
    from jira.client import JIRA

    jira = JIRA('https://jira.atlassian.com')
    issue = jira.issue('JRA-9')
    version = jira.project_versions(jira.project("JRA"))[0]

    print version.id
    issue.update(fixVersions=[{"id":version.id}])

Expected behaviour
-------------------------------------
`fixVersions` is set on the issue

Actual behaviour:
-------------------------------------

     10130
     Traceback (most recent call last):
     File "foo.py", line 10, in <module>
     issue.update(fixVersions=[{"id":version.id}])
     File "/Library/Python/2.7/site-packages/jira/resources.py", line 331, in update
     super(Issue, self).update(fields=None, async=async, jira=jira, **data)
     TypeError: update() got multiple values for keyword argument 'fields'

Configuration
===============
I'm running OSX 10.10.1

    $~ pip show jira
    ---
    Name: jira
    Version: 0.35
    Location: /Library/Python/2.7/site-packages
    Requires: tlslite, six, requests-oauthlib, requests
    $ ~ python --version
    Python 2.7.6

**Comment by dholtkamp** [comment]
Same thing happens with labels. 

issue.update({'labels': 'test'})
issue.update(labels=['label1', 'label2'])
lead to the same error.

I also tried to add a label during issue creation (using a dict), doesn´t work.

Using Python 2.6.9 on OSX, jira package 0.35

**Comment by ssbarnea** [comment]
I agree with you, I was able to identify the bug and tomorrow I will make a new release with the fix. 

I have to delay it a little bit because I do also have some other changes which are breaking the tests and I do not want to push code that I do know that does not pass the tests.

**Comment by DanEhrlich** [comment]
This error is still occurring with 0.36.

**Comment by ssbarnea** [comment]
Please check now, I made a new release which is supposed to include a fist for this too.

**Comment by marcoconti83** [comment]
It works great. Thanks!

**Comment by elucify** [comment]
It's nice that there's a fix for this, but build 0.36 failed in travis. So apparently 0.35 is the latest version available from pypi. Is there a repo that distributes 0.36?
