### ISSUE TITLE
Unable to upgrade the JIRA Python from 0.47 to 0.50

### ISSUE THREAD

**Issue by ShivaShinde** [pycontribs/jira#111]
@jsoriano I am using Python Jira 0.47 on MacOS Yosemite. I am running this command but nothing happens ***pip install --user --upgrade jira***

How can I upgrade from 0.47 to 0.50? Thanks.

**Comment by ssbarnea** [comment]
I am 100% sure that that's because of some issues regarding what python version you are using and where it does install. I do work on mac and had similar issues but there is nothing wrong with the library installation part, which consists in copying some files.
