### ISSUE TITLE
sendEmail kwarg doesn't work when calling add_user method

### ISSUE THREAD

**Issue by fender4645** [pycontribs/jira#112]
The code and docs for the `add_user` method have a kwarg called "sendEmail" which I presume is supposed to send email to the new user that was just created. Looking at the REST API, this is currently not a valid parameter and will be ignored. This should be removed from both the code and the docs.

I'll fix and create a pull request.

**Comment by ssbarnea** [comment]
The parameter was removed from trunk as someone reported it as being ignored by jira rest API.
