### ISSUE TITLE
add_watcher throws 404

### ISSUE THREAD

**Issue by tfrokt** [pycontribs/jira#1123]
**Describe the bug**
```
*** jira.exceptions.JIRAError: JiraError HTTP 404 url: https://XXX.atlassian.net/rest/api/2/issue/XXX-XXXX/watchers
	text: {"errorMessages":[],"errors":{}}
```

**To Reproduce**
```
JIRA(basic_auth=(jira_user, jira_password), options={'server': jira_server})
issue_dict = {
        'project': 'XXX',
        'summary': 'test',
        'description': 'test',
        'issuetype': {'name': 'Initiative'},
    }
issue = jira.create_issue(fields=issue_dict)
jira.add_watcher(issue, '<username>')
```

**Expected behavior**
No error - or at least a meaningful error message

**jira==3.0.1**
**Python 3.9.6**

`remove_watcher` throws the same error, I double checked my username is correct by querying watchers as described [here](https://jira.readthedocs.io/en/master/examples.html#watchers).

Happy to provide further info if required.

**Comment by adehad** [comment]
Can you confirm whether you are using a "Jira Cloud" or "Jira Server / Data Center" instance?

**Comment by tfrokt** [comment]
> Can you confirm whether you are using a "Jira Cloud" or "Jira Server / Data Center" instance?

"Jira Cloud", see the url in the error message above https://XXX.atlassian.net.

**Comment by adehad** [comment]
So I am suspecting you may need to use `accountId` instead of `name`, 
```python
jira.add_watcher(issue, user_resource.accountId)
```

**Comment by tfrokt** [comment]
> So I am suspecting you may need to use `accountId` instead of `name`,
> 
> ```python
> jira.add_watcher(issue, user_resource.accountId)
> ```

That works! Thanks a lot for the quick replies!

**Comment by adehad** [comment]
No problem! Might reopen this so we can track that we need to improve the documention a little. Thanks for raising!
