### ISSUE TITLE
Replacing password with PAT not working

### ISSUE THREAD

**Issue by pkalbhor** [pycontribs/jira#1129]
Hi, 
I was trying to authenticate using personal access token instead of a password using
```
jira = JIRA('http://its.cern.ch/jira', basic_auth=('username', 'Personal access token')
```
It gives authentication failure. 
```
Basic Authentication Failure - Reason : AUTHENTICATED_FAILED
```
However, using actual password works. Please tell me if I am doing it in the wrong way. The user guide says the same.

**Comment by studioj** [comment]
Thanks for your report would this be a possible solution? https://github.com/pycontribs/jira/pull/991

a workaround until that PR is merged and released can be found here https://github.com/pycontribs/jira/issues/989#issuecomment-772683446

Don't hesitate to comment or contribute 👍
