### ISSUE TITLE
Resource RequestType is broken in 3.x

### ISSUE THREAD

**Issue by bmathieu33** [pycontribs/jira#1130]
The class cannot be instanciated with raw content, since v3.

The commit [b07a074abf6773c](https://github.com/pycontribs/jira/commit/b07a074abf6773c6f6434fe1d6d2fe596c1695d1#diff-f6a531db4e0cfb356f1e8f6c560f4f2363242fb39be8aaf1da4145854f2f3731) has changed `RequestType.__init__` method, trying to parse raw content before having called `Resource.__init__()`. This leads to this kind of traceback, using release 3.0.1:

```
jira/resources.py", line 1015, in __init__
     self._parse_raw(raw)
jira/resources.py", line 403, in _parse_raw
     dict2resource(raw, self, self._options, self._session)
jira/resources.py", line 199, in __getattr__
     raise AttributeError(
 AttributeError: <class 'jira.resources.RequestType'> object has no attribute '_options' ('RequestType' object is not subscriptable)
```

Other resource classes have not been changed, so it seems this changed has been introduced by accident.

To reproduce:

```python
from jira.resources import RequestType
RequestType({}, None, {"some_attr": True})
```

Traceback:
```
Traceback (most recent call last):
  File "venv/lib/python3.9/site-packages/jira/resources.py", line 183, in __getattr__
    return self[item]
TypeError: 'RequestType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.9/site-packages/jira/resources.py", line 1015, in __init__
    self._parse_raw(raw)
  File "venv/lib/python3.9/site-packages/jira/resources.py", line 403, in _parse_raw
    dict2resource(raw, self, self._options, self._session)
  File "venv/lib/python3.9/site-packages/jira/resources.py", line 199, in __getattr__
    raise AttributeError(
AttributeError: <class 'jira.resources.RequestType'> object has no attribute '_options' ('RequestType' object is not subscriptable)
```

**Comment by studioj** [comment]
@bmathieu33 Thanks for your report. Could you edit your issue with a simple way to reproduce...

that would be awesome. Thx for investigating the commits and dont hesitate to create a fork and open a PR to possibly fix this (who knows with a test to validate its fix ;-))

**Comment by bmathieu33** [comment]
@studioj I have added a simple way to reproduce, and a small PR to fix this.

Sorry I cannot take the time investigate more how to add a test. I searched and found no tests case was already set up for this resource (only an empty file).
