### ISSUE TITLE
[Question] Will changes be published to PyPI?

### ISSUE THREAD

**Issue by julenpardo** [pycontribs/jira#1143]
Hey there,

I was wondering if changes integrated to master will get released and published to PyPI. Just asking because community had to fix some issues in the past (some of them breaking) and the [last release](https://pypi.org/project/jira/#history) is from May 12, and there have been quite some changes since then.

Thanks in advance,

**Comment by bodograumann** [comment]
I would also really like to see a new release; especially to assign tickets in jira cloud.

**Comment by julenpardo** [comment]
@adehad @studioj @ssbarnea do you guys know if there's any chance for this?

**Comment by studioj** [comment]
I think once @adehad has finalised his JiraCloud testing we would feel safe about releasing a new version.

see => https://github.com/pycontribs/jira/pull/1109

progress is happening in spare/hobby time so we cant provide a final date. 
If you want you could review the current progress and provide suggestions :-)

**Comment by julenpardo** [comment]
Awesome, thanks a lot for the heads up, I didn't know it was conditioned by this.

Unfortunately in my case I cannot use the latest master due to the sensitive nature of the places where the Jira library is used :( 

Many thanks again for the update!

**Comment by studioj** [comment]
due to the sensitive natures we really want to validate JIRA cloud the same way as we do jira server

**Comment by adehad** [comment]
As an update, I've got in touch (find us here: https://matrix.to/#/#pycontribs:matrix.org) and have the permissions for making a pre-release, will see if these PRs can get merged in in the new few days, otherwise I'll look into making the pre-release without those changes for now.

**Comment by bodograumann** [comment]
Thanks for the pre-release. It works perfectly for us!

**Comment by adehad** [comment]
`3.1.1` is now up !
