### ISSUE TITLE
ResilientSession::__recoverable throws AttributeError when dumping debug info 

### ISSUE THREAD

**Issue by sphack** [pycontribs/jira#1214]
### Bug summary

When a ConnectionError is thrown, __recoverable attempts to dump out headers from the response which does not exist on class ConnectionError.

Traceback (most recent call last):
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/client.py", line 1315, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 175, in post
    return self.__verb("POST", url, **kwargs)
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 155, in __verb
    if self.__recoverable(
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 120, in __recoverable
    logging.debug("response.headers: %s", response.headers)
AttributeError: 'ConnectionError' object has no attribute 'headers' 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

v7.13.1

### jira-python version

3.0.1

### Python Interpreter version

3.8.10

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
Keep calling create_issue until the server kills the connection before responding.   In my environment, I can reproduce it in 30 minutes running 20 scripts concurrently.   Normally, instances of this are reported every few days.
```

### Stack trace

```python
Traceback (most recent call last):
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/client.py", line 1315, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 175, in post
    return self.__verb("POST", url, **kwargs)
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 155, in __verb
    if self.__recoverable(
  File "/home/shack/projects/jiracnv/venv/lib/python3.8/site-packages/jira/resilientsession.py", line 120, in __recoverable
    logging.debug("response.headers: %s", response.headers)
AttributeError: 'ConnectionError' object has no attribute 'headers'
```

### Expected behaviour

I expect it to retry and not throw an error.

**Comment by sphack** [comment]
Implemented a fix and validated it works.  Wrap the two debug lines in hasattr check to verify that these attributes exist before dumping them to the logger.

        if hasattr(response, "headers"):
            logging.debug("response.headers: %s", response.headers)
        if hasattr(response, "content"):
            logging.debug("response.body: %s", response.content)

**Comment by sphack** [comment]
Looks like this is already address in the repo in the following comment, however, there is no bug ID describing this issue.

commit 6e513952c854acf67f78bce8c281c0546489a346
Author: adehad <26027314+adehad@users.noreply.github.com>
Date:   Sat May 15 13:45:29 2021 +0100

    add typehints and allow google docstrings (#1023)

    * chore: allow google docstring

    * bugfix: respect logging argument

    * bugfix: correct usage of JIRAError, add typehints

    * feature: add typehints and coax mypy

    * example, add _Comment helper

    * feature: add py.typed for PEP-561 compliance

    * bugfix: fix epic_id typehint, closes #968

**Comment by sphack** [comment]
Reopening issue since the fix is not in a release yet.   Please make a 3.0.2 release with the above change.

**Comment by adehad** [comment]
Hi @sphack you can find this in our release candidate: `pip install jira==3.1.0rc1` - expect a "proper" release soon - either "watch" this repo for releases or follow #1143 - where I will post an update. #1194 has some more details about the upcoming release.

Thanks
