### ISSUE TITLE
Ability to change Sprint state

### ISSUE THREAD

**Issue by doxt3r** [pycontribs/jira#123]
Hello!
Since Jira agile version 6.7.5, it is possible to change the state of a sprint via REST API.

The jira client (client.py) has already a function update_sprint with the possibility to do this, but the lines of code are commented:

```
def update_sprint(self, id, name=None, startDate=None, endDate=None):
    payload = {}
    if name:
        payload['name'] = name
    if startDate:
        payload['startDate'] = startDate
    if endDate:
        payload['startDate'] = endDate
    # if state:
    #    payload['state']=state
```

Could you please fix this ?
Thanks

**Comment by wizravi** [comment]
When I try to change sprint state as below:
jira.update_sprint(11, name="MySprint1", startDate="10/NOV/16 12:33 AM", endDate="24/NOV/16 12:33 AM", state="ACTIVE")

I get following error:
response text = {"message":"Unrecognized field \"state\" (Class com.atlassian.greenhopper.web.rapid.sprint.model.UpdateSprintRequest), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@155ed26; line: 1, column: 47] (through reference chain: com.atlassian.greenhopper.web.rapid.sprint.model.UpdateSprintRequest[\"state\"])","status-code":500,"stack-trace":"org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field \"state\" (Class com.atlassian.greenhopper.web.rapid.sprint.model.UpdateSprintRequest), not marked as ignorable\n at [Source: org.apache.catalina.connector.CoyoteInputStream@155ed26; line: 1, column: 47] 

Please help with this.

**Comment by tusharmakkar08** [comment]
@ssbarnea : Any update on how to overcome the issue which @wizravi mentioned?

**Comment by doxt3r** [comment]
Hi, what version of agile plugin are you using ?  manipulating state is enabled only since Jira agile version 6.7.

**Comment by tusharmakkar08** [comment]
Hey @doxt3r 

I am using JIRA Agile v7.1.23 .

**Comment by tusharmakkar08** [comment]
@doxt3r : Any idea on how to move forward?

**Comment by acromo** [comment]
I am also seeing the same issue with "state"
jira.exceptions.JIRAError: JiraError HTTP 500 url: http://bryde.ftc.rdlabs.hpecorp.net:8080/rest/greenhopper/1.0/sprint/11
	text: Unrecognized field "state" (Class com.atlassian.greenhopper.web.rapid.sprint.model.UpdateSprintRequest), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@8563b92; line: 1, column: 12] (through reference chain: com.atlassian.greenhopper.web.rapid.sprint.model.UpdateSprintRequest["state"])

I'm using Jira Software Server 7.9.0 and latest jira-python
I see 'state' getting passed via params but I believe the server is saying it doesn't recognize 'state' as a valid parameter.

**Comment by CamilleValley** [comment]
Same problem where with JIRA v7.2.12.
Any suggestion is very welcome :)

**Comment by ssbarnea** [comment]
I am reopening the ticket but keep in mind that this project does not have any company behind and that the only proved way to fix a bug was to raise a PR that is passing testing... or to bribe someone to do it for you.

Also I would recommend anyone to test **master** version before doing so as there are lots of changes in master which fixed existing bugs. Yep, install from git, should work.

**Comment by doxt3r** [comment]
Hi all,
Please ensure your are using sources from master branch and following the exact instructions from Jira Documentation:
```
 Update sprint

PUT /rest/agile/1.0/sprint/{sprintId}

Performs a full update of a sprint. A full update means that the result will be exactly the same as the request body. Any fields not present in the request JSON will be set to null.

Notes:

-     Sprints that are in a closed state cannot be updated.
-     A sprint can be started by updating the state to ‘active’. This requires the sprint to be in the ‘future’ state and have a startDate and endDate set.
-     A sprint can be completed by updating the state to ‘closed’. This action requires the sprint to be in the ‘active’ state. This sets the completeDate to the time of the request.
-     Other changes to state are not allowed.
-     The completeDate field cannot be updated manually.
```

Hope this helps

**Comment by blakperlz** [comment]
Was there an answer to this?  Yes I'm following the direction and I've tried multiple variations.
