### ISSUE TITLE
Support Personal Access Tokens

### ISSUE THREAD

**Issue by sajeelirkal** [pycontribs/jira#1237]
### Problem trying to solve

With the Jira LTS release 8.20 the Jira is supporting Personal Access Tokens, we need to support personal access tokens for Jira. The Basic auth will no more be supported for many Jira applications with this release.

More details: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

### Possible solution(s)

Details about personal access tokens: More details: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Comment by adehad** [comment]
We have support for PAT via the `token_auth` parameter:

Also see: #1216 

and

https://jira.readthedocs.io/api.html#jira.client.JIRA.__init__
