### ISSUE TITLE
Unable to add issues to epic after update 3.0.1 -> 3.1.1

### ISSUE THREAD

**Issue by valentijnscholten** [pycontribs/jira#1244]
### Bug summary

Exception when trying to add issues to an epic:
```
  File "/home/valentijn/dd/dojo/jira_link/helper.py", line 580, in add_jira_issue_for_finding
    return add_jira_issue(finding, *args, **kwargs)
  File "/home/valentijn/dd/dojo/jira_link/helper.py", line 695, in add_jira_issue
    add_issues_to_epic(jira, obj, epic_id=epic.jira_id, issue_keys=[str(new_issue.id)], ignore_epics=True)
  File "/home/valentijn/dd/dojo/jira_link/helper.py", line 565, in add_issues_to_epic
    return jira.add_issues_to_epic(epic_id=epic_id, issue_keys=issue_keys, ignore_epics=ignore_epics)
  File "/home/valentijn/venv/lib/python3.8/site-packages/jira/client.py", line 4768, in add_issues_to_epic
    raise NotImplementedError(
NotImplementedError: Jira Agile Public API does not support this request
```

Used to work in 3.0.1 and I think this a supported operation. Could it have to do something with the changes made in https://github.com/pycontribs/jira/pull/1186 ?

There's some code referring to the old value of `agile_rest_path` it seems?
```
if (
            self._options["agile_rest_path"]
            != GreenHopperResource.GREENHOPPER_REST_PATH
        ):
            # TODO(ssbarnea): simulate functionality using issue.update()?
            raise NotImplementedError(
                "Jira Agile Public API does not support this request"
            )
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian) and JIRA Server

### Jira instance version

8.20.1

### jira-python version

3.1.1

### Python Interpreter version

3.8

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
Call `add_issues_to_epic`
```

### Stack trace

```python
see above
```

### Expected behaviour

Issues being added to epic

**Comment by Dibakarroy1997** [comment]
Can confirm that add_issues_to_epic works in 3.0.1 but is not working in 3.1.1.
Manually this endpoint seems to working fine: https://developer.atlassian.com/cloud/jira/software/rest/api-group-epic/#api-agile-1-0-epic-epicidorkey-issue-get

**Comment by IanWhalen** [comment]
Hey all just wanted to add that we are seeing this as well.  Anyone figure out a workaround yet?

**Comment by gredin** [comment]
Please see my solution at https://github.com/pycontribs/jira/issues/964#issuecomment-1008920980

**Comment by IanWhalen** [comment]
FWIW we already subclass `jira.JIRA` in order to add some other helper methods and the like, so we've solved this by overriding the method as follows:

```python
class JiraService(JIRA):
    def __init__(self):
        super().__init__()

    def add_issues_to_epic(self, epic_key, issue_keys):
        data = {"issues": issue_keys}
        url = self._get_url(f"epic/{epic_key}/issue", base=self.AGILE_BASE_URL)
        response = self._session.post(url, data=json.dumps(data))
        return response
```

(note: lots of additional code related to auth and logging removed for clarity's sake in this example.)

**Comment by adehad** [comment]
So I believe this should be fixed in the latest release, do let me know if this is not the case

**Comment by adehad** [comment]
@gekitsuu can you check if #1450 works for you with

`pip install git+https://github.com/pycontribs/jira.git@bugfix/request_method_for_add_issues_to_epic`

**Comment by gekitsuu** [comment]
I installed the new version
```
➜ python -c 'import jira; print(jira.__version__)'
3.3.3.dev2+gea02922
```
And still get the same error

**Comment by adehad** [comment]
@gekitsuu Thanks, spotted another error, I've pushed an update, would be great if you can check again
Thanks for the swift response

**Comment by gekitsuu** [comment]
That worked in that I now get an error about next-gen issue (which I expected) Thanks!

**Comment by adehad** [comment]
Nice, I've added in a bit of a (hacky) test and was able to further confirm that both the original URL and request method were wrong, so hopefully we can properly close this issue with that PR.

Can I also further confirm if you are using Jira Cloud @gekitsuu  ?

Thanks again for the quick testing

**Comment by gekitsuu** [comment]
That’s correct

**Comment by adehad** [comment]
Perfect, will try and get this into a patch soon.

**Comment by Ma1tobiose** [comment]
This api still has problems when using the jira cloud platform. The test is as follows.
![image](https://user-images.githubusercontent.com/9525648/215239010-65a94ef4-07f7-47d3-b224-53a6a2f78e9f.png)
An error occurs
```
{"errorMessages":["The request contains a next-gen issue. This operation cant add next-gen issues to epics. To add a next-gen issue to an epic, use the Edit issue operation and set the parent property (i.e., `\"parent\":{\"key\":\"PROJ-123\"}` where `PROJ-123` has an issue type at level one of the issue type hierarchy). See <a href=\"https://developer.atlassian.com/cloud/jira/platform/rest/v2/\"> developer.atlassian.com </a> for more details."],"errors":{}}%
```
