### ISSUE TITLE
please upload an sdist distribution to pypi [$20]

### ISSUE THREAD

**Issue by wiggin15** [pycontribs/jira#127]
The PyPI page for jira contains only a wheel file:
https://pypi.python.org/pypi/jira/
But easy_install and buildout don't know how to install this distribution type. Some packages still use these systems (easy_install may be considered legacy, but it is still widely popular, and buildout is still in use).
It's also good to have a source distribution to be able to look at the source more easily.
This is a recurring issue - please fix the release script (if there is one) to always upload an sdist distribution.
##

**Comment by akadaedalus** [comment]
This is also an issue for source-based Linux distributions like Gentoo and its variants.  I had a ebuild script for v.0.50 that retrieves the tarball from pypi mirrors and builds from the source.  I prefer Gentoo's package management system to the various language-specific packagers like CPAN, gem, and pypi. 

I'd change the script to pull from github but releases are not tagged either, so it's a guessing game which commit to pull.

**Comment by nbaggott** [comment]
Yes, please fix the release script. And post the 1.0.3 src to pypi (or cut a 1.0.4). I'm in urgent need of some of the fixes in 1.0.3 but can't make use of the wheel for infrastructure reasons. 

Ping me if I can help.

**Comment by JohnPeacockMessageSystems** [comment]
I hate to leave a "me too" message here, but we have an alternate path distribution of python, etc, so I must have source, not some predigested binary package.  If you could at least be bothered to actually create tags, we could pull from github instead.

**Comment by ssbarnea** [comment]
Can you please elaborate the "can't make use of the wheel for infrastructure reasons" part? I am quire curious what prevents your from doing it?

**Comment by wiggin15** [comment]
I don't know about @JohnPeacockMessageSystems, but on our environment we can't use wheels because we're using the "buildout" build system, which doesn't support installing wheels yet.

Also, since there are no tags and no source distributions, it's hard to find the code for a specific version and compare it to another version.

**Comment by zaufi** [comment]
as a gentoo user I completely agreed with @akadaedalus! -- usage of this package has turned into a pain in the ass :( -- no source tarball, no sane tags on github :(

**Comment by akadaedalus** [comment]
I modified my ebuild to use git instead for v.1.0.3 based on the commit history of `jira/version.py`.  The relevant lines:
```
inherit distutils-r1 git-r3
EGIT_REPO_URI="https://github.com/pycontribs/jira.git"
EGIT_COMMIT="0ad3c352839060da9dc146df635a97119eccd114"
```
For 1.0.4 which doesn't seem to have been published to pypi:
```
EGIT_COMMIT="a84e736f783cf1a6c9259ce682e666571acf6f02"
```
Note that even though it took me maybe 5 minutes to figure out what to do, if those commits are tagged, it'd take me 10 seconds to create a new package with no guesswork and code examination.

A side comment that I do appreciate the product.  I've got a nice workflow with bugwarrior and taskwarrior thanks to this module.

**Comment by livenson** [comment]
Hi, hitting the same issue with 1.0.4. Any timeline on fixing it?

**Comment by ssbarnea** [comment]
Let me give some feedback on this. Back in February I changed jobs and my new position does not require much use of JIRA Python library.  

I don't mind making new releases (with proper sdist and wheels in them) but what prevented me from doing a new one is the fact that there are integration tests that are failing on Travis.

Until we fix those I cannot make a new release, that's because passing them is mandatory for a new release. 

Anyone can run these tests from their machines and make PRs for fixing them. Probably you observed that I do usually merge PRs really quick.

The day we will get the tests passing I will make a new release, a proper one.

**Comment by livenson** [comment]
Fair enough. PR submitted.

**Comment by akadaedalus** [comment]
Not sure if it was done manually but this appears to have been fixed with the 1.0.7 version -- I see the source available for download along with the wheel file.

**Comment by zaufi** [comment]
@ssbarnea,

> Until we fix those I cannot make a new release, that's because passing them is mandatory for a new release. 

as far as I see release [1.0.7](https://pypi.python.org/pypi/jira/1.0.7) has announced, I guess all tests are passed? then why there is still no tag `1.0.7` on github???

**Comment by ssbarnea** [comment]
fixed
