### ISSUE TITLE
code block not displaying as code block in the doc

### ISSUE THREAD

**Issue by dmshd** [pycontribs/jira#1277]
### Bug summary

Hello
In this page : https://jira.readthedocs.io/examples.html#initialization
under https://jira.readthedocs.io/examples.html#jira-cloud
there is a ".. code-block" (rst syntax not interpreted).
Kind regards,
Daniel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### jira-python version

main

### Python Interpreter version

3.8

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
# 1.
Go to https://jira.readthedocs.io/examples.html#jira-cloud
# 2. When I call the function with argument x
See that there is RST syntax not interpreted (" .. code-block")
```

### Stack trace

```python
---
```

### Expected behaviour

---

**Comment by adehad** [comment]
Thanks! Should now be updated
