### ISSUE TITLE
Remove setuptools runtime dependency

### ISSUE THREAD

**Issue by EpicWink** [pycontribs/jira#1289]
### Problem trying to solve

I'm trying to remove `setuptools` from my application dependencies (so I can use [`pip-tools`](https://pypi.org/project/pip-tools/1.8.0/) with [`pip install --no-deps`](https://pip.pypa.io/en/stable/cli/pip_install/#install-no-deps), as per [pip's recommendation](https://pip.pypa.io/en/stable/topics/repeatable-installs/))

### Possible solution(s)

Remove [`setuptools` requirement](https://github.com/pycontribs/jira/blob/main/setup.cfg#L62) from `install_requires`

### Alternatives

For my use, use `pip-tools --allow-unsafe` or `pip install` without `--no-deps`, but this doesn't solve the underlying issue

### Additional Context

Setuptools is only used in the `jira` package during build-time (as the pyproject.toml (aka PEP517) build backend), and not during runtime (a [repository search](https://github.com/pycontribs/jira/search?q=setuptools) confirms this)

**Comment by adehad** [comment]
@debanne thanks, we have #1248 which tracks the removal of `pkg_resources` and we have also dropped Py36 support so can use `importlib.metadata` without the backport.
