### ISSUE TITLE
Add Methods for Additional Project Configuration Schemes

### ISSUE THREAD

**Issue by Zyzyx** [pycontribs/jira#1294]
### Problem trying to solve

I need to automate reviews of schemes associated with a couple thousand projects in my Jira instance. It would enable us to review policies in place and provoke conversations with project owners that are not compliant.

### Possible solution(s)

 I noticed project_permissionscheme() exists and does exactly what I need. I'm thinking of adding similar calls for:

- issue security schemes
- issue type schemes
- priority schemes
- screen schemes
- workflow schemes
- field configuration schemes
- notification schemes

Like permission schemes, they would all be passed in a project ID or name.

### Additional Context

I'll sign up for authoring the PR if you guys are interested in this work. I know what I'm doing in Python but as of this writing, but I'm not an expert on the internals of python-jira. If there are any pitfalls I should know about, please let me know!

In the future I may return with a request to change to add calls to update/change schemes by project too. But for now, please consider that out of scope.

**Comment by ssbarnea** [comment]
You are welcomed to join this challenge. My only recommendation is to try to implement these in one by one instead of a big PR.
