### ISSUE TITLE
Add api-method to delete remotelinks

### ISSUE THREAD

**Issue by rynkk** [pycontribs/jira#1300]
### Problem trying to solve

It seems as if there was no method in the JIRA class to remove remotelinks (by globalId or internalId) from issues.
Is this in purpose/has there not been any demand for this, yet?

### Possible solution(s)

Implement the DELETE remotelink routes (As described here:
https://docs.atlassian.com/software/jira/docs/api/REST/8.13.14/#issue-deleteRemoteIssueLinkByGlobalId
https://docs.atlassian.com/software/jira/docs/api/REST/8.13.14/#issue-deleteRemoteIssueLinkById
https://developer.atlassian.com/server/jira/platform/jira-rest-api-for-remote-issue-links/#deleting-a-remote-link-by-global-id )

```py
import urllib.parse
@translate_resource_args
def delete_remotelink(self, issue: Union[str, Issue], *, internalid: Optional[str] = None, globalid: Optional[str] = None) -> Response:
    """Delete remotelink from issue by internalId or globalId.

    Args:
        issue (str): Key (or Issue) of Issue
        internalid (str): InternalID of the remotelink to delete
        globalid (str): GlobalID of the remotelink to delete

    Returns:
        Response
    """
    if not ((internalid is None) ^ (globalid is None)):
        raise ValueError("Must supply either 'internalid' XOR 'globalid'.")
    if internalid is not None:
        url = self._get_url("issue/" + str(issue) + "/remotelink/" + str(internalid))
    elif globalid is not None:
        # stop "&" and other special characters in globalid from messing around with the query
        globalid = urllib.parse.quote(globalid, safe="")
        url = self._get_url("issue/" + str(issue) + "/remotelink?globalId=" + globalid)
    return self._session.delete(url)
        
```

### Alternatives

Splitting the above method into 2 (One for globalId one for internalId)

### Additional Context

Pull request wanted?

---
<sub>Jannik Meinecke (<jannik.meinecke@mercedes-benz.com>) on behalf of MBition GmbH.
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by adehad** [comment]
@rynkk I believe there is an implementation for the internal id at least at the resource level:

e.g. the `RemoteLink` class itself has a `.delete()` method inherited from the `Resource` class:
https://github.com/pycontribs/jira/blob/ebc74c1d74367aaa91c43499619c656a3ebffea1/jira/resources.py#L416
(also see the test case I've linked at the bottom of this message)

Now at the global ID level, I do not believe this exists.

It would be great if you are able to submit a pull request for your proposal, it looks good to me as a single method, some suggestions from me:

```diff
--internalid
++internal_id
```
```diff
--globalid
++global_id
```

Would also be great if you can use the "f-string" format, we have this running on our linter `tox -e lint` so it should just be applied for you, e.g.
`self._get_url(f"issue/{issue}/remotelink?globalId={globalid}")`

and it would be great if you can write a test case for this, perhaps very similar to this:
https://github.com/pycontribs/jira/blob/ebc74c1d74367aaa91c43499619c656a3ebffea1/tests/resources/test_remote_link.py#L134

Thanks!

**Comment by rynkk** [comment]
I will have to wait until I've had the FOSS-workshop of my employee. Don't want to be in a pickle in the end. I will start working on this in approx. 1,5 months. If anyone else is craving this, feel free.
