### ISSUE TITLE
Contributing section lacks some information

### ISSUE THREAD

**Issue by Achimh3011** [pycontribs/jira#133]
Hi, as a new user of the project I'd value a few words about how this project is tested and how I can test changes I do. I'd think the "Contributing" section would be a matching place.

**Comment by asqui** [comment]
+1

How to get started. How to run the tests. How to contribute pull requests, (e.g. make sure that your patch is based off the latest version on master and has a corresponding test.) How the automated build and release process is supposed to work?

Having such a guide would make it a lot easier for willing helpers to contribute, and unfortunately it's hard for such willing helpers to reverse engineer such a guide from limited snippets of information...

**Comment by ssbarnea** [comment]
I added both of you to PyContribs so you can also push, merge and improve the documentation. 

I will try to do something in this direction myself but I cannot make any promises, especially that now I do not use the Jira library as much as before.

As a hint: try to follow the **git flow** process, that's documented and we can go towards it.
