### ISSUE TITLE
Random code confusing people

### ISSUE THREAD

**Issue by bharel** [pycontribs/jira#1332]
Heya! I'm a contributor on [stackoverflow](https://stackoverflow.com/questions/71461413/what-does-bases-in-init-self-mean), and you seem to have [random code that does nothing](https://github.com/pycontribs/jira/blob/09babc70ab20b0c28a1626987aa176c34250a57e/jira/resources.py#L1474) which was added as part of #306.

Do whatever you wish with that information ^^

**Comment by alannaemmrie** [comment]
Hey! Do you just want this deleted from the file? I can take care of that.

**Comment by adehad** [comment]
@alannaemmrie by all means feel free!

**Comment by adehad** [comment]
(We recently re-implemented pickling support in #1051  and have some tests in place, so in theory we should know if we broke pickling)
