### ISSUE TITLE
Error using token_auth

### ISSUE THREAD

**Issue by krwester** [pycontribs/jira#1335]
When I try to authenticated using a PAT on JIRA Server I get the following error:

tried `jira = JIRA(options=options, token_auth = jira_token)`

gives:

`TypeError: __init__() got an unexpected keyword argument 'token_auth'`

If I use basic_auth, it works.   I've also tried token_auth method with a different API wrapper, and it works fine.

**Comment by adehad** [comment]
Please follow the correct bug report template. There isn't enough information in this report, a key piece of information for example is what version of the package you are using

**Comment by krwester** [comment]
Description:  PAT Token method leads to `TypeError: __init__() got an unexpected keyword argument 'token_auth'`

Python Interpreter: Python 3.8
jira-python: V 3.11
OS: Windows 10

Other Dependencies:  JIRA Server 8.22.0#822000-sha1:cef2cc4

Steps To Reproduce:
    1. Setup personal token via JIRA interface
    2. Save token to variable "jira_token"
    3. Try to authenticate using `jira = JIRA(options=options, token_auth = jira_token)`
    4. Get error:  `TypeError: __init__() got an unexpected keyword argument 'token_auth'`

Confirm token authentication works on server by using the Atlassian Api wrapper.

Basic authentication also works using username/password -- but that is not ideal.

**Comment by adehad** [comment]
Can you check what the output of `print(jira.__version__)` is?
`3.1.1` should include the token auth option that is run in our test suite:
https://github.com/pycontribs/jira/blob/2c9f744e45bf4ebfd1e64f181a981c84e371e652/tests/test_client.py#L211

Is there the possibility of a conflicting namespace?
