### ISSUE TITLE
PAT Token method leads to TypeError: __init__() got an unexpected keyword argument 'token_auth' 

### ISSUE THREAD

**Issue by krwester** [pycontribs/jira#1337]
### Bug summary

Description: PAT Token method leads to T`ypeError: __init__() got an unexpected keyword argument 'token_auth'`

Python Interpreter: Python 3.8
jira-python: V 3.11
OS: Windows 10

Other Dependencies: JIRA Server 8.22.0#822000-sha1:cef2cc4

Steps To Reproduce:
1. Setup personal token via JIRA interface
2. Save token to variable "jira_token"
3. Try to authenticate using jira = JIRA(options=options, token_auth = jira_token)
4. Get error: TypeError: __init__() got an unexpected keyword argument 'token_auth'

Confirm token authentication works on server by using the Atlassian Api wrapper.

Basic authentication also works using username/password -- but that is not ideal.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

8.22.0

### jira-python version

main

### Python Interpreter version

3.8

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Reproduction steps

```python
Setup personal token via JIRA interface
2. Save token to variable "jira_token"
3. Try to authenticate using jira = JIRA(options=options, token_auth = jira_token)
4. Get error: TypeError: __init__() got an unexpected keyword argument 'token_auth'
```

### Stack trace

```python
I'm not sure how to provide that.
```

### Expected behaviour

Authenticated jira object

### Additional Context

Confirm token authentication works on server by using the Atlassian Api wrapper.

**Comment by wrmacrae** [comment]
This is happening for me, too, with v8.20.6 of Jira Server and 2.0 of the jira python module. Python 3.9.9 on a Mac.
```
>>> import inspect
>>> from jira import JIRA
>>> inspect.signature(JIRA.__init__)
<Signature (self, server=None, options=None, basic_auth=None, oauth=None, jwt=None, kerberos=False, kerberos_options=None, validate=False, get_server_info=True, async_=False, async_workers=5, logging=True, max_retries=3, proxies=None, timeout=None, auth=None)>
```

**Comment by krwester** [comment]
I was running 3.1.1 and still had the issue.   However, I upgraded to 3.2 and it works as expected.   Resolved as far as I'm concerned.
