### ISSUE TITLE
How to get attachment from comment?

### ISSUE THREAD

**Issue by Irishery** [pycontribs/jira#1382]
I want to download image from comment via api, but only that I can get is a string name of image in body like  `body: "!image-2022-05-19-19-58-23-624.png!"`. Is there any possible ways to do it?

**Comment by billga** [comment]
Yes. Since you can already get at the comments you're halfway there. With the string you found in the comment, search through the attachments on that issue to get the item you want: 
```python
# jc is your jira client, ABC-123 is your issue key
issue = jc.issue('ABC-123', fields='attachment')
for item in issue.fields.attachment:
    print(f"{item.filename}")
```
