### ISSUE TITLE
setuptools_scm_git_archive is obsolete

### ISSUE THREAD

**Issue by SnarkBoojum** [pycontribs/jira#1416]
### Bug summary

Since version 7, setuptools_scm has native support for git archives, so that [project](https://github.com/Changaco/setuptools_scm_git_archive) is now obsolete and its homepage is a migration guide.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### jira-python version

-

### Python Interpreter version

-

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
-
```

### Stack trace

```python
-
```

### Expected behaviour

-

**Comment by adehad** [comment]
Thanks happy to accept a PR for this, e.g. #1384

**Comment by adehad** [comment]
Refer to #1443
