### ISSUE TITLE
Plan to provide gadget or dashboard item resource?

### ISSUE THREAD

**Issue by chiaminchuang** [pycontribs/jira#1432]
Just a simple question. Do you plan to implement [gadget](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-dashboards/#api-rest-api-3-dashboard-dashboardid-gadget-post) or [dashboard item](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-dashboards/#api-rest-api-3-dashboard-dashboardid-items-itemid-properties-propertykey-get) resource? If you don't, why?
I didn't find any discussion or documentation about these two resources (I may miss them).
Thanks!

**Comment by adehad** [comment]
Happy to review any PRs!

We are a community run project so any gaps are filled by people like you and I.
Currently we have a preference for features that we can test (using our Jira Cloud instance and self-hosted Jira instance). 
If you plan to subclass the Jira class and need any help feel free to ask and the community may be able to help further.

Thanks
