### ISSUE TITLE
[Feature] auth use Bearer Authorization

### ISSUE THREAD

**Issue by JayChanggithub** [pycontribs/jira#1495]
### Bug summary

Have anything way to authenticator via Bearer token. I found via `curl` api like "https://jira.${FQDN}/rest/api/2/search" response code is 200. However i use python Jira module always got 401. How to do adopt Bearer token for these modules?

```
import json
import requests
url='https://jira.${FQDN}/rest/api/2/search'
headers = {}
headers["Accept"] = "application/json"
headers["Authorization"] = "Bearer $token"
resp = requests.get(url, headers=headers, data=json.dumps(query))
```
above code workable. Just want to know how could leverage these  Jira library use "Bearer token"?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### Jira instance version

9

### jira-python version

main

### Python Interpreter version

3.9

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Reproduction steps

```python
Workable


import json
import requests
url='https://jira.${FQDN}/rest/api/2/search'
headers = {}
headers["Accept"] = "application/json"
headers["Authorization"] = "Bearer $token"
resp = requests.get(url, headers=headers, data=json.dumps(query))
```

Failure

```
jira = JIRA(options=jiraOptions, basic_auth=("$token"))
```
```


### Stack trace

```python
401 failure
```

### Expected behaviour

workable auth with Bearer token

### Additional Context

altgraph==0.17.2
async-timeout==4.0.2
Deprecated==1.2.13
macholib==1.16
modulegraph==0.19.2
packaging==21.3
py2app==0.28.2
pyparsing==3.0.9
redis==4.3.4
TBB==0.2
wrapt==1.14.1

**Comment by JayChanggithub** [comment]
Sorry. I had found regarding these brief docs[ here](https://jira.readthedocs.io/examples.html#jira-cloud). Please kindly ignore above issue. Thanks.

**Comment by adehad** [comment]
Glad you found the docs useful, if you feel anything is missing, feel free to suggest any doc improvements (or even PR) and happy to include them !
