### ISSUE TITLE
Resource class's `find` method broken

### ISSUE THREAD

**Issue by milo-minderbinder** [pycontribs/jira#150]
Changes to the Resource class in 81322dd491bc268c8d56c3e9abd28c3f82c57244 broke the `Resource.find()` method, due to an extraneous `self` parameter passed to the class's `_get_url()` method on line 157 of jira/resources.py:
```python
url = self._get_url(self, path)
```

**Comment by ak-ambi** [comment]
Also fixed in #147 and #148
