### ISSUE TITLE
Right way to get all projects

### ISSUE THREAD

**Issue by filmackay** [pycontribs/jira#151]
Hi, just wondering what the best way to get all project information is with this API. If I call `.projects()` I get back a summary Project objects, with some information. To get the full information I need to make individual calls to `project.self` URL.

I can't see a way to do this in this API other than to do a `Project.find()` on each item returned by `.projects()`. Perhaps there is a better way?

**Comment by ssbarnea** [comment]
That's normal, this is mostly a REST API which means that you will have to make additional calls to get more information.
