### ISSUE TITLE
Update Issue Fails with connection timeout

### ISSUE THREAD

**Issue by kaarthikeyapreyan** [pycontribs/jira#155]
Python v2.7.10
Python-Jira v1.0.3
Requests v2.8.1

When trying to update an issue it fails with connection timeout
```
new_issue.update(fields={'reporter': {"name": reporter}})  # [Errno 110] Connection timed out
```
This happens for all the fields when using the update method.
But a CURL update works. The problem is only with the update, create and transitions are working good.
(could it be because of http redirects in my jira domain that update is not handling...?)

**Comment by ssbarnea** [comment]
I am closing this ticket as it seems like a support ticket and it also seems to lack information. 

We may reopen this ticket if there is a PR referring to it or if someone assigns it to himself and starts working on it. Creating bounty may be a way to speed things up.
