### ISSUE TITLE
Incorrect initialisation of resources.Issue causes fields, id and key fields to be reset

### ISSUE THREAD

**Issue by eleusis** [pycontribs/jira#158]
In f1866f48ea349d5c92cbdd11893b4b742d1f9a3c a change was made to add 'type hints' to the `Issue` class in the `jira.resources` module. However, due to the ordering of this new code, an `Issue` instance initialised from a `raw` dict would see its `fields`, `id` and `key` properties reset to `None`:

```
def __init__(self, options, session, raw=None):
        Resource.__init__(self, 'issue/{0}', options, session)
        if raw:
            self._parse_raw(raw)

        self.fields = None
        """ :type : Issue._IssueFields """
        self.id = None
        """ :type : int """
        self.key = None
        """ :type : str """
```

This means that, for example, an `Issue` instantiated from search results (`jira.search_issues()`)does not have its `fields` data accessible, whereas one instantiated using `jira.issue()` is fully functional. This side effect is readily noticeable from a broken test - `IssueTests.test_issue_equal()`. I note that this test was marked as failing in dedb4447eea6fe89c2c8fc2d5edf3a478ae8d599, 9 days after the introduction of the issue above.

Moving the `if raw` block after the type hint initialisers fixes the problem, and the test passes.
##

**Comment by hdost** [comment]
@ssbarnea Looks like we can close this out as the fix has been implemented

**Comment by hdost** [comment]
@eleusis This looks to be fixed based on commit history.
