### ISSUE TITLE
Add Labels to Issue: Field 'labels' cannot be set. It is not on the appropriate screen, or unknown.

### ISSUE THREAD

**Issue by dholtkamp** [pycontribs/jira#16]
When trying to add labels to an issue - either during creation or afterwards.

```
from jira.client import JIRA
jira = JIRA('https://jira.atlassian.com')
issue = jira.issue('JRA-107')

issue.update(labels=['bla', 'blubb'])
```

OR

```
issue.fields.labels.append(u'bla')
issue.update(fields={'labels': issue.fields.labels})
```

Both examples were taken from the documentation.

```
JIRAError: JiraError HTTP 400
	text: Field 'labels' cannot be set. It is not on the appropriate screen, or unknown.
```

But (after manually adding labels on the Web):

```
print issue.fields.labels
[u'bla', u'blubb']
```
So the field is there.

jira-0.37 with Python 2.6.9 on OSX

**Comment by ssbarnea** [comment]
Sorry but this seems like a configuration bug on your instance. As long you do not have the lables field editable using the edit screen o this issue, you will get this error.

This error comes from JIRA directly and is pretty descriptive.

BTW, you will never be able to label issues on JAC site if you are not the owner of these issues! 

If you get this error, all depends on your server configuration, not the client library.

**Comment by dholtkamp** [comment]
Oh damn, i was using the wrong user, sorry about that. Thanks for pointing me in the right direction.
