### ISSUE TITLE
problem when having unicode attribute name in resources

### ISSUE THREAD

**Issue by molog** [pycontribs/jira#160]
dict2resource raises error when the resource dict contains any unicode key (non-ascii) as python 2 does not allow non-ascii attribute.

This problem has been there since the start of this project. Any solution for this in the future?
##

**Comment by asqui** [comment]
If you can submit a pull-request that fixes this, it will likely be merged in quite quickly...

**Comment by hdost** [comment]
@molog A PR is always welcome, and even better, if we could have a test to cover your case that would be even better.
