### ISSUE TITLE
function not working

### ISSUE THREAD

**Issue by Calm3890** [pycontribs/jira#1609]
### Bug summary

JIRA function of issue_types_for_project not found when being called
<img width="483" alt="Screenshot 2023-02-20 at 09 43 46" src="https://user-images.githubusercontent.com/36410028/219997533-3129ba3e-0de8-40e2-998e-eef13fa28ada.png">

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### jira-python version

"main", "3.4.1"

### Python Interpreter version

3.9

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
jira: JIRA
# 2. When I call the function with argument x
jira.the_function(x)
# 3.
...
```

### Stack trace

```python
AttributeError: 'JIRA' object has no attribute 'issue_types_for_project'
```

### Expected behaviour

The issue function properly

**Comment by studioj** [comment]
hey @Calm3890 
care to try with version 3.5.0?
this method was only added in 3.5.0
https://github.com/pycontribs/jira/compare/3.4.1...3.5.0?diff=unified#diff-442d14b20d591afd0c3de830d2803e30d4816eedc708f9ad129316aa7e5a4a7cR3170
