### ISSUE TITLE
No attachments in self hosted JIRA 6.4.4

### ISSUE THREAD

**Issue by zamber** [pycontribs/jira#163]
Hi,

I've tried with latest master https://github.com/pycontribs/jira/commit/126fa15325cb94ca4243c9551fd0ba4841b88915 and I don't see `attachment` in `fields` for an issue. I search issues by  `'project = PROJ AND attachments IS NOT EMPTY ORDER BY created DESC'` and it successfully finds issues with attachments. `issue.raw` also does not have `attachment` anywhere.

Are there any other steps I should take to debug this?

**Comment by eleusis** [comment]
`search_issues()` does not grab all the data attached to an issue - you can use the optional `expand` keyword parameter to specify additional fields to be fetched. For attachments, however, you might like to consider the `client.JIRA.attachment()` and `client.JIRA.attachment_meta()` methods.

**Comment by zamber** [comment]
Thanks, solved it with `search_issues(query, fields='summary,description,attachment')` :).

**Comment by eleusis** [comment]
Oops, sorry, `fields` is the right parameter, not `expand`. :)
