### ISSUE TITLE
Worklog field maxResults

### ISSUE THREAD

**Issue by gordeychuk** [pycontribs/jira#164]
Hi everyone,

I didn't find a way to ask a help, so I created an issue.
Module works well, but when I receive info about issue worklog field, I have maxResults = 20.

I know that I can set maxResult when I searching an issues, but what about issue info?
How can I get more than 20 worklogs?

I read the documentation and I saw expand parameter for issue method, but I don't know how to use it for getting more worklogs.

Thanks in advance.

**Comment by gordeychuk** [comment]
Issue solved by using separate worklogs method

**Comment by ankitg1989** [comment]
@gordeychuk can you mention the method you used?

**Comment by gordeychuk** [comment]
> @gordeychuk can you mention the method you used?

Here's the part from my app:
`
from jira import JIRA

def _jira_authorize(self):
        key_cert_data = self._read_key(self.key_cert_filename)
        dance_result = oauth_dance(self.JIRA_base_url, self.consumer_key, key_cert_data, self.username, self.password,
                                   print_tokens=False)
        oauth_dict = {
            'access_token': dance_result['access_token'],
            'access_token_secret': dance_result['access_token_secret'],
            'consumer_key': self.consumer_key,
            'key_cert': key_cert_data
        }
        self.jira = JIRA(server=self.JIRA_base_url, oauth=oauth_dict)

....
    def _get_issue_worklogs_by_date(self, issue_key, date_start, date_end, month):
        issue_worklogs = self.jira.worklogs(issue_key)
        if issue_worklogs:
            for worklog in issue_worklogs:
                        ...


`

**Comment by ankitg1989** [comment]
@gordeychuk Actually i am using something like below.
jira = JIRA(options={'server': 'https://jiraurl/jira','verify': False}, basic_auth=('username', 'pass'))
issue = jira.issue('jira-ID')
print (len(issue.fields.worklog.worklogs))

I am running the above code and getting length as 20 even when particular JIRA-ID has 26 worklog entries.


As per your code i will get the list of all worklog but how will i further get the data corresponding to each worklog like comments,hours logged,etc.

**Comment by gordeychuk** [comment]
>  how will I further get the data corresponding to each worklog like comments, hours logged, etc.

Just go through the worklogs list, this is a list of **Worklog** objects and each of them contains all the required fields: issue, timeSpent, timeSpentSeconds, adjustEstimate, newEstimate, reduceBy, comment, started, user.

So you can do something like this:
`for worklog in jira.worklogs(issue_key):`
`    print(worklog.comment)`

**Comment by ankitg1989** [comment]
Thanks @gordeychuk , It worked.
