### ISSUE TITLE
how to set description with rich text style

### ISSUE THREAD

**Issue by woshiyushengzhou** [pycontribs/jira#1646]
### Problem trying to solve

I want rich text in the description

**Comment by studioj** [comment]
@woshiyushengzhou 
does this comment help?
https://github.com/pycontribs/jira/issues/1556#issuecomment-1332033220
If we're missing documentation you can always open a PR to update our examples 
https://jira.readthedocs.io/examples.html#
https://github.com/pycontribs/jira/tree/main/examples
