### ISSUE TITLE
add_issues_to_epic does not works

### ISSUE THREAD

**Issue by llarouche** [pycontribs/jira#165]
Hi, 

from jirashell, I'm trying to add an issue to an epic, but it doesn't works. I'm I doing something wrong, or is this not working?

I type the command:
jira.add_issues_to_epic(661846,'MOSOUND-3091') 
and it fails with what's in the attached file.

Thanks, 
Louis
[jirashell.txt](https://github.com/pycontribs/jira/files/89652/jirashell.txt)

**Comment by llarouche** [comment]
jira.add_issues_to_epic(661846,[wIssue.key])  fixed it.

I guess this can be deleted.

**Comment by MuqadderIqbal** [comment]
I was about to submit this issue after encountering the same scenario as @llarouche and found this existing one instead. I agree with @nerakhon. This issue needs to be reopened and the documentation updated to reflect that the "issue_keys" is expected to be a dict and not a string. I spent hours looking for a resolution online as well as going through the source code for the package to see if I could spot the error before landing here.
