### ISSUE TITLE
Getting the context of custom fields

### ISSUE THREAD

**Issue by qequ** [pycontribs/jira#1654]
### Problem trying to solve

Is there a way to have the list of values a field (custom field in my case) can have?

### Additional Context

Using the `issue` only returns data of the issue, not in general

**Comment by Keenpachi** [comment]
you can get this with requests library as described -> 

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-contexts/#api-group-issue-custom-field-contexts

I don't see that this was implemented inside jira library.

**Comment by studioj** [comment]
@qequ @Keenpachi thank you for reporting.
We're open to PR's which could "fix" this feature request.
Don't forget to add a test and excuse us for late responses.
Kind Regards

**Comment by studioj** [comment]
@qequ I'm closing this as it seems to be a duplicate of this one
https://github.com/pycontribs/jira/issues/1619
please reopen if thats not the case

**Comment by qequ** [comment]
@studioj  is still possible to make a pull request with this feature or will it continue as a workaround ?

**Comment by studioj** [comment]
Sure, is the other ticket an ok duplicate?
