### ISSUE TITLE
Is there a way to release fixVersion in a project using this tool?

### ISSUE THREAD

**Issue by gs-rtummalapalli** [pycontribs/jira#166]
It will be most helpful for me to automate my usecase.. I want to release multiple versions in multiple projects based on released modules in our product..

**Comment by eleusis** [comment]
You should be able to update the value of the `released` field on a `resources.Version` instance, using `resources.Version.update()`.

Please endeavour to read the documentation at https://pythonhosted.org/jira/, the Jira REST API documentation (e.g. https://docs.atlassian.com/jira/REST/latest/) and/or the source code to work out if/how certain things can be done. This request is not an issue.

**Comment by gs-rtummalapalli** [comment]
Hi Eleusis,

Thanks a lot..!! I got it... i am able to release version with this..
