### ISSUE TITLE
Unable to update the author of a comment.

### ISSUE THREAD

**Issue by eanxgeek** [pycontribs/jira#167]
I have tried a number of ways to update the author of a comment; however, none seem to work.  A quick review of the code, client.py, seems to indicate that there may be a known issue.  Further, in reading resources.py and client.py I see no obvious evidence that updating the author of a comment is implemented.

```python
from jira import JIRA

options = {
    'server' : 'https://jira.server',
    'verify' : True
}

user = 'esammons'
password = 'password!'
auth = (user, password)
c = JIRA(options = options, basic_auth = auth)

issue = 'JIRA-123'
comment = c.add_comment(issue, 'This is a test comment')

### At this point I tried several different options ####
comment.update....
```

Further the only place where I see updateAuthor is in add_worklog()

Any thoughts on how to get this working, for my use case this is extremely critical?

**Comment by ssbarnea** [comment]
That's not possible using REST api. Please do not raise bugs unless you have the confirmation that the operation is possible using JIRA APIs.
