### ISSUE TITLE
issue.fields has no attribute of 'worklog(s)' in new version

### ISSUE THREAD

**Issue by rion10** [pycontribs/jira#171]
In old releases, e.g.: 0.16 ~ 0.28, I can use issue.fields.worklog.worklogs to get worklogs for one issue, but in new version of jira, I can only use jira.worklogs(issue.key) to get the worklogs, and it seems lower efficient than previous way since worklogs() used to get information from remote server side.
Is it possible to re-add worklog attribute for issue.fields again?
##

**Comment by hdost** [comment]
As of the current version, worklogs can be accessed like the following:`issue.fields.worklog.worklogs[0]`
See: http://jira.readthedocs.io/en/latest/examples.html#fields
