### ISSUE TITLE
Support kerberos authentication

### ISSUE THREAD

**Issue by tuukkamustonen** [pycontribs/jira#174]
I can't find any mentioning of kerberos auth from either code or docs so I assume it's simply not supported at the moment.

On linux, I first fetch Kerberos ticket by:

    kinit

Then in python:

    j = JIRA('https://jira.companydomain')

Causes:

    ...
    line 45, in raise_on_error
        r.status_code, error, r.url, request=request, response=r, **kwargs)
    jira.exceptions.JIRAError: JiraError HTTP 401
            text: Kerberos authentication failed. Please see link XXX
            url: https://jira.companydomain/rest/auth/1/session
            response headers = {'Keep-Alive': 'timeout=15, max=100', 'Date': 'Fri, 19 Feb 2016 11:08:01 GMT', 'Content-Type': 'text/html; charset=iso-8859-1', 'Connection': 'Keep-Alive', 'Content-Length': '124', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'WWW-Authenticate': 'Negotiate'}
            response text = Kerberos authentication failed. Please see link XXX

I don't know kerberos, really, but I assume simply adding https://github.com/requests/requests-kerberos and setting `auth=HTTPKerberosAuth()` should do it...?

**Comment by ssbarnea** [comment]
Kerberos is something that is not supported by JIRA itself and unless you will implement it and also provide a test instance so we can validate it, it would probably never happen.

**Comment by tuukkamustonen** [comment]
Fair enough. PR at https://github.com/pycontribs/jira/pull/175/files
