### ISSUE TITLE
Can we add custom auth as supported by python requests module ?

### ISSUE THREAD

**Issue by anbu78** [pycontribs/jira#179]
Python requests module supports custom auth
http://docs.python-requests.org/en/master/user/advanced/#custom-authentication

But jira client only accepts a tuple as auth
https://github.com/pycontribs/jira/blob/master/jira/client.py#L280

Can we also support callable auth object ?

**Comment by ssbarnea** [comment]
Yes you can, but you will have to contribute using a PR, one that also includes unittests for the added functionality. I am closing this till we get a PR as there are not plans on implementing this ourselves.
