### ISSUE TITLE
Backup for Jira Cloud

### ISSUE THREAD

**Issue by guymatz** [pycontribs/jira#180]
Please provide a mechanism for initiating a backup with Jira Cloud, as well as methods for checking progress and downloading the backup file.

**Comment by ssbarnea** [comment]
I am not going to implement this so if you want to make it happen make a PR or but a bounty. We will reopen it if needed.

**Comment by guymatz** [comment]
https://github.com/pycontribs/jira/pull/181  :-)

I have asked atlassian to add a way to determine whether a server is cloud or Server, and they actually did it!  That will make additions like this one a little easier/cleaner.  

Thanks!!
