### ISSUE TITLE
Cannot get list of attachments

### ISSUE THREAD

**Issue by patrick-bark** [pycontribs/jira#184]
Hey, I am trying to get a list of attachments associated with an issue. From what I am reading in the docs that should be `issue.fields.attachment`, however that field is not present in the issue even though I know that the ticket has attachments. Any ideas here?
##

**Comment by grundic** [comment]
```python
issue = jira_client.issue('TST-123')
for attachment in issue.fields.attachment:
    print(attachment)
```

you can verify that issue has an attachment with JQL
```sql
project = TST and attachments is not EMPTY
```

**Comment by hdost** [comment]
@ssbarnea I think we can close this issue

**Comment by hdost** [comment]
@patrick-bark This issue should be fixed. feel free to re-open.
