### ISSUE TITLE
Add ability to search users by email

### ISSUE THREAD

**Issue by agileminor** [pycontribs/jira#1842]
### Problem trying to solve

Using search_user uses rest/api/2/user/search?username=XXX, which throws the following error for me from Jira Cloud - "The query parameter 'username' is not supported in GDPR strict mode."

### Possible solution(s)

Looks like they want people to use accountId instead, so it would be good to get that added to the supported search commands. Also, email would be useful - /rest/api/3/user/search?query=<e-mail>

### Additional Context

This is discussed here https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

**Comment by supermitch** [comment]
This works fine for me:

```python
        response = requests.get(
            url="https://company.atlassian.net/rest/api/2/user/search/",
            params={"query": "first.last@domain.com"},
            headers={"Authorization": "Basic  <basic auth secret>"},
        )
```

returns the following:

```JSON
[
  {
    "self": "https://company.atlassian.net/rest/api/2/user?accountId=5f2...",
    "accountId": "5f2...",
    "accountType": "atlassian",
    "emailAddress": "first.last@company.com",
    "avatarUrls": {
      "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5f2...",
      ...
    },
    "displayName": "First Last",
    "active": true,
    "timeZone": "blah",
    "locale": "en_US"
  }
]
```

**Comment by agileminor** [comment]
True - but the current code doesn't use query=...., it uses username=..., which has the issue I mentioned above.
The workaround I'm using is to bypass search_user and directly call the rest API with query=.

**Comment by supermitch** [comment]
I see. I posted an edit to how I use this library. See above. You can use the `query` arg with the `search_users` function to search by email.

**Comment by agileminor** [comment]
Thanks - much appreciated.

**Comment by supermitch** [comment]
@agileminor glad that helped. I also just checked, and this seems to match the v3 API behaviour: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-user-search/#api-rest-api-3-user-search-get
