### ISSUE TITLE
Support Pin/Unpin and accessing pinned comments

### ISSUE THREAD

**Issue by marci4** [pycontribs/jira#1877]
### Problem trying to solve

I am looking into accessing the following apis:
* https://docs.atlassian.com/software/jira/docs/api/REST/9.17.0/#api/2/issue-getPinnedComments
* https://docs.atlassian.com/software/jira/docs/api/REST/9.17.0/#api/2/issue-setPinComment

### Possible solution(s)

I would like to support the project and provide a PR

**Comment by dimitarOnGithub** [comment]
@marci4 I think you should just prep a PR, preferably with a test case or two for the flow, and put it for review :)
