### ISSUE TITLE
Get Watchers List

### ISSUE THREAD

**Issue by Simwar** [pycontribs/jira#189]
Hello,

How do I get the list of watchers for an issue?

I see there is a resource but I don't know what to do from there.

**Comment by grundic** [comment]
```python
issue = jira_instance.issue('TST-123)
for watcher in jira_instance.watchers(issue).watchers:
    print(watcher)
```

**Comment by ssbarnea** [comment]
If this would become a PR with documentation update it would be great :)

**Comment by JSinks** [comment]
This issue should be closed now that the documentation has been updated?

**Comment by hdost** [comment]
@ssbarnea I think we can close this issue

**Comment by asqui** [comment]
Looks like it's already closed ;-)
