### ISSUE TITLE
Download Attachments (csv's)

### ISSUE THREAD

**Issue by adtrombley** [pycontribs/jira#191]
There is no documentation on how to download a file to my local (in my case as .csv) and there are several questions identical to mine in atlassian answers - that don't have any answers on how to do this

**Comment by ishah-12** [comment]
I am facing a similar issue as well.

**Comment by ssbarnea** [comment]
I am closing this ticket as it seems like a support ticket and it also seems to lack information. 

We may reopen this ticket if there is a PR referring to it or if someone assigns it to himself and starts working on it. Creating bounty may be a way to speed things up.

**Comment by midnightdim** [comment]
In case someone runs into this old thread as I did, here's the code for downloading attachments of an issue.

```
for attachment in issue.fields.attachment: 
    with open(attachment.filename, "wb") as f:
        f.write(attachment.get())
```
