### ISSUE TITLE
UserWarning: You are running an outdated version of JIRA Python 1.0.6. Current version is 1.0.6.dev20160420173258. Do not file any bugs against older versions.

### ISSUE THREAD

**Issue by jrbenito** [pycontribs/jira#193]
Following issue #156 I forced upgrade of package by doing:

`pip install https://pypi.python.org/packages/f6/ea/2535e412ff76d85da20d2be6d1eaf9aa5de49481da94f2fe7e8830eedd35/jira-1.0.6.dev20160420173258-py2.py3-none-any.whl`

This installed 1.0.6 successfully but even after it the Jira package still complains as:

`<...>/client.py:324: UserWarning: You are running an outdated version of JIRA Python 1.0.6. Current version is 1.0.6.dev20160420173258. Do not file any bugs against older versions.
  __version__, released_version))`

I think there is a check error for versions.

**Comment by drobota** [comment]
I got the same issue after I upgraded jira 

`dm08@dm08:~/projects/zeus (feature/PROTON-35086)$ pip install jira -U
Requirement already up-to-date: jira in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/site-packages (from jira)
Requirement already up-to-date: requests-oauthlib>=0.3.3 in /usr/local/lib/python2.7/site-packages (from jira)
Requirement already up-to-date: requests-toolbelt in /usr/local/lib/python2.7/site-packages (from jira)
Requirement already up-to-date: requests>=2.6.0 in /usr/local/lib/python2.7/site-packages (from jira)
Requirement already up-to-date: tlslite>=0.4.4 in /usr/local/lib/python2.7/site-packages (from jira)
Requirement already up-to-date: oauthlib>=0.6.2 in /usr/local/lib/python2.7/site-packages (from requests-oauthlib>=0.3.3->jira)
dm08@dm08:~/projects/zeus (feature/PROTON-35086)$ pip search jira
jira (1.0.3)                          - Python library for interacting with JIRA via REST APIs.
  INSTALLED: 1.0.3 (latest)
`

**Comment by jrbenito** [comment]
Following Cory´s comment on http://stackoverflow.com/questions/36847031/python-jira-is-not-upgraded-by-pip/  I noticed the release name published on https://pypi.python.org/pypi/jira/json is:

`"version": "1.0.6.dev20160420173258", `

but version declared in the package itself does not match https://github.com/pycontribs/jira/blob/develop/jira/version.py#L10

**Comment by licorna** [comment]
I patched the module to avoid seeing this error until a proper version comes out:

```
import jira
# Monkey patch jira module.
JIRA = jira.JIRA
JIRA._check_update_ = lambda x: True
```

**Comment by ssbarnea** [comment]
This should have not happened as the `dev` release was not supposed to reach pypi server. They will reach the pypi-test server instead as soon I manage to fix the process.
