### ISSUE TITLE
Support for Servicedesk API 

### ISSUE THREAD

**Issue by danielpops** [pycontribs/jira#203]
Hi,

In the latest and greatest jira, there is a rest API for creating servicedesk requests (https://docs.atlassian.com/jira-servicedesk/REST/cloud/#servicedeskapi/request).  Is there a plan to support that in the python-jira client lib?

**Comment by hdost** [comment]
Currently there are two PRs covering this in #371 and #388

**Comment by hdost** [comment]
@ssbarnea in #371 there was mention of making Desk its own module, and from what I can tell #388 is the same change but rebased. however, both need to be rebased. Is there one that you would prefer we start with. I can get the rebase going.

**Comment by wilk** [comment]
What's preventing this project to include the Desk feature?
It'd be really nice having it included.

**Comment by hdost** [comment]
There are service desk resources available in the API, documentation seems to be the only park lacking, but that is being addressed elsewhere,
