### ISSUE TITLE
jirashell - No module named IPython.frontend.terminal.embed

### ISSUE THREAD

**Issue by norricorp** [pycontribs/jira#204]
Hi, trying to use jirashell. Installed jira-python via pip. Running on windows.
c:>jirashell -s http://centos7:8080
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\jirashell.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\jira\jirashell.py", line 255, in main
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named IPython.frontend.terminal.embed

Does anyone know where I have gone wrong?
Regards,
John

**Comment by norricorp** [comment]
As you can see from above, I am running python 2.7.
So installed python 3.5, reinstalled jira-python, installed IPython and then jirashell worked.

**Comment by hamaney** [comment]
> Traceback (most recent call last):
>   File "/home/<>/.local/bin/jirashell", line 8, in <module>
>     sys.exit(main())
>   File "/home/<>/.local/lib/python3.5/site-packages/jira/jirashell.py", line 257, in main
>     import IPython
> ImportError: No module named 'IPython'

same issue for 3.5?
