### ISSUE TITLE
tab expansion not working on windows?

### ISSUE THREAD

**Issue by norricorp** [pycontribs/jira#206]
Hi,
according to the documentation, having got an issue in jirashell, then typing "issue." and tab will expand the properties.
Running jirashell on windows, no propties, just tabs across screen.
Is this a windows bug?

**Comment by hdost** [comment]
@norricorp when you say jirashell do you mean the Python interpreter?

**Comment by norricorp** [comment]
Gosh I raised that a long time ago.
I have just run it again. On windows, open a shell (I have opened powershell)
```
> jirashell -s http://jira.atlassian.com
c:\python35\lib\site-packages\IPython\frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated.
 All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
WARNING: Readline services not available or not loaded.
WARNING: Proper color support under MS Windows requires the pyreadline library.
You can find it at:
http://ipython.org/pyreadline.html

Defaulting color scheme to 'NoColor'
<JIRA Shell 1.0.3 (http://jira.atlassian.com)>

*** JIRA shell active; client is in 'jira'. Press Ctrl-D to exit.

In [1]: issue = jira.issue('JRA-1330')

In [2]: issue.
  File "<ipython-input-2-ba1c81799348>", line 1
    issue.
                ^
SyntaxError: invalid syntax

From http://jira.readthedocs.io/en/latest/jirashell.html
Try getting an issue:
In [1]: issue = jira.issue('JRA-1330')
issue now contains a reference to an issue Resource. To see the available properties and methods, hit the TAB key:

Which is what I did. I typed issue and TAB key. And I get the Syntax error above.

**Comment by hdost** [comment]
If you uninstall IPython and reinstall it what happens? It sounds like they may have been havin issues previously

**Comment by hdost** [comment]
@norricorp any issue after following ☝️

**Comment by norricorp** [comment]
I installed jupyter (I had not installed this before, I thought it was an option for Jira module).
Run jirashell again, retrieved issue, and then used TAB and nothing.
Not sure if this should work on windows or whether the documentation is just very optimistic.

**Comment by hdost** [comment]
@norricorp so it looks like if that's the case you may need to use SHIFT+TAB https://github.com/ContinuumIO/anaconda-issues/issues/298
