### ISSUE TITLE
"issue.fields.components" lacking calls to certain fields/commands

### ISSUE THREAD

**Issue by Kentoseth** [pycontribs/jira#208]
When I use "issue.fields.components", I get certain results from it that seem to be missing from python-jira.

More specifically, here is an example output I get:

```
In [6]: issue.fields.components
Out[6]: [<JIRA Component: name=u'logging-script', id=u'50'>]
```

When I check the supported commands for "issue.fields.components", this is all I see:

```
In [5]: issue.fields.components.
issue.fields.components.append   
issue.fields.components.extend   
issue.fields.components.insert   
issue.fields.components.remove   
issue.fields.components.sort
issue.fields.components.count    
issue.fields.components.index    
issue.fields.components.pop      
issue.fields.components.reverse 
```

There doesn't seem to be any support for something like:

`issue.fields.components.name`
`issue.fields.components.id`

Just thought I would bring this to your attention.

**Comment by danielpops** [comment]
That's because components is a list

`In [11]: type(issue.fields.components)
Out[11]: list`

**Comment by Kentoseth** [comment]
@danielpops 

Is that the expected output when calling: ```issue.fields.components``` (ie. a list of items)?

If so, then this doesn't need to be an improvement

**Comment by danielpops** [comment]
@Kentoseth sounds right to me, since a jira issue can have multiple components.  Similarly, a jira issue can have multiple labels, and that also is a list of items:

```
In [15]: type(issue.fields.labels)
Out[15]: list
```

**Comment by Kentoseth** [comment]
Okay thank you, I will close this.
