### ISSUE TITLE
Allow for deactivating users

### ISSUE THREAD

**Issue by guymatz** [pycontribs/jira#211]
Please allow for the deactivation of users

**Comment by asqui** [comment]
If you can submit a pull request for this it will likely get merged :)

**Comment by guymatz** [comment]
Woo hoo!
https://github.com/pycontribs/jira/pull/217

**Comment by hdost** [comment]
@ssbarnea looks like we can close this issue.

**Comment by hdost** [comment]
Looks like resolved in #217
