### ISSUE TITLE
add_remote_link failes - NotImplementedError: Unable to identify the issue to link to. 

### ISSUE THREAD

**Issue by EricLSD** [pycontribs/jira#213]
When attempting to update a newly created JIRA with a remote link I receive the following error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 441, in call
>     exit_code = func(sopel, trigger)
>   File "/home/esammons/.sopel/modules/sopel-jira.py", line 152, in createtask
>     c.add_remote_link(linkedIssue, updateIssue)
>   File "/usr/local/lib/python2.7/dist-packages/jira/client.py", line 968, in add_remote_link
>     "Unable to identify the issue to link to.")
> NotImplementedError: Unable to identify the issue to link to.

My code follows:

```
   linkedIssue = c.issue(linkedIssueKey)

    fields = {
        'project': {'key' : 'PROJECT'},
        'summary': 'Develop test for ' + linkedIssueKey,
        'description': 'Develop test for ' + linkedIssueKey,
        'issuetype': {'name': 'Task'},
        'components': [{'name': 'test-dev'},],
    }

    try:
        newIssue = c.create_issue(fields=fields, prefetch=True)
    except:
        bot.say("Creating the task failed!")

    try:
        c.add_remote_link(newIssue, linkedIssue)
    except JIRAError as je:
        bot.say("Creating remote link failed, %s" % je)

```

**Comment by hdost** [comment]
@eanxgeek Can you reproduce with the latest version?

**Comment by y9luiz** [comment]
I hade this same issue, using jira version 2.0.0

**Comment by kohtala** [comment]
Me too. Fresh Jira v8.13.10#813010-sha1:156ab00 from atlassian/jira-software:8.13.10 Docker image. Done nothing but create a project and try jira==3.1.1 against it. I'm creating a link within the same project in the same Jira instance. Creating links on the Jira UI is successful.

`/rest/applinks/latest/listApplicationlinks` seems to return `{'list': []}`.

**Comment by kohtala** [comment]
This seems to be a [documentation](https://jira.readthedocs.io/examples.html) issue. Searching for linking in the quickstart Examples, you only find

```
# Linking a remote jira issue (needs applinks to be configured to work)
issue = jira.issue("JRA-1330")
issue2 = jira.issue("XX-23")  # could also be another instance
jira.add_remote_link(issue.id, issue2)
```

Granted, it says you need applinks, which not many know or need, but it also says _could **also** be another instance_ hinting that it just as well might be the local instance.

The [create_issue_link](https://jira.readthedocs.io/api.html#jira.client.JIRA.create_issue_link) is much more difficult to find, but does work.
