### ISSUE TITLE
Support new ability to suppress notifications on update

### ISSUE THREAD

**Issue by lukehankins** [pycontribs/jira#214]
In [JRA-34423](https://jira.atlassian.com/browse/JRA-34423), Atlassian added the ability to suppress notifications on a per-update basis.  The implementation appears to be via a query string parameter (notifyUsers=false) on the update POST, per [the docs](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-editIssue).  It would be great if we could toggle that switch via the issue.update() method.

**Comment by ssbarnea** [comment]
Sure, PR are welcomed.

**Comment by guymatz** [comment]
Should this be part of the update method?  Or should it be it's own method, e.g. issue.set_notify_user(False)?

**Comment by lukehankins** [comment]
It seems more efficient to part of update from a usage point of view.  Having to toggle the option on an issue and then remember to set it back if you later wanted to make an update send a notification feels like it would an opportunity to forget.

**Comment by ssbarnea** [comment]
I would suggest this approach: configuring the default value per session (to notify or not) and allowing users to overwrite it using normal API calls.

**Comment by awakeford** [comment]
Hi, maybe a better solution would be to use the same pattern as for the find() method and create a params=None parameter to update were params would be a dict. 

All params would propagate down to requests via the kwargs and get appended to the URL using the correct ?field=val format.

This would cover all current and future POST parameters.

**Comment by dblachut** [comment]
Maybe some generic solution for query parameters would be nice? A lot of requests has additional query parameters listed in Jira API. It would be nice to be able to do:

```
params = {
    'overrideScreenSecurity': false,
    'anyOtherParameterFromAPI': 'value'
}
issue.update(description='A quiet description change was made', queryParams=params)
```
Above is an example with issue update, but it could be done for an other request.
