### ISSUE TITLE
Missing dependencies in release.sh

### ISSUE THREAD

**Issue by lechat** [pycontribs/jira#219]
`release.sh` depends on `gitchangelog` library (since PR #215), but that library only installed if `Makefile` is used. And it is not used by Travis, so when magically all tests get fixed - release will fail.

I guess that `gitchangelog` needs to be added into test dependencies in `setup.py`

Btw, it is confusing to have both: `Makefile` with bunch of dependencies in `requirements*.txt` files and requirements listed within `setup.py`.

**Comment by hdost** [comment]
I believe this is resolved, please feel free to comment back if it's still an issue.
