### ISSUE TITLE
issue.update fails silently

### ISSUE THREAD

**Issue by lorrin** [pycontribs/jira#22]
I have `customfield_10020` but not `customfield_10099`. On create, I can set `customfield_10020` and I get a `JIRAError` attempting to set `customfield_10099`. This is the behavior I would expect.
```
>>> from jira.client import JIRA
>>> jira = JIRA(options={'server':'http://my-jira-host/'}, basic_auth=('username','password'))
>>> jira.create_issue(project={'key': 'ADRD'}, summary='foo', description='bar', issuetype={'name':'Task'}, customfield_10099=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lhn/.virtualenvs/sonatype-artifact-analysis/lib/python2.7/site-packages/jira/client.py", line 596, in create_issue
    raise_on_error(r)
  File "/Users/lhn/.virtualenvs/sonatype-artifact-analysis/lib/python2.7/site-packages/jira/exceptions.py", line 49, in raise_on_error
    raise JIRAError(r.status_code, error, r.url)
jira.exceptions.JIRAError: HTTP 400: "Field 'customfield_10099' cannot be set. It is not on the appropriate screen, or unknown."
http://pipeline-jira/rest/api/2/issue
>>> issue = jira.create_issue(project={'key': 'ADRD'}, summary='foo', description='bar', issuetype={'name':'Task'}, customfield_10020=3)
>>>
```

However, on issue.update, it behaves as if an update of the non-existent `customfield_10099` succeeded. I would have expected a `JIRAError` here too.
```
>>> issue.update(fields={'customfield_10020':4})
>>> issue.update(fields={'customfield_10099':4})
>>>
```

If I trace through with the debugger I see a `400` (with the goofy error message discussed in #1) come back from the server at  https://github.com/pycontribs/jira/blob/0.33/jira/resources.py#L120, but it is never raised as a `JIRAError`. 

Looks like this is an indentation error introduced in 5d08efe22c5060c9bac432eb2ea9c87649fc55b6. I'll go see about making a pull request.

**Comment by lorrin** [comment]
Hrm. I see that on master c17852a720bfdf187022d9a153e2f27ed282b30d ripped out all the `raise_on_error(r)` invocations from `resources.py`, so it's not a simple matter of just undoing the accidental indentation done in  5d08efe. I'll hold off attempting to fix myself.

**Comment by lorrin** [comment]
Is this fixed now?

**Comment by ssbarnea** [comment]
Please try current release, it should work.

/sorin
