### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by drobota** [pycontribs/jira#220]
Issue https://github.com/pycontribs/jira/issues/193 came up again however with a new version 

```
version of JIRA Python 1.0.3. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
  __version__, released_version)
```

**Comment by msawangwan** [comment]
I am also having this issue -- what is the most optimal solution? Is it a problem to continue using v1.0.3?

**Comment by ssbarnea** [comment]
Cannot reproduce this problem with latest release 1.0.10.
