### ISSUE TITLE
jira current versions have been removed from PyPI

### ISSUE THREAD

**Issue by thanatos** [pycontribs/jira#221]
We have a script that uses `jira`, and depends on `jira>=1.0.3`; it seems that all of {1.0.3, 1.0.4, 1.0.5} were all removed from PyPI, rending anyone who needs to use this script unable to install this. There's some ancient versions … but why? There's also a `.dev` version, but `pip` won't install those by default (for good reason) and #193 states,

> This should have not happened as the dev release was not supposed to reach pypi server.

… so I'm guessing this should not have happened.

<sub>(leftpad…)</sub>

**Comment by thanatos** [comment]
It seems my original post about might be wrong about 1.0.3; that seems to be on PyPI. (The other two, .4, .5, still aren't, but having .3 solves my immediate need, I think.)

I have no idea how ca6cec9 addresses this issue.

**Comment by hdost** [comment]
This is a very old issue. 

@thanatos feel free to re-open if this is still a problem
