### ISSUE TITLE
transition_issue returns JiraError HTTP 500

### ISSUE THREAD

**Issue by kanayak123** [pycontribs/jira#222]
When I execute below code in my python script, I get JiraError HTTP 500 for all closed issues. The transition fails. It works for issues that are in open/in-progress status.
I am using jira-1.0.7.dev20160607111203, Python 3.5 and JIRA 7.0.0.
The JIRA user account that I am using to execute this code has required permissions and also the transitionId is correct. The JIRA server I am using is the replica of the production, so I could upgrade JIRA to 7.1.7. Even after the upgrade the error remains same.

`jira.transition_issue(issue, 122370, transitionId=3)`

I have attached the log from JIRA server and the script.
[jiraerror-g_yjzlao.txt](https://github.com/pycontribs/jira/files/304166/jiraerror-g_yjzlao.txt)

I have many duplicate accounts in JIRA. I am writing a script to move all issues to one account and then delete the unwanted duplicate.

**Comment by devGregA** [comment]
I'm having the same issue.

**Comment by hdost** [comment]
I am unable to reproduce this issue. Is is possible that these issues may have some rules around transitions. Its possible that the workflow for these tickets do not allow for this. 

@kanayak123 I would need a little more context around the full situation before we could do something to resolve this. Feel free to re open.
