### ISSUE TITLE
Error on Jira Server side if trying to attach a new file and the filename contains non-ascii characters

### ISSUE THREAD

**Issue by oechslein** [pycontribs/jira#223]
I'm still on official jira python 1.0.3 (python 2.7) and Jira Server is v7.0.10.
I'm trying to attach a file via add_attachment, something like 
jira.add_attachment('TEST-1234', file, u'FilenameWithUmlautü.txt')
I'm getting a "Oops - an error has occurred" / 500 page.

I digged down how the 'ü' is encoded by the MultipartEncoder and it is encoded with email.utils.encode_rfc2231 into filename*=utf-8''FilenameWithUmlaut%C3%BC.txt"

Any idea how to solve this? Is it a known issue with Jira server maybe?

**Comment by oechslein** [comment]
Forgot to mention that when I remove the "ü" everything works and when I replace "ü" with e.g. "ê" it also fails.

**Comment by Crackmire** [comment]
Hi, I have the same error in this scenario. Did you manage to fix this problem, or find a workaround?

**Comment by oechslein** [comment]
Unfortunately not, still same issue (jira python 1.0.7 (python 2.7) and Jira Server is v7.1.9).

**Comment by guillaume-alvarez** [comment]
I have the same issue.

Is there any known workaround?

**Comment by lizhenwei** [comment]
I have same issue in python 2.7
`
# -- coding: UTF-8 --
from jira import JIRA
url = 'https://www.XXXJIRA.com'

jira = JIRA(server=url, basic_auth=('admin', 'password'))
issue = jira.issue('key-481')
path='resource/目录.png'
filename= "目录.png"
newpath = unicode(path, "UTF-8")
result=jira.add_attachment(issue=issue, attachment=newpath,filename=filename)
`
run this code, return "jira.exceptions.JIRAError: JiraError HTTP 500 url"
can any body help ?

**Comment by ivochkin** [comment]
I've managed to work around the issue. It seems like Jira recognizes B-encoded filenames (RFC 1867) and displays them correctly.

The following piece of code that B-encodes filename works for me:
`
filename= "目录.png"
import base64
filename = "=?UTF-8?B?{}?=".format(base64.b64encode(filename.encode("utf-8")).decode("utf-8"))
`
