### ISSUE TITLE
'issue.fields.attachment' attribute not present in version 1.0.7

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [pycontribs/jira#224]
hi
i have two issues to report.

**Issue 1**
i have upgraded from jira 1.0.3 to 1.0.7 and i am getting this error.actually i upgraded to the package named **jira 1.0.7.dev20160607111203** 

`>>> /usr/lib/python3.4/site-packages/jira/client.py:328: UserWarning: You are running an outdated version of JIRA Python 1.0.7. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
`
How can i rectify this warning.
**Issue 2**
i am trying to access the issue.fields.attachment attribute and i am getting the following errors,

```
Requirement already up-to-date: oauthlib>=0.6.2 in ./.local/lib/python3.4/site-packages (from requests-oauthlib>=0.3.3->jira==1.0.7.dev20160607111203)
[root@master ~]# jirashell -s http://jira.atlassian.com
/usr/lib/python3.4/site-packages/jira/client.py:328: UserWarning: You are running an outdated version of JIRA Python 1.0.7. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
  __version__, released_version))
/usr/lib/python3.4/site-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
<JIRA Shell 1.0.7 (http://jira.atlassian.com)>

*** JIRA shell active; client is in 'jira'. Press Ctrl-D to exit.

In [1]: jira=JIRA('http://issues.apache.org/jira')

In [2]: issue=jira.issue('OPENNLP-840')

In [3]: issue.fields.attachment
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python3.4/site-packages/jira/jirashell.py in <module>()
----> 1 issue.fields.attachment

AttributeError: type object 'PropertyHolder' has no attribute 'attachment'

```

On referring the documentation i can still find issues.fields.attachment attribute present in version 1.0.7.
Where have i gone wrong.Is this some how related to my first issue. kindly do help

**Comment by massdest** [comment]
Hello, same problems here:

```
/usr/local/lib/python3.4/dist-packages/jira/client.py:328: UserWarning: You are running an outdated version of JIRA Python 1.0.7. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
  __version__, released_version))
Traceback (most recent call last):
  File "./importres2.py", line 28, in <module>
    pprint(issue.fields.attachment)
AttributeError: type object 'PropertyHolder' has no attribute 'attachment'
```

On older versions issue.fields.attachment doesnt work for me too.

**Comment by esmaras** [comment]
Hi,

Unfortunately, I am having the same exact problem as well. I am running a python script in a virtualenv and I have run the command 

$ pip install jira-python 

and I get an error telling me that the module doesnt exist. If I find a solution to this question before someone else does I will be sure to share my knowledge here.

**Comment by massdest** [comment]
Hello, Im wrote some simple function for download attachments

```
def download_atachment(issueid):
	filename = "attachments/" + issueid + ".zip"
	fp = open(filename, "wb")
	curl = pycurl.Curl()
	curl.setopt(pycurl.URL, "https://example.jira.com/secure/attachmentzip/" + issueid + ".zip")
	curl.setopt(pycurl.USERPWD, "jirauser:jirapassword") 
	curl.setopt(pycurl.WRITEDATA, fp)
	curl.setopt(pycurl.SSL_VERIFYHOST, 0)
	curl.setopt(pycurl.SSL_VERIFYPEER, 0)
	curl.perform()
	curl.close()
	filename_size = os.path.getsize(filename)
	if filename_size == 0:
		os.remove(filename)
		return None
	else:
		return filename
```

**Comment by andersonpaac** [comment]
Try doing this 
`
jira.search_issues("assignee in (currentUser()) and attachments is NOT EMPTY", fields=["attachment"])
`

**Comment by hdost** [comment]
As of 1.0.11 accessing attachments

No Attachement:
```
issue.fields.attachment
[]
```

With Attachment:
```
issue.fields.attachment
[<JIRA Attachment: filename='email_body.html', id='2497448', mimeType='text/html'>, <JIRA Attachment: filename='email_changes.json', id='2504820', mimeType='application/json'>]
```

This doesn't seem to be an issue at this point.

**Comment by Ads5740** [comment]
Hi, I am running 1.0.11 and this isn't working for me either:

Code (redacted):
```python
options={'server':'https://Jira_url'}
jira = JIRA(options, basic_auth=(id,password), validate=True)
tmp_issues = jira.search_issues('<issue_id>')
if len(tmp_issues) == 0:
            break
print [issue.fields.attachment for issue in tmp_issues]
```

Error:
```win
    print [issue.fields.attachment for issue in tmp_issues]
AttributeError: type object 'PropertyHolder' has no attribute 'attachment'
```
the issue.fields.summary works so connection is good

**Comment by hdost** [comment]
@Ads5740 So I don't know if you saw @andersonpaac's response, but you need include attachment when searching. Otherwise it's not included by default. Keep in mind that once specifying fields you will need to include all fields that you want. That only applies to search. If you are at a point where you know the Key to the issues i.e. PRJ-1123 you can just:
```
issue = jira.issue('PRJ-1123')
issue.fields.attachment
```

**Comment by cappaji** [comment]
@hdost Thanks your comment saved me.

**Comment by iskunk** [comment]
In case it helps anyone else:

I encountered a problem similar to this (perhaps the same?) with 1.0.10, where issues returned from a `JIRA.search_issues()` query were missing the `.attachment` attribute, even when the associated Jira issue had actual attachments.

If I load the issue directly using `JIRA.issue()`, however, then the resulting object had the `.attachment` attribute present and correctly populated.

**Comment by satyamchaturvedi** [comment]
Has anyone got a solution for this? the problem persists in v2.0.0 as well.
through jira shell it shows attachment via issues.fields.attachment but using the script getting same error.. 
AttributeError: type object 'PropertyHolder' has no attribute 'attachment'

**Comment by iskunk** [comment]
Hi @satyamchaturvedi, I think #163 may describe a solution for you. Also have a look at #547 and #672.
