### ISSUE TITLE
jira library should not return an error that an old version of the library is being used when the latest one is not available.

### ISSUE THREAD

**Issue by eanxgeek** [pycontribs/jira#225]
I went to pypi and manually downloaded and install jira 1.0.7 after receiving the following error:

> /usr/lib/python2.7/site-packages/jira-1.0.7-py2.7.egg/jira/client.py:328: UserWarning: You are running an outdated version of JIRA Python 1.0.7. Current version is 1.0.7.dev20160607111203. Do not file any bugs against older versions.
>   **version**, released_version))

When I search out the jira plugin I get the following:

> jira                             - Python library for interacting with JIRA via REST APIs.
>   INSTALLED: 1.0.7
>   LATEST:    1.0.3

You'll notice from the example above, I still get the error even when I am on the most current available.

```
sudo cd jira-1.0.7.dev20160607111203
sudo python setup.py install
```

**Comment by hdost** [comment]
@ssbarnea Seem like we can close this out.
