### ISSUE TITLE
Backup methods should make use of deploymentType of server_info

### ISSUE THREAD

**Issue by guymatz** [pycontribs/jira#234]
Atlassian has introduced a new value of [deploymentType](https://jira.atlassian.com/browse/JRA-60416) in server_info . . .  the backup methods, i.e. backup, backup_complete, etc., should make use of this rather than having a parameter flag

**Comment by guymatz** [comment]
Can I assign this to myself?

**Comment by dbaxa** [comment]
@guymatz feel free to work on this issue and submit a pull request for it.

**Comment by hdost** [comment]
This was fixed in 2016
