### ISSUE TITLE
jira.delete_project() does not do anything

### ISSUE THREAD

**Issue by lechat** [pycontribs/jira#236]
Hi,

As it was mentioned in #80, this method doesn't actually delete project. Instead or REST API DELETE method it uses POST to Jira page. That POST redirects to "Acknowledge deletion" page and that page never gets acknowledgment of course.

Strange thing is that `JiraTestManager` tries to use that method for test preparations and that doesn't affect tests running on TravisCI. But it does affect my local test run...

I've changed `delete_project` to use REST API and added tests. Will submit PR shortly.

**Comment by hdost** [comment]
@ssbarnea looks like this has already been fixed
