### ISSUE TITLE
Add flag to prevent fields loading

### ISSUE THREAD

**Issue by grundic** [pycontribs/jira#240]
After upgrading from 1.0.3 to 1.0.7 I've encounter problems with my tests.
This change was introduced by #93.

I'm using JIRA client with dummy authorization data and mock specific methods that I know are being used. With this change I have to always mock `fields` method to prevent from 401 response. 
I would be absolutely happy if there would some flag in constructor, something like `check_update` that would prevent this behaviour.
Thank you.

**Comment by hdost** [comment]
Closing this issue due to age and lack of activity. 

@grundic  If this is still a problem could you provide a little more context, maybe some sample code? Sounds like this is an issue when testing your code.
