### ISSUE TITLE
how update listselect  value

### ISSUE THREAD

**Issue by hugoren** [pycontribs/jira#249]
```
  How to update listselect value？ 
  Like this : 
          iss.update(fields={'customfield_12300':[{"value":"8"},{"value":"9"}]}) ,but exception  
Can you give me a example
```

**Comment by fender4645** [comment]
The format depends on the field type you're trying to update. Your example above has you updating the same field value twice in a list which I don't think any field supports (maybe a cascading list but I've never used that field type before). What I typically do is, as a test, get the issue object in the debugger and see what field values it accepts.

**Comment by hdost** [comment]
Closing this issue as is seems like a question more than an actual issue. Also has not been updated in more than a year and context is unclear.
