### ISSUE TITLE
import configparser and from six.moves does not work with certain Python 2.7 installs

### ISSUE THREAD

**Issue by BuildMonkey** [pycontribs/jira#25]
Certain installs of python 2.7 do not have
  from six.moves import configparser
when it fails to import Python 3's
  import configparser
module.

I see that it supports Python 2.7 and Python 3. Can this check which version of Python is loaded and from there determine
Python 2.* import ConfigParser
Python 3: import configparser

Thanks

**Comment by ssbarnea** [comment]
Please be sure that you are using the latest release as I do know as fixing this. If you are able to replicate the issue be sure that you can report: exact python version and the versions of jira and six modules.

**Comment by BuildMonkey** [comment]
We only installed the module earlier this week so it's good to see it has been resolved since then. We will install the 0.39 version shortly. I did also log another issue with 0.38. I didn't see verification on that one, but I hope the resolution is in 0.39 as well.
