### ISSUE TITLE
add_user does not use 'directoryId'

### ISSUE THREAD

**Issue by noqqe** [pycontribs/jira#250]
Hi,

The API reference in the docs say `directoryId` is `1` as default. 

```
add_user(username, email, directoryId=1, password=None, fullname=None, notify=False, active=True, ignore_existing=False)
```

However its not `1` when you use it. 
A quick look in the code shows that `directoryId` parameter isn't used at all during the creation:

https://github.com/pycontribs/jira/blob/4983cba00791991c27672321a4815f17e71f64e9/jira/client.py#L2641-L2686

Its this because the Jira REST API itself does not implement it?

https://docs.atlassian.com/jira/REST/server/#api/2/user-createUser

**Comment by noqqe** [comment]
Any news here?

**Comment by noqqe** [comment]
I'm not entirely sure if you understand what this means. You basically cannot create Users in Directories other than the first one. Even worse, the tool gives you the impression you can choose to just drop your configuration parameter right after you specified it.

I find this a serious bug, tbh.

**Comment by hdost** [comment]
@ssbarnea my suggestion on this would be to just remove the parameter.
