### ISSUE TITLE
search_issues fails ~1/50 with KeyError in _fetch_pages

### ISSUE THREAD

**Issue by michaelk-stratoscale** [pycontribs/jira#253]
When calling search_issues, this code (in _fetch_pages), occasionally fails with resource returns as a dict with no 'issues' key.

```
resource = self._get_json(request_path, params=page_params, base=base)
next_items_page = [item_type(self._options, self._session, raw_issue_json) for raw_issue_json in (resource[items_key] if items_key else resource)]
```

```
/usr/lib/python2.7/site-packages/jira/client.pyc in search_issues(self, jql_str, startAt, maxResults, validate_query, fields, expand, json_result)
   1728             return self._get_json('search', params=search_params)
   1729 
-> 1730         issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
   1731 
   1732         if untranslate:

/usr/lib/python2.7/site-packages/jira/client.pyc in _fetch_pages(self, item_type, items_key, request_path, startAt, maxResults, params, base)
    382         resource = self._get_json(request_path, params=page_params, base=base)
    383         next_items_page = [item_type(self._options, self._session, raw_issue_json) for raw_issue_json in
--> 384                            (resource[items_key] if items_key else resource)]
    385         items = next_items_page
    386 

KeyError: u'issues'
```

Script that reproduces the issue quite consistently (~1/50):

```
import jira
i = 0
jiraClient = jira.JIRA('https://XXXXX.atlassian.net', basic_auth=('XXXXX', 'XXXXX'))
jql = "XXXXXXXXXXXXXXXXX"
while True:
    try:
        jiraClient.search_issues(jql)
        i += 1
    except Exception as e:
        print e
        print i
```

**Comment by michaelk-stratoscale** [comment]
BTW, to bypass the problem i've downgraded to 1.0.3 which does not have the issue.

**Comment by Fr3dBear** [comment]
1.0.7 seems to have a problem with the way it uses the search query in regards to the max returned results.

I had a similar problem: https://github.com/pycontribs/jira/issues/229

**Comment by michaelk-stratoscale** [comment]
@Fr3dBear , i fail to see how these two are related (except for both being in search_issues method, and found in 1.0.7). You described a problem where a URL is malformed every time maxResults was set to False. The issue i'm reporting here is a sporadic failure to retrieve search results.

**Comment by Fr3dBear** [comment]
I have misunderstood the problem you are having. However I do believe that by default maxResults is set to false unless otherwise specified. (This probably means nothing in regards to your problem)
```python
import jira
i = 0
jiraClient = jira.JIRA('https://XXXXX.atlassian.net', basic_auth=('XXXXX', 'XXXXX'))
jql = "XXXXXXXXXXXXXXXXX"
while True:
    try:
        jiraClient.search_issues(jql)
        i += 1
    except Exception as e:
        print e
        print i
```
As search_issues returns a list of issues, I am uncertain why this indefinite loop is present while no change to the query is made. Could you provide insight?

**Comment by hdost** [comment]
Unable to replicate issue using provided code. If this is still an issue feel free to re-open.
