### ISSUE TITLE
package_meta tries to run git on module load (also, fails in python 2.7 if "git branch" fails)

### ISSUE THREAD

**Issue by olivierlefloch** [pycontribs/jira#258]
I'm surprised that importing the jira client now runs `git branch` in a subprocess seemingly irrespective of being in development or not. This seems like a high performance cost to be paying at module import when not running in development. This is the case on the `develop` branch.

Also, `run_but_ignore_errors` fails in python 2.7 when there is an error in the `try` section:

```
        try:
            return subprocess.check_output(*args, shell=True, stderr=devnull,
                                           **kwargs)
        except (subprocess.SubprocessError,
                FileNotFoundError, OSError):
            return None
```

because `subprocess.SubprocessError` was introduced in Python 3.3: `AttributeError: 'module' object has no attribute 'SubprocessError'`.

**Comment by hdost** [comment]
I don't see that there is a `git branch` run anymore anywhere in the code. Closing.
