### ISSUE TITLE
Conflicting documentation sites

### ISSUE THREAD

**Issue by FrancescoRizzi** [pycontribs/jira#26]
I think this is due to the ongoing transfer of the project from one site to another, but figured I'd bring it up...

So, https://jira-python.readthedocs.org/en/latest/
And http://jira.readthedocs.org/en/latest/

List different version numbers (and different URLs for the source), but use the same package name for pip (pip install jira).. Of course, one of the two is wrong (the older jira-python if I had to guess?)
HTH

**Comment by ssbarnea** [comment]
Sorted, now the old link was removed. Still, it will take some time for google indexing to bring the new one on the top.
