### ISSUE TITLE
Watcher list isn't being shown

### ISSUE THREAD

**Issue by jporanga** [pycontribs/jira#260]
I can't get the watcher list.

When I execute jira.watchers(issue) I get the following output:
\<JIRA Watchers at 86636360\>

**Comment by fender4645** [comment]
That's because jira.watchers() returns a JIRA Watchers object. If you're trying to get a list of watchers for a given issue then you need to iterate through watchers.watchers:

```
watchers_list = jira.watchers(issue).watchers
for watcher in watchers_list:
    print watcher.name
```
