### ISSUE TITLE
Why is the requests requirement so high?

### ISSUE THREAD

**Issue by gmmeyer** [pycontribs/jira#261]
Requests is currently set at 2.10. Is there any reason for this? 

As far as I can tell--both from the code and from some testing I've done--it could be much lower. A lot of people are still using lower versions of requests in their apps.

Is there any particular reason why it's so high?

**Comment by ssbarnea** [comment]
I do not remember but if you want to downgrade it feel free to add a pull request with a working version and if it does not break anything I will accept it.

I will close this bug as I am not willing to spend any time testing compatibility with older versions of requests library, but you are still welcomed to make a PR.
