### ISSUE TITLE
add_remote_link() causes JiraError 400: url: https://url/issue.key/remotelink details

### ISSUE THREAD

**Issue by eanxgeek** [pycontribs/jira#263]
When attempting add_remote_link() I receive the following:

> JIRAError: JiraError HTTP 400 url: https://issues.jboss.org/rest/api/2/issue/iddue-xxxx/remotelink details: /tmp/jiraerror-olxOW6.tmp (file "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 55, in raise_on_error)

My code creates a new issue (newIssue) and tries to link to an original / related issue (linkedIssue).

`c.add_remote_link(newIssue.key, linkedIssue.key)`

**Comment by Fr3dBear** [comment]
Not sure if you will have the same problem but you might want to try the create_issue_link function: [link](http://pythonhosted.org/jira/#jira.JIRA.create_issue_link)

**Comment by candy901122** [comment]
I am facing the same issue, when trying to create connection.

authed_jira = JIRA(options, basic_auth=('username', 'passwd')) 

It had been worked for me, but when jirap server upgrade to JIRA 7.2.7
