### ISSUE TITLE
Search_issues is creating a bad url. 

### ISSUE THREAD

**Issue by cfortuner** [pycontribs/jira#269]
Trying to use the search_issues function is returning:

JiraError HTTP 404 url: https://jira.riotgames.com/rest/api/2/search?maxResults=False&validateQuery=True&jql=project+%3D+SCM&startAt=0 details: /var/folders/_m/wnb0sxqs67l6b3gn2pylxwlj_lknc3/T/jiraerror-b9ybpoc3.tmp

The search_params: validateQuery and maxResults dont seem to be working correctly.

**Comment by Fr3dBear** [comment]
This is probably related to #229 a source fix is at the bottom. You should try using the modified client.py file. If this does not work, I have been able to circumvent the error in my own tests by defining maxResults to anything but False, such as 500. [https://jira.riotgames.com/rest/api/2/search?maxResults=500&validateQuery=True&jql=project+%3D+SCM&startAt=0](https://jira.riotgames.com/rest/api/2/search?maxResults=500&validateQuery=True&jql=project+%3D+SCM&startAt=0)

If all this fails go back to jira version 1.0.3, which suits most needs with the exception of the Outward/Inward issueLinks functionality.

**Comment by hdost** [comment]
Closing for same reason as #229
