### ISSUE TITLE
search_issues yields error 400 (The value does not exist for the field 'project')

### ISSUE THREAD

**Issue by FrancescoRizzi** [pycontribs/jira#27]
All right, I wouldn't be surprised if there's something I'm doing wrong here, but I can't spot it, so I wonder if anyone can enlighten me...
I'm getting error 400 ("The value 'project_id' does not exist for the field 'project'") when querying via search_issues, but the same query work in jirashell.

I've anonymized the name of our atlassian instance, user id and password below of course, but I am able to log in with those credentials to the atlassian instance, so that shouldn't be the problem.

(as of this morning, with jira 0.39)

via jirashell:

jirashell -s https://[our_instance].atlassian.net -u [uid] -p [psw]
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/frontend.py:30: UserWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  warn("The top-level `frontend` package has been deprecated. "
<JIRA Shell 0.39 (https://[our_instance].atlassian.net)>

*** JIRA shell active; client is in 'jira'. Press Ctrl-D to exit.
In [1]: projects = jira.projects()
In [2]: keys = sorted([project.key for project in projects])
In [3]: print ','.join(keys)
MI
In [4]: issues = jira.search_issues('project=MI')
In [5]: print len(issues)
42

On the other hand, I have a python script serving a web page.
This script uses my JIRAClient wrapper:

import sys
from jira.client import JIRA
class JIRAClient:
   def __init__(self):
      jiraOpts = {
         'server': 'https://[our_instance].atlassian.net',
         'basic_auth': ('uid', 'pwd')
      }
      self.jira = JIRA(jiraOpts)

   def GetIssues(self):
      qry = 'project=MI'
      return self.jira.search_issues(qry)

This leads to the error:
  File "/Users/frankr/Documents/Mobi/SyncService_trunk/tools/MIIT/JIRAClient.py", line 38, in GetIssues
    return self.jira.search_issues(qry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jira/client.py", line 1433, in search_issues
    resource = self._get_json('search', params=search_params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jira/client.py", line 1853, in _get_json
    r = self._session.get(url, params=params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jira/resilientsession.py", line 78, in get
    return self.__verb('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jira/resilientsession.py", line 74, in __verb
    raise_on_error(r, verb=verb, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
JIRAError: JiraError HTTP 400
   text: The value 'MI' does not exist for the field 'project'.
	url: https://[our_instance].atlassian.net/rest/api/2/search?jql=project%3DMI&validateQuery=True&startAt=0&maxResults=50

Additional info:
qry='project="MI"' produces the same results
self.jira.search_issues(qry, validate_query=False) produces no error but returns an empty list

**Comment by ssbarnea** [comment]
I almost sure you are using a different user or you are not even logged in and that's why you get this error. This is what happens when you do not have access to the MI project. The query is perfect and as you observed it does work in a different context.

**Comment by FrancescoRizzi** [comment]
Thanks, but.. isn't the 'basic_auth' option I'm using when instantiating the JIRA object all I have to do to "log in" (I'm using the term loosely, of course)?

jiraOpts = {
'server': 'https://[our_instance].atlassian.net',
'basic_auth': ('uid', 'pwd')
}
self.jira = JIRA(jiraOpts)
return self.jira.search_issues(qry)

**Comment by ssbarnea** [comment]
Print the current user after you do instantiate. If your instance allows anonymous you will not get an exception even if your credentials are wrong.

**Comment by FrancescoRizzi** [comment]
Resolved: Closing the issue as it was an issue with my code.

THIS IS WRONG:
jiraOpts = {
'server': 'https://[our_instance].atlassian.net',
'basic_auth': ('uid', 'pwd')
}
self.jira = JIRA(jiraOpts)
return self.jira.search_issues(qry)

THIS IS RIGHT:
jiraOpts = {
'server': 'https://[our_instance].atlassian.net'
}
self.jira = JIRA(jiraOpts, basic_auth=('uid', 'pwd')
return self.jira.search_issues(qry)

Thank you for the help
