### ISSUE TITLE
jira-1.0.7 tag / release missing on github

### ISSUE THREAD

**Issue by austin987** [pycontribs/jira#270]
pypi has the release: https://pypi.python.org/pypi/jira

and a tarball: https://pypi.python.org/packages/4e/36/4f0ab121c3510fce29743c31e2f47e99c2be68ee4441ad395366489351b0/jira-1.0.7.tar.gz#md5=cb1d3f1e1b7a388932ad5d961bf2c56d

as well as a link to a github tarball:
https://github.com/pycontribs/jira/archive/1.0.7.tar.gz

that's 404:
austin@austin2:~$ wget https://github.com/pycontribs/jira/archive/1.0.7.tar.gz
--2016-10-18 16:20:09--  https://github.com/pycontribs/jira/archive/1.0.7.tar.gz
Resolving github.com... 192.30.253.112
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/pycontribs/jira/tar.gz/1.0.7 [following]
--2016-10-18 16:20:09--  https://codeload.github.com/pycontribs/jira/tar.gz/1.0.7
Resolving codeload.github.com... 192.30.253.120
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-10-18 16:20:10 ERROR 404: Not Found.

**Comment by mrueg** [comment]
@ssbarnea can you help us out here and add a tag?

**Comment by ssbarnea** [comment]
@mrueg sure but can you tell me which changeset should I tag?

**Comment by andrey-utkin** [comment]
Could you maybe make a tag for _new_ release (1.0.8 I guess) so that whatever you tag, it will be authoritative. Nobody would need 1.0.7 then (unless you break something, in which case people would need to downgrade and need old tag :) ).

**Comment by mrueg** [comment]
@ssbarnea what @andrey-utkin works for me as well. I'm just interested in a tagged src version :)

**Comment by ssbarnea** [comment]
Fixed few weeks ago, now we have tags.
