### ISSUE TITLE
User don't have KEY field which breaks integrity

### ISSUE THREAD

**Issue by President** [pycontribs/jira#281]
jira.group_members("jira-users") returns list of users where KEY field is actually NOT a user's key but a user's name!
But this field - user's name can be changed in JIRA by administrator and this causes big problem if we want to extract the data and keep the references between the entities.

Example:
1.you exported users to your database
2.you exported issues and linked them to the users (you should use issue.fields.assignee.name, as you cannot use fields.assignee.key because you don't know the user's keys)
3.you changed user's name
4.you exported new users (new user is created which is actually a duplicate)
5. you trying to sync issues and link them to users and new issues are linked to new user.
Now you have duplicate users both with issues!

Suggestion:
jira.group_members() should use user's key for keys and user's name field should be among other user's fields together with email and fullname.

JIRA's API already supports this - 
"/rest/api/2/group?groupname=#{groupname}&expand=users"  returns JSON with users' keys.

Please fix this.

**Comment by President** [comment]
this requires actually a very simple change:
_def group_members()_ should be updated
...
result[user['**key**']] = {**'name': user['name'],** 'fullname': user['displayName'], 'email': user.get('emailAddress', 'hidden'), 'active': user['active']}
...

**Comment by asqui** [comment]
Seems like a sensible suggestion. Please submit a pull request for this and it will be incorporated into the library.

@ssbarnea: This would be a breaking change. Any code that is already using `group_members()` will begin to receive different results. What is our approach for handling breaking changes to the library?

**Comment by ssbarnea** [comment]
Usually we should not break the API. Still, if it solves a broken API and it adds tests, I would not mind merging the change into a newer minor or major version (but not in a patch one).

Just make a PR and I will take care to be merged at the right moment.

**Comment by NfNitLoop** [comment]
I think we can make a change here that doesn't break backward compatibility:

Keep the same (dictionary) key in the return results, but add a new "key" property to the dictionary that gets returned for each user. That entry will contain the "key" value from the Jira API.

I was reading the source to figure this out, so I might have enough of this in my head to make a PR this weekend.

One thing to note, this is using the [deprecated] /rest/api/2/group endpoint, so the return values/schema aren't even documented there. 🙁 

[deprecated]: https://docs.atlassian.com/jira/REST/server/#api/2/group-getGroup

**Comment by NfNitLoop** [comment]
*poke*   My team is still using the branch which I've got open in PR #281 so that we can access the Jira primary key.  Is there anything in particular I need to do to help get the fix merged into mainline?
