### ISSUE TITLE
Unnecessary dependency causes conflict with package tlslite-ng

### ISSUE THREAD

**Issue by ilan700** [pycontribs/jira#290]
The package metadata lists:
"Requires-Dist: tlslite (>=0.4.4)"
However the package tlslite is never used by the jira package. tlslite is an outdated package. It was renamed to tlslite-ng in the newer versions. It is now not possible to use the packages 'jira' and 'tlslite-ng' together.
The fix should be to simply remove the dependency from the metadata.

**Comment by ssbarnea** [comment]
This was fixed develop and will be included in next release.
