### ISSUE TITLE
JIRA(validate=True) doesn't raise exception when user is not authenticated

### ISSUE THREAD

**Issue by lukas-bednar** [pycontribs/jira#300]
This part of code promises that I should get exception when user is not authenticated, but it passes this section without problem ...
https://github.com/pycontribs/jira/blob/develop/jira/client.py#L296
```
            # This will raise an Exception if you are not allowed to login.
            # It's better to fail faster than later.
            self.session()
```
it fails further on issue #298

**Comment by hdost** [comment]
This is fixed as of 1.0.10
