### ISSUE TITLE
Exception AttributeError on close 

### ISSUE THREAD

**Issue by BuildMonkey** [pycontribs/jira#31]
Exception AttributeError: "'NoneType' object has no attribute 'magic_close'" in <function <lambda> at 0x1a290c8> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method JIRA.__del__ of <jira.client.JIRA object at 0z1a16a10>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'warn'" in <function cleanup at 0x1a19d70> ignored

Problem is the __del__ method
  if session is not None:
    session.close()

and the _try_magic() method call

**Comment by ssbarnea** [comment]
Can you you be more explicit, maybe a pull request? ;)

**Comment by BuildMonkey** [comment]
It is in the 0.39 release.

**Comment by BuildMonkey** [comment]
Is there any progress on this?

Thanks.

**Comment by sargentstudley** [comment]
Can you provide a code snippet that produces this error?

**Comment by ssbarnea** [comment]
closing due to lack of feedback.

**Comment by BuildMonkey** [comment]
I will get you the code snippet tomorrow. Please do not close out this issue because it is valid.


Thanks.

**Comment by BuildMonkey** [comment]
Upon further testing, I receive those error messages when the utility exits prematurely. Is there a way in an Exception block to close out the session?

**Comment by sargentstudley** [comment]
Is the utility you are using the Jira Shell, or something else? Are there any logs or error messages that indicate what is causing the application to exit prematurely?
