### ISSUE TITLE
allow for cert based authentication

### ISSUE THREAD

**Issue by j5awry** [pycontribs/jira#311]
Current implementation allows for basic auth, oauth, and kerberos. Expand to include cert based authentication. 

This can be implemented as a possible resilient session using cert based auth with Requests lib. Add in arguments to allow passing certs, which then implements cert based auth

**Comment by j5awry** [comment]
I should be able to help with this. I've forked and will begin looking more seriously at this.

**Comment by fdcds** [comment]
Duplicated by #637 and #558?

**Comment by fdcds** [comment]
Please reopen, this is still relevant. There is a fix available in #838 (which was sadly also closed before its time).

**Comment by tomasbedrich** [comment]
As a workaround, I was able to pass `JIRA(server_url, {"client_cert": ...}, basic_auth=("foo", "bar"))`.

Given that your Jira is configured to use client-cert, it probably ignores HTTP basic auth. Fortunately, the code handling basic auth sessions in this library adds `client_cert` to that session. Just quick hack until #838 is merged.
