### ISSUE TITLE
Applying/updating malformed label does not produce exception

### ISSUE THREAD

**Issue by fender4645** [pycontribs/jira#32]
```
from jira.client import JIRA
jira = JIRA(options={'server': JIRA_URL})
issue = jira.issue('SB-15')

issue.fields.labels.append("this should not work")
issue.update(fields={"labels": issue.fields.labels})
```

This should fail but as it exists now will exit with 0. Making the same call via the REST API produces an expected HTTP Error 400.

**Comment by sargentstudley** [comment]
I've started working on this.

**Comment by sargentstudley** [comment]
I've made a push request for two unit tests to cover the positive and negative scenarios discussed. Both are passing locally, so I am curious to see how it works in travis CI. 

@fender4645, can you provide which version of JIRA, Python, and Jira-Python you are using? 

Thanks.

**Comment by ssbarnea** [comment]
v0.40 works as expected so I am closing this. If it doesn't feel free to reopen it.

**Comment by fender4645** [comment]
Thanks. Verified you get the appropriate error in v0.40.
