### ISSUE TITLE
ImportError: cannot import name JIRA

### ISSUE THREAD

**Issue by kuberkaul** [pycontribs/jira#320]
I have already done` pip install jira` 

but when I run the following it fails with **ImportError: cannot import name JIRA** :

```
import re
from jira import JIRA

jira = JIRA('https://issues.net')
# all values are samples and won't work in your code!
key_cert_data = None
key_cert_file = "cert/jiraprivatekey.pub"
with open(key_cert, 'r') as key_cert_file:
    key_cert_data = key_cert_file.read()
```

**Comment by ssbarnea** [comment]
I can assure you that `from jira import JIRA` works on all supported version of Python.

**Comment by nirzari** [comment]
@kuberkaul 
It won't work if your file name is 'jira.py'
[1] https://stackoverflow.com/questions/41621566/python-cannot-import-name-jira

**Comment by thakkardharmik** [comment]
I am seeing the issue on OSX. I am trying in python shell.

```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jira import JIRA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name JIRA
>>>
```

**Comment by hdost** [comment]
@thakkardharmik 
There are a couple things that could be happening here.
A. There is a clashing jira.py
B. The python jira module is not installed at all
C. The python jira module is not installed for the correct version

# Problem A
```
➜  ~ python
Python 2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
>>> jira.__file__
'jira.pyc'
>>> quit()
```
The indicator is that `jira.__file__` will show either `jira.py` or `jira.pyc`

**Solution A**

# Problem B
```
➜  ~ python     
Python 2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named jira
>>> quit()
```
```
➜  ~ python3
Python 3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named jira
>>> quit()
```

# Problem C
```
➜  ~ pip -V      
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
➜  ~ pip2 -V
pip 9.0.3 from /usr/lib/python2.7/site-packages (python 2.7)
➜  ~ 
```
If you did a `pip install jira` it's possible that the `pip` does not match your `python`. To make sure that you install it to the proper python you can run `python -m pip install jira` or `python3 -m pip install jira`

**Comment by vucanthi** [comment]
Hi, I've run into this issue and still can't figure out. I looked at all the possible solutions. Is there any other issue that might have arise since 2018? I have Python 3.6

pip 20.3.1 from /home/vunguye/.local/lib/python3.6/site-packages/pip (python 3.6)

Really appreciate any help.

**Comment by ama-ana** [comment]
I had the same issue and tried all options found over the internet. The solution was to use 'python script.py' instead of just 'script.py' I used on previous python versions ;)

**Comment by macetw** [comment]
When I arrived at this problem, I found that part of my `pip3 install ...` step had failed, so nothing from the large requirements-file was installed. Correcting the failing package resolved the problem.

**Comment by Bloomnum** [comment]
hi! Solution B - it's worked! 
`python3 -m pip install jira`

**Comment by TonyJelev** [comment]
> @kuberkaul It won't work if your file name is 'jira.py' [1] https://stackoverflow.com/questions/41621566/python-cannot-import-name-jira

I usualy browse github, without an account, but you my friend... You made me create one and upvote you. Thank you big time!
