### ISSUE TITLE
Update CHANGELOG and tags

### ISSUE THREAD

**Issue by tuukkamustonen** [pycontribs/jira#321]
Looks like CHANGELOG in master is out of date (last release is 1.0.4 there), some release tags are missing and tags are in odd order anyway (their timestamps seem odd)?

**Comment by ssbarnea** [comment]
Upload of changelogs to github release is currently blocked by https://github.com/travis-ci/travis-ci/issues/6423 -- I suggest you to add some comments there in order to get it fixed.
