### ISSUE TITLE
Cookies based authentication support

### ISSUE THREAD

**Issue by MaximBB** [pycontribs/jira#324]
It would be useful to add cookies based authentication support into this module
It was raised before in: https://github.com/pycontribs/jira/issues/72
It is also described in
https://jira.atlassian.com/browse/JRA-44654

I didn't assess all consequences but the result could be achieved with a small workaround in the existing code and calling constructor JIRA with "Validate" parameter. Extra line of the code is shown in bold below. 
I suppose it could be done in more reliable and elaborate way (maybe just adding one extra parameter for conditional launch of this part of the code) in one of future releases

client.py

```
def session(self):
        """Get a dict of the current authenticated user's session information."""
        url = '{server}/rest/auth/1/session'.format(**self._options)

        if isinstance(self._session.auth, tuple):
            authentication_data = {
                'username': self._session.auth[0], 'password': self._session.auth[1]}
```
            **## self._session.auth=None #Custom - remove authorization at every call**
```
            r = self._session.post(url, data=json.dumps(authentication_data))
        else:
            r = self._session.get(url)

        user = User(self._options, self._session, json_loads(r))
        return user
```

**Comment by jettero** [comment]
I'm trying to make a command-line tool to automate stuff. The only login method available to me on this corp-jira is basic auth... I would really need this cookie-based session persistence to use this module. I'm surprised it's not already sorted since this module is so otherwise kickass.

Hrm.

**Comment by jettero** [comment]
The above PR is how I would do it. In fact, I'm installing this at my house currently.

**Comment by MaximBB** [comment]
inject one line of code into client.py as suggested above and you get needed result. Cookie will be used automatically instead of sending login/password everytime
self._session.auth=None #Custom - remove authorization at every call

It works if you initiation with "validat" 
e.g.:
jira = JIRA(server,basic_auth=(user, passw),validate=True)

**Comment by jettero** [comment]
I wanted to be able to save the cookie externally and pass it back in ... possibly saving multiple cookies I can switch between; but especially the requirement for me is having the program exit, save the cookie, and use the cookie on the next run.

Just commenting out the one line doesn't achieve that result afaik.
