### ISSUE TITLE
Old issues not available on Bitbucket

### ISSUE THREAD

**Issue by tomikall** [pycontribs/jira#33]
In your code base, there's a reference (in a warning) to https://bitbucket.org/bspeakmon/jira-python/issue/46. The issues on the Bitbucket repo are closed, though, or at least they can no longer be accessed (Access denied).

The old issues should be made available somewhere for reference.

**Comment by ssbarnea** [comment]
Hmm, i will try to copy those that are referenced. I asked Ben to make the old repo private because people where still opening tickets on the old one.

/sorin
