### ISSUE TITLE
Basic Auth no longer works

### ISSUE THREAD

**Issue by isaacanderson** [pycontribs/jira#343]
I can no longer auth using basic auth when constructing  a JIRA client instance.

The server info endpoint retrieval fails with a http 401.  Adding get_server_info=False just results in a http 401 on a different endpoint.

The last time the script was working that I can confirm was Jan 20.

When I encountered the issue I upgraded from 1.0.5 to 1.0.10 and the issue persisted.

I've also tried changing the credentials used from my JIRA log in to my all combinations of my JIRA username, Bitbucket username, email, with both my old jira/bitbucket passwords my new atlassian account password.

**Comment by ssbarnea** [comment]
Are you sure that this is not related to use of a Cloud hosted instance or a specific version of JIRA? Travis CI is using basic authentication and is passed the test which makes me think that this problem is specific to your environment.

**Comment by isaacanderson** [comment]
I believe I have solved the issue by using a username password combination I could have sworn failed previously.
