### ISSUE TITLE
sessions not getting closed

### ISSUE THREAD

**Issue by jhsenjaliya** [pycontribs/jira#354]
we have noticed that use of this library opens new sessions at regular interval, and does not close it gracefully. even-though session.close() is getting called in __del__ method, but the issue is that method is used by garbage collector not guaranteed to be called, python community has preference over using rather contextManager so that it can be called via "with" to take care of closing of the session gracefully.

creating this issue to check if anybody has any workaround or suggestion and would be nice if someone can verify the behavior as well.

ps: Eventually the session might get closed by the server, but we want to be proactively closing the session once the interaction is over.

**Comment by ssbarnea** [comment]
Well, for most people this was not an issue but I always welcome pull requests.

**Comment by hdost** [comment]
@jhsenjaliya are you interested in investigating this issues?

**Comment by jhsenjaliya** [comment]
@hdost its been a while, let me check on this next week to push PR. Thanks
