### ISSUE TITLE
Implement the JIRA Software REST API Reference

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#355]
From what I saw from the code, the GreenHopper implementation is a bit dated and does not use much of the API available on the [JIRA Software REST API Reference](https://docs.atlassian.com/jira-software/REST/cloud/). 

The advantage of this would be that we would have access to a clean json allowing to access agile data, instead of custom fields. For instance the [get issue](https://docs.atlassian.com/jira-software/REST/cloud/#agile/1.0/issue-getIssue) method allows to get information about the epics of the sprints without needing to go through custom fields. Finding information about the sprints of a story can be especially cumbersome as one can read on the "JIRA Software field input formats" section of the [JIRA Cloud REST API Reference](https://docs.atlassian.com/jira/REST/cloud/)  

I came across this problem as I was trying to write code to propagate Stories and Epics from a source project to a target project, where I have three sub teams, which need to have three separate backlogs. I know it is ugly, but can't have the same backlog for a sub-teams doing NodeJS, another one doing iOS and a last one doing Android. Technologies are too different. /) Hopefully I get the time to finish this code and open-source it 😃 .

From what I saw, it might be a good idea to leave `GreenHopperResource` as it is and create an `AgileResource`, from which the following resources could inherit:

- `AgileBoard`
- `AgileEpic`
- `AgileIssue`
- `AgileSprint`

I have started a project on this at https://github.com/esciara/jira/projects/1 . If this is not the best way to move forward with this, please shout. Any constructive feedback welcome.

**Comment by ssbarnea** [comment]
I am in favour or gradually migrate to a single JIRA() class that knows about Agile and ServiceDesk. So we should have classes only for Issue, Board, Sprint but not for Epic, this being just a type of Issue.

**Comment by esciara** [comment]
Will look into it for the single `JIRA()` class. 

As for Epics, they have a specific API on JIRA and do also have some specific qualities. Have a look at the links to the doc I gave previously. I think it makes sense that we follow the api's logic in this respect. What do you think?

**Comment by esciara** [comment]
> I am in favour or gradually migrate to a single JIRA() class that knows about Agile and ServiceDesk. 
@ssbarnea can you be more specific as to what you mean by migrate? `ServiceDesk` seems to be in there already. `GreenHopper` is already deprecated.

**Comment by atiniir** [comment]
is there a way to access the agile boards and sprints without using the greenhopper api ?  .boards returns an error from my jira server "Warning: Old private GreenHopper API is used, all parameters will be ignored."
