### ISSUE TITLE
[tip] how to get a test instance from atlassian

### ISSUE THREAD

**Issue by lipkau** [pycontribs/jira#356]
Hi.

I hope you don't mind me contacting you directly.
Your email was available on your github profile.

I saw you are the current maintainer of pycontribs/jira.
And I would be interested about some tips:

I am collaborating on a library to do the same as your module, but for PowerShell (replicaJunction/PSJira)
However, I want to make my CI better. I want the UnitTests to actually connect to a server and perform real activities instead of mocking everything.

I saw the Credits of your repo, in particular this part:
Atlassian for developing such a powerful issue tracker and for providing a free on-demand JIRA instance that we can use for continous integration testing.
So to my real question: How did you get that instance? And is it possible for me to get something similar?

Thanks

**Comment by ssbarnea** [comment]
Use this page to request a license or a cloud instance from Atlassian.
https://www.atlassian.com/software/views/open-source-license-request
