### ISSUE TITLE
Validate comment documentation is up to date. 

### ISSUE THREAD

**Issue by mramanathan** [pycontribs/jira#358]
After successfully completing basic authentication, I setup a jira object to the production server.

On the jira object, while trying to extract the comment text using the id of that comment, instead of text, command returns the comment id.

Referred to the docs for the usage, it looks to be ok.

Tried this from jirashell.

`In [70]: cmnt = jira.comment('SREC-255', '2590283')`
`In [71]: print cmnt1`
`Out[71]: <JIRA Comment: id=u'2590283'>`

What's wrong with the usage here ?

**Comment by suresh753** [comment]
I do not know but you can get comments 
issue = jira.issue(SREC-255) 
issue.raw['fields']['comment']['comments']

**Comment by fender4645** [comment]
@mramanathan I know this is old but for historical sake, the "comment()" method returns a Comment object. If you want the text, you need to get the "body" property:
```
cmnt = jira.comment('SREC-255', '2590283')
print cmnt.body
```

**Comment by nojiratz** [comment]
Genius! The cmt.body is exactly what I was looking for!

**Comment by hrm232** [comment]
I tried above code it did not work, hence tried as follow way. I get error at last line of snippet. 
Any idea what's missing?

jql='project = TMP AND key = TMP-281 ORDER BY createdDate ASC'
issues = jira.search_issues(jql, 0, 1000)
for issue in issues:
    print(issue.fields.issuetype.name)
    print(issue.fields.reporter.displayName)
    print(issue.fields.comment.comments)

**Comment by fender4645** [comment]
@hrm232 what's the error you're getting with your code? issue.fields.comment.comments will return a list of comment objects (one object for each comment in the issue)...or an empty list if there aren't any comments in the issue.

**Comment by alexmgr** [comment]
@fender4645 I'm hitting the same error as @hrm232 on `1.0.10` and `1.0.11`. You essentially get an `AttributeError`:
```
import jira as jira_

jira = jira_.JIRA(url, basic_auth=(username, password))
issues = jira.search_issues(SOME_QUERY)
for issue in issues:
    # This works and returns comments as intended
    print([comment.body for comment in jira.comments(issue)])
    # Works fine
    print(issue.fields.summary, issue.fields.description)
    # This raises attribute error:
    # AttributeError: type object 'PropertyHolder' has no attribute 'comment'
    print(issue.fields.comment.comments)
```
Versions (I'm on `1.0.10` due to #501 ):
```
certifi==2018.1.18
chardet==3.0.4
defusedxml==0.5.0
idna==2.6
jira==1.0.10
oauthlib==2.0.6
pbr==3.1.1
requests==2.18.4
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
six==1.11.0
urllib3==1.22
```

**Comment by chalbersma** [comment]
I'm getting the same error as @alexmgr with `jira==1.0.15`. Interestingly I don't see the error when using jirashell.

**Comment by eschwaiger** [comment]
@hrm232 Same issue but I think I figured it out. When you do your jira.search_issue you have to specify fields to pull with it, in this case your comments fields. Try this:

jql='project = TMP AND key = TMP-281 ORDER BY createdDate ASC'
issues = jira.search_issues(jql, 0, 1000, fields='comments')
for issue in issues:
print(issue.fields.issuetype.name)
print(issue.fields.reporter.displayName)
print(issue.fields.comment.comments)

No more errors, hope this helps.
