### ISSUE TITLE
@not_on_custom_jira_instance tag not allowing to test on any other instance than pycontribs.atlassian.net

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#359]
The way the not_on_custom_jira_instance means that any other instance than pycontribs.atlassian.net is considered a custom instance : (https://github.com/pycontribs/jira/blob/ff7fe0b8cd901e6d84abafbc10a5eab405568649/tests/tests.py#L71-L77)
```python
if 'CI_JIRA_URL' in os.environ:
    not_on_custom_jira_instance = pytest.mark.skipif(True, reason="Not applicable for custom JIRA instance")
    logging.info('Picked up custom JIRA engine.')
else:
    def noop(arg):
        return arg
    not_on_custom_jira_instance = noop
```
And that means that a lot of tests are not run when not using a "custom" Jira instance... 
But I would love to run my tests on an instance of Jira on my machine for better speed.

Could someone explain why singling out these tests?

**Comment by hdost** [comment]
@esciara The reason for a lot of these custom tests is because many things are generated in JIRA, and these tests which are skipped during custom instance rely on the specific IDs, but hopefully as part of #543 we can isolate some of these tests to be even tighter scope.
