### ISSUE TITLE
Support to deactivate a user

### ISSUE THREAD

**Issue by fabio-silva-movile** [pycontribs/jira#36]
The jira-python api and the Jira Rest API cannot deactivate a user directly, look at theses links:

https://jira.atlassian.com/browse/JRA-37294
https://answers.atlassian.com/questions/292406/how-to-change-a-user-activity-status-by-rest-api

But this is a usefull feature for me, that want to create a script to manage users in jira. There is any way to perform this action? I tried the following but without success:

user = jira.user(username)
user.update({"active":"false"})

This raise the following exception:

  File "/home/fabio/git-repositories/jira-scripts/jira-scripts-env/local/lib/python2.7/site-packages/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.utils.JIRAError: JiraError HTTP 400
	text: error.no.value.found.to.be.changed

**Comment by ssbarnea** [comment]
The usual question: have you tried the same operation using REST browser or with curl?

**Comment by ak-ambi** [comment]
Something is changing in JiRA according to comments from linked JIRA issue. Functionality is implemented, but no details whether and when this will be deployed.

**Comment by ssbarnea** [comment]
I am closing this ticket due to the lack of additional information. Still, we do accept PRs.
