### ISSUE TITLE
IntelliJ/PyCharm reformat code rules

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#360]
Hi guys,

Being new to the project and wanting to follow its code formatting rules using IntelliJ/PyCharm, could you point out the right rules/file that could enforce these rules? Did not find anything on the project. ~~Maybe could use a file with [EditorConfig Plugin](https://plugins.jetbrains.com/plugin/7294-editorconfig) (though not sure how it works...)~~ It is actually used...

Let me know.

Em

**Comment by esciara** [comment]
PS: current `.editorconfig` file does not work well as I systematically get these changes when I use IntelliJ's code format functionality:
```python
class ResourceTests(unittest.TestCase):

    def setUp(self):
        pass
```
=>
```python
class ResourceTests(unittest.TestCase):
    def setUp(self):
        pass
```

**Comment by esciara** [comment]
Found the answer in this question [how to share code style settings between developers in IntelliJ](http://stackoverflow.com/questions/9087439/how-to-share-code-style-settings-between-developers-in-intellij).

@ssbarnea, would it be a good idea to version control `.idea/codeStyleSettings.xml` so that all can use the same rules?

**Comment by ssbarnea** [comment]
Feel free to make a PR that adds this file, I would not be against it. Still, be aware that the official way of testing the codestyle is part of the tox testing, not specific to your editor. 

I am using PyCharm too so I will appreciate it.

**Comment by esciara** [comment]
@ssbarnea would love to, but don't have a working version and I am having difficulties finding the right settings. I assumed that you already had the right settings in your PyCharm since you are working on the project since a while. Could you send me yours, through a gist or anyother way? Can then create the PR.

Let me know.

**Comment by blakev** [comment]
I wouldn't recommend adding the `.idea` folder at the project level. It's developer specific and should be universally skipped in `.gitignore`.

If you want to enforce coding style create a flake8 profile.

**Comment by esciara** [comment]
Hi @blakev . From what I read, `.idea/codeStyleSettings.xml` is not developer specific but project specific. Hence the idea. 

Unless you suggest there is a way to create a flake8 profile and integrate it in the IDE so that it is possible to use the tool's reformat code capabilities (in which case I would love to have more info), then it would means each time one needs to do that manually... impractical.

**Comment by blakev** [comment]
The point is `.idea` isn't ubiquitous to all development environments, and IDE-specific configuration files should not be included in the core project.

**Comment by ssbarnea** [comment]
I agree with @esciara here and if the `codeStyleSettings.xml` will produce files that are passing our pep8, I will include the file as I would find it useful too. Please note that this is not the user-specific project file, these should not be stored with the project.

Anyway, these project files will not be included in the source distributions, they are just development configuration files.

IntalliJ is sponsoring us by providing free licenses of their PyCharm and I do find the tool extremely valuable, even if I am not always using it. I use a mix of mcedit, atom and pycharm.

**Comment by esciara** [comment]
Not moving forward much on this... Cannot find info on how to best configure the code style on PyCharm/IntelliJ to get the right `codeStyleSettings.xml`. I would need a working example to work with...

**Comment by hdost** [comment]
@esciara @ssbarnea Is this something that we are going to move further on or should we close it?

**Comment by esciara** [comment]
I haven't found something sufficiently rigorous to move forward with. So let's close it, and if I find something interesting, I will reopen it and offer a PR.
