### ISSUE TITLE
ipython dependency

### ISSUE THREAD

**Issue by ari** [pycontribs/jira#361]
I used pip to install this module, but that didn't bring in ipython which is required by the jirashell command.

**Comment by ssbarnea** [comment]
This is fixed on development branch and will be included in the next release. Feel free to reopen if you think that the fix was incomplete.

**Comment by ssbarnea** [comment]
Fixing this bug in main branch raised a new one and I will need your oppinion regarding the best way to address it. Read and vote on https://stackoverflow.com/questions/44165253/should-cli-commands-be-installed-by-default-with-python-libraries
