### ISSUE TITLE
Expand worklogs if total > maxResults

### ISSUE THREAD

**Issue by smbelsky** [pycontribs/jira#363]
Currently, if a JIRA Issue has worklogs, that field response is structured as follows:

```
{
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "id": "316785",
    "self": "https://server.jirainstance.com/rest/api/2/issue/316785",
    "key": "ABC-123",
    "fields": {
        ...
        "worklog": {
            "startAt": 0,
            "maxResults": 20,
            "total": 2454,
            "worklogs": [{wl1}, {wl2}...{wl20},]
            }
        }
    }
```

Presently, whether you use the JIRA.issue(key) method or the jira.search_issues(key, expand='worklog') method, the API call only returns the first 20 worklogs. It appears to be impossible to get more than 20 worklogs. 

However, if you hit https://server.jirainstance.com/rest/api/2/issue/316785/worklog, this will return all worklogs as a JSON, where maxResults == total. 

We have reporting that depends on using these worklogs, but we're currently impeded by this limitation. Can we possibly use this issue/123456/worklog API call in order to supply JIRA.issue.fields.worklog with data, rather than relying on the data from the issue/123456 API call itself? I'm happy to take a stab at a PR.

Open to other approaches to solving this problem. Is it possible to increase maxResults using the jira.issue() or any other method? 

Thanks!

**Comment by jough** [comment]
+1

**Comment by smbelsky** [comment]
I'm going to close this issue, after reading a different section of the code. It looks like the JIRA class in jira/client is structured so that you can simply call jira.worklogs(key) to return a list of all worklogs for a given ticket. Per the snippet of code below (lines 1321-1329 currently) it looks like this is calling the exact API url described in my initial issue above.

Therefore, if you're looking to get all worklogs, use the jira.worklog method instead of trying to get all worklogs from the jira.issue object. Sorry for the noise! 

```
    def worklogs(self, issue):
        """Get a list of worklog Resources from the server for an issue.
        :param issue: ID or key of the issue to get worklogs from
        """
        r_json = self._get_json('issue/' + str(issue) + '/worklog')
        worklogs = [Worklog(self._options, self._session, raw_worklog_json)
                    for raw_worklog_json in r_json['worklogs']]
        return worklogs
```
