### ISSUE TITLE
Travis failed from fork on exact same commit that passed on original repo

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#366]
Created a [branch](/esciara/jira/tree/issue_360) based on [commit passing on Travis](https://travis-ci.org/pycontribs/jira/builds/205810346) and had the [same commit fail the build](https://travis-ci.org/esciara/jira/builds/209573955).

Same tests failed on the 4 flavors of python:
```
tests/tests.py::IssueTests::test_transitioning FAILED
[..]
tests/tests.py::UserTests::test_user FAILED
```

**Comment by esciara** [comment]
[Build on the next commit](https://travis-ci.org/esciara/jira/builds/209579570) failed again but for different reasons, even as the files which change are [two files unrelated to code](https://github.com/esciara/jira/compare/693b2f06af44...2a7b3f1890e5).

@ssbarnea does that mean that the tests are not reliably reproductible ? If this is the case, any indication as what could be done to make them reproductible. Otherwise it will be hard to confidently make the code evolve safely and in confidence... :-/

**Comment by esciara** [comment]
Reproduced problems error logs available at https://gist.github.com/esciara/7a7b8576cc293cf0fff2fdd1bbea6fe0

**Comment by esciara** [comment]
`test_transition` still fails when run on Travis where as it works fine when started on my computer (even though it still uses pycontribs.atlassian.net as the test JIRA cloud:
```
    def test_transitioning(self):
        # we check with both issue-as-string or issue-as-object
        transitions = []
        for issue in [self.issue_2, self.jira.issue(self.issue_2)]:
            transitions = self.jira.transitions(issue)
>           self.assertTrue(transitions, msg="Expecting at least one transition but had none for issue %s" % issue)
E           AssertionError: [] is not true : Expecting at least one transition but had none for issue Z130018E9B-2
```
Look on the test JIRA cloud, it turns out that the issue *does not have transitions indeed*:
![image](https://cloud.githubusercontent.com/assets/1336689/24224009/38627508-0f59-11e7-9f9f-a63090f491b8.png)

Where as when run on my computer targeting the same JIRA Cloud instance, the issue created *has* transitions:
![image](https://cloud.githubusercontent.com/assets/1336689/24224072/7ae2bfe6-0f59-11e7-9ab9-4e9ef731296d.png)

**Comment by esciara** [comment]
@ssbarnea would love some help on this.

Also found out that other issues created by the travis run do have the transitions with them:
![image](https://cloud.githubusercontent.com/assets/1336689/24225621/d419108a-0f61-11e7-9e14-d4853b98adca.png)
The difference between these ones and the other ones is that these one have been created during the test, where as the other ones have been created in during the `__init__` of the `JiraTestManager`class.

And I am not sure whether what I said earlier is a good idea...

> **Third issue's** log:
>```
>    def test_session_with_no_logged_in_user_raises(self):
>>       anon_jira = JIRA('https://support.atlassian.com', logging=False)
>
>;31tests.py:1946: 
>```
>JIRAError raise on code:
>```
>    def test_session_with_no_logged_in_user_raises(self):
>        anon_jira = JIRA('https://support.atlassian.com', logging=False)
>        self.assertRaises(JIRAError, anon_jira.session)
>```
>Surprised it worked as it should use a with self.assertRaises(JIRAError):

**Comment by ssbarnea** [comment]
I very late here but here is what I found while trying to investigate this a couple of weeks ago: is about the params you are using to create the project. With same params Jira creates a project with an invalid scheme that doesn't allow you to transition issues. This is what happens, not the trick is to find a way to avoid it, especially with default params for create_project.

**Comment by esciara** [comment]
Thanks. Two things to investigate then:

1. Why is this behaving differently when running on Travis and running on my mac?
1. Why some issues created on the same project have transitions and other don't => that would suggest that the problem is not around params during project creating as you suggest @ssbarnea , but around the issue creation (?).

**Comment by esciara** [comment]
@ssbarnea : nothing to do with defaults or anything else. `test_transitioning` [did not pass when run with all other tests](https://travis-ci.org/esciara/jira/jobs/214456657), but [passed when run alone](https://travis-ci.org/esciara/jira/jobs/214608365) (see [commit diff](https://github.com/esciara/jira/compare/9adfb9fcfd25...2ed6bc231b27) for code changes).

This means that the tests are not reliably repeatable. It passes or not depending on context. I am intending to look into this, but any info will be appreciated.

**Comment by ssbarnea** [comment]
That's what happens when testing is done against a SaaS product. Travis run the tests in parallel and the results are close to those that you would get by running with "detox".

As we cannot really fix Jira Cloud, we need to work on the test to make them more reliable. In the end the users of the library will probably use it with various Jira instances, some of them in the cloud.

I know that getting unpredictable results from tests is not something we all dream about. On the bright side, that's a challenge for improving the execution to make it more reliable.

**Comment by esciara** [comment]
@ssbarnea : I managed to reproduce the problem. And ~there is a solution~ I am not sure there is a complete solution: read on.

The problem is happening when the 4 Travis jobs are started at the same time. Then the Jira Cloud instance gets on overload somehow and does not function properly, resulting in the issues 1, 2 and 3 creations being incomplete (in this case not having transitions).

When I start the 4 jobs one after the other in sequence, then the tests pass. For instance, I first launched [this build](https://travis-ci.org/esciara/jira/builds/214811933) initially through a push and all jobs failed. Then I relaunched the [first of the four jobs](https://travis-ci.org/esciara/jira/jobs/214811936) manually, and it passed.

You can [force Travis to run only one job at a time](https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/). I did this on my fork and [all jobs of the next build ran fine](https://travis-ci.org/esciara/jira/builds/214834837). You should do that on the repository to avoid problems.

Beware though: it has happened though that the job on python 2.7 still fails sometimes. I wonder whether this is due to the fact that it runs in parallel mode... Or does it? **Note:** sometimes, other is fails with other versions of python.

Also, when commits are pushed to pull requests, not one but two builds (containing each 4 jobs) are being started simultaneously... So it would be no surprise if they fail. This is actually what happened on my last push on pull request #370 : the [build on your repo failed on all jobs](https://travis-ci.org/pycontribs/jira/builds/214846154), and only two jobs of the [build on my fork](https://travis-ci.org/esciara/jira/builds/214846145) failed.

**Comment by esciara** [comment]
OK, this one is solved. 

By re-reading https://github.com/pycontribs/jira/issues/366#issuecomment-288574977 , I realised I could use the fact that the only the issues created in `__init__` had no transitions (probably because the project is too freshly created) but that subsequently created issue have those transitions. So the test creates and deletes one for its own use, like the `test_update` tests do.

Now other tests issues related to concurrent testing have cropped up. Will report in different issue.

**Comment by ssbarnea** [comment]
I was expecting a bug in JIRA. I will add you the the ticket that I opened with Atlassian so you can provide more information to them.

If you could build a small script replicates the bug it would be wonderful because they could fix it!

**Comment by hdost** [comment]
@ssbarnea sounds like this was an issue in JIRA itself. Is this still some open issue?

**Comment by hdost** [comment]
A fair amount of work has gone into solving this. Recently had to make a fix, but I'm gonna call this good.
