### ISSUE TITLE
Problem with add_worklog

### ISSUE THREAD

**Issue by flyasky** [pycontribs/jira#369]
With python 2.7.12 ubuntu 16.10
code on line 1500 in client.py
```
if started is not None:
  # based on REST Browser it needs: "2014-06-03T08:21:01.273+0000"
  data['started'] = started.strftime("%Y-%m-%dT%H:%M:%S.000%z")
```
Did not actually add "+0000" on "%z" so Jira returns HTTP Error 500.

**Comment by flyasky** [comment]
And the same with python 3.6

**Comment by flyasky** [comment]
today_time = datetime.now(timezone.utc)

**Comment by MrPrezident** [comment]
I ran into this same problem. Since timezone is required here, but it is optional for datetime, it would make sense to catch this error early so that the user sees a more readable error message something like this:

```
            if started.tzinfo:
                data['started'] = started.strftime("%Y-%m-%dT%H:%M:%S.000%z")
            else:
                raise JIRAError("'started' parameter is missing timezone information")
```
