### ISSUE TITLE
test_add_group and other group related tests fail from time to time

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#373]
As seen in job https://travis-ci.org/pycontribs/jira/jobs/214981947 for instance. This happens mainly in Travis during concurrently run tests.

The error message cropping up is:
```
E           JIRAError: JiraError HTTP 404 url: https://pycontribs.atlassian.net/rest/api/latest/group?groupname=testGroupFor_Z130018E9A
E           	text: The group named 'testGroupFor_Z130018E9A' does not exist
```

**Comment by hdost** [comment]
Test suites have been fixed, not seeing this anymore.
