### ISSUE TITLE
test_update_version fails with error "A version with this name already exists in this project."

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#374]
This happened on the following jobs:

* https://travis-ci.org/esciara/jira/jobs/214981940
* https://travis-ci.org/esciara/jira/jobs/214981942

Full error message is:
```
E           JIRAError: JiraError HTTP 400 url: https://pycontribs.atlassian.net/rest/api/2/version
E           	text: A version with this name already exists in this project.
```
This offending code is:
```python
    @flaky
    def test_update_version(self):
    
        version = self.jira.create_version('new updated version 1',
                                           self.project_b, releaseDate='2015-03-11',
>                                          description='new to be updated!')
tests/tests.py:1889: 
```
There is no other version created in the test code with name "new updated version 1". Does this mean that another concurrent test is using the same projet `self.project_b` as this one? That seems to be the only possibility.

To investigate.

**Comment by hdost** [comment]
Closing, citing the last comment in #375
