### ISSUE TITLE
Adding built-in resilience into jira library

### ISSUE THREAD

**Issue by esciara** [pycontribs/jira#375]
@ssbarnea , I was thinking... We are facing a lot of issues in the test suite, which are linked to the fact that JIRA Cloud is not always responsive, and does not finish the job internally by the time the next bit of code is run (#366, #373, #374 and counting)... Well isn't that something that people will face in their own usage of the library as well?! 

I mean, a lot of code is written in the tests to check, wait and make sure that we can go through the next bit of code. Why not instead build that in the library? Like having an `ensure_transaction` flag, which if set to `True`, would check that the action has taken effect. 

It could take this form:
```
    def add_group(self, groupname, ensure_transaction=False, max_tries=5, wait_time_before_retry=1):
```
In the above example, if `ensure_transaction` was set to `True`, then a `find()` would be triggered after the `add_group` action is sent to JIRA, and if it cannot find the group, it would try up to `max_tries` times and wait `wait_time_before_retry` seconds between each try.

We could do the same for the deletes on Resources, amongst other actions:
```
    def delete(self, params=None, ensure_transaction=False, max_tries=5, wait_time_before_retry=1):
```

What do you think ?

**Comment by asqui** [comment]
Sounds like a neat idea, but rather than having these settings on each individual method, I'd put them on the constructor only, to avoid polluting the interface of every method with three extra arguments that are orthogonal to the purpose of the method.

**Comment by ssbarnea** [comment]
Exactly, any resiliency support should controlled from the instance level, not at method level.
