### ISSUE TITLE
Importing jira fails because pbr assumes either an sdist tarball or upstream git repository

### ISSUE THREAD

**Issue by JorisE** [pycontribs/jira#376]
Following the pretty straight-forward installation instructions, I end up with the following error when trying to import jira:

```
In [1]: from jira import JIRA
---------------------------------------------------------------------------
DistributionNotFound                      Traceback (most recent call last)
/home/joris/.virtualenvs/jira/lib/python3.6/site-packages/pbr/version.py in _get_version_from_pkg_resources(self)
    439             requirement = pkg_resources.Requirement.parse(self.package)
--> 440             provider = pkg_resources.get_provider(requirement)
    441             result_string = provider.version

/usr/lib/python3.6/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    425     if isinstance(moduleOrReq, Requirement):
--> 426         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    427     try:

/usr/lib/python3.6/site-packages/pkg_resources/__init__.py in require(self, *requirements)
    967         """
--> 968         needed = self.resolve(parse_requirements(requirements))
    969 

/usr/lib/python3.6/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    853                         requirers = required_by.get(req, None)
--> 854                         raise DistributionNotFound(req, requirers)
    855                 to_activate.append(dist)

DistributionNotFound: The 'jira' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-1-70d1a867bf64> in <module>()
----> 1 from jira import JIRA

/home/joris/.virtualenvs/jira/lib/python3.6/site-packages/jira/__init__.py in <module>()
      4 from pbr.version import VersionInfo
      5 
----> 6 _v = VersionInfo('jira').semantic_version()
      7 __version__ = _v.release_string()
      8 version_info = _v.version_tuple()

/home/joris/.virtualenvs/jira/lib/python3.6/site-packages/pbr/version.py in semantic_version(self)
    458         """Return the SemanticVersion object for this version."""
    459         if self._semantic is None:
--> 460             self._semantic = self._get_version_from_pkg_resources()
    461         return self._semantic
    462 

/home/joris/.virtualenvs/jira/lib/python3.6/site-packages/pbr/version.py in _get_version_from_pkg_resources(self)
    445             # installed into anything. Revert to setup-time logic.
    446             from pbr import packaging
--> 447             result_string = packaging.get_version(self.package)
    448         return SemanticVersion.from_pip_string(result_string)
    449 

/home/joris/.virtualenvs/jira/lib/python3.6/site-packages/pbr/packaging.py in get_version(package_name, pre_version)
    748                     " to pbr.version.VersionInfo. Project name {name} was"
    749                     " given, but was not able to be found.".format(
--> 750                         name=package_name))
    751 
    752 

Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name jira was given, but was not able to be found.
```

I may be missing something, but this looks like it is not supposed to happen. Testing the versions that are available on Pypi I found 1.0..3 to be working. It seems that this has been introduced in version 1.0.7.

**Comment by ssbarnea** [comment]
Which method did you use to install? Please provide full information about OS, virtualenvs and how you installed the package so we can reproduce the problem.

Pbr is caching the version at compile time, the only case where it needs git is when you install in developer (editable) mode.

**Comment by JorisE** [comment]
This happened on Arch Linux using `pip install jira` in a fresh virtualenv.

I have just tested a systemwide (non-virtualenv) install and to my surprise that worked. I a fresh virtualenv it failed again.

**Comment by ssbarnea** [comment]
Python version and result of "pip freeze" inside the virtualenv. Also try, after this, to upgrade pip and setuptools inside the venv. Alternatively you can try "pip install -U jira" too.

**Comment by JorisE** [comment]
pip freeze:
```
$ pip freeze
appdirs==1.4.3
defusedxml==0.5.0
jira==1.0.10
oauthlib==2.0.2
packaging==16.8
pbr==2.0.0
pyparsing==2.2.0
requests==2.13.0
requests-oauthlib==0.8.0
requests-toolbelt==0.7.1
six==1.10.0
```
with pip and virtualenv updated.

Two noteworthy things:
 * This happens in ipython, but not in a plain python shell. 
 * This does not happen when run from any directory that has a git repository.

**Comment by ssbarnea** [comment]
My mistake, you need to run `pip freeze --all`, the normal output is missing exactly what I was interested about: pip and setuptools versions.

**Comment by JorisE** [comment]
np, here it is:

```
pip freeze --all       
appdirs==1.4.3
defusedxml==0.5.0
jira==1.0.10
oauthlib==2.0.2
packaging==16.8
pbr==2.0.0
pip==9.0.1
pyparsing==2.2.0
requests==2.13.0
requests-oauthlib==0.8.0
requests-toolbelt==0.7.1
setuptools==34.3.3
six==1.10.0
virtualenv==15.1.0
wheel==0.29.0
```

**Comment by ssbarnea** [comment]
I am almost sure that there is something wrong with your environment, maybe with ipython installation itself. If "python -c "import jira; print(jira.__version__)" works, I doubt there is a problem with the module.

I here is another: considering that ipython is not reported by your pip freeze I came to the conclusion that you are not running the right one.

Is try that jira package 1.0.6 does not install ipyton itself, you need to install it yourself.

**Comment by ewangchong** [comment]
Is this ticket fixed? I tried to run it in AWS Lambda function it still exists.

**Comment by mromey** [comment]
Having the same issue.  Developing on OSX, did a pip download into my Lambda repo of the JIRA package and its dependencies using the following command.

python3 -m pip download --platform=manylinux1 --python-version 3.8 --only-binary=:all: jira

As a result, getting the following errors in CloudWatch when I attempt to import (from jira import JIRA).

00 | Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name jira was given, but was not able to be found.
-- | --




00 | Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name jira was given, but was not able to be found.
-- | --

**Comment by kevwo** [comment]
This is a problem with the way pbr collects the version. It conveniently works if running inside a git repo.

@mromey **A workaround would be to set a dummy environmental variable prior to invoking your script: PBR_VERSION = "1.0"**

I don't know if there are any side effects from this, but it works well for me.

The full stack trace in case @ssbarnea was curious. Although I see pbr dependency has been removed in master so might already be fixed in the next release.

Traceback (most recent call last):
  File "jira\__init__.py", line 6, in <module>
  File "pbr\version.py", line 462, in semantic_version
  File "pbr\version.py", line 449, in _get_version_from_pkg_resources
  File "pbr\packaging.py", line 870, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name jira was given, but was not able to be found.

**Comment by ssbarnea** [comment]
@kevwo With all due respect to others that want to fix bugs in this library I have to say that I decided to let it rot until I will see at least one jira user using https://github.com/sponsors/ssbarnea 

PS. I know how to fix it, pbr can be replaced by setuptools-scm but this needs time, especially as the library CI/CD jobs were broken for very long time.

**Comment by harshi-g** [comment]
As a work around keeping the idna packages along with the jira packages worked for me in the lambda function:
idna, idna-2.6.dist-info, jira and jira-1.0.15.dist-info
