### ISSUE TITLE
Unable to equate issue.fields.assignee.displayName to string.

### ISSUE THREAD

**Issue by RatanShreshtha** [pycontribs/jira#377]
I am trying to write a script that uses JIRA python library to reassign issues to someone else based on a set of conditions but when I try to equate issue.fields.assignee.displayName == 'Ratan Kulshreshtha' it gives me false.

I have double checked the displayName but still, I am getting False as the response.

```
from jira import JIRA

from mail_settings.settings import JIRA_PASSWORD, JIRA_QA, JIRA_USERNAME, jira_options

def commentOnJIRA(jiraId, context):
    currentCommitIdShort = success_context['currentCommitIdShort']
    lastCommitIdShort = success_context['lastCommitIdShort']
    timestamp = success_context['timestamp']
    apiReportUrl = success_context['apiReportUrl']

    try:
        jira = JIRA(jira_options, basic_auth=(JIRA_USERNAME, JIRA_PASSWORD))
        issue = jira.issue(jiraId)
        newComment = "some thing"
        jira.add_comment(jiraId, newComment)
        if issue.fields.assignee.displayName == 'Ratan Kulshreshtha':
            jira.assign_issue(issue, JIRA_QA)
        return "JIRA comment done and reasign done."
    except Exception as e:
        print("Unable to comment on JIRA.")
        print(e)
        raise
```

I am trying this snippet on Fedora 25, with python 2.7.13 and jira-1.0.10.

**Comment by Fr3dBear** [comment]
I did a little testing with jirashell, with relation to assignee's. It seems that the `assignee.displayName` atribute returns a string in the format of "lastname, firstname". You could try this by making your string "Kulshreshtha, Ratan".

Alternatively and probably safer, is to find the keyname that the user has, as this returns an all lowercase string that will be void of weird conventions such as the "," that displayName has

**Comment by RatanShreshtha** [comment]
But when I printed assignee.displayName it printed Ratan Kulshreshtha on the stdout.

**Comment by Fr3dBear** [comment]
Again, i suggest using `assignee.key` rather then `assignee.displayName`, it will require you to find said persons keyname however in the long run its far simpler. Finding a keyname only requires a little experimentation with jirashell, my go to option when i can not figure out what is going on.

`jirashell -s http://"yoururlhere" -u "yourusername" -P` in CMD
See the docs for more info: [DOCS](http://skjira.readthedocs.io/en/latest/jirashell.html)

Quick tip, you can easly view the members of an object using `dir(yourobject)` or `yourobject.__dict__`

**Comment by hdost** [comment]
I would follow @Fr3dBear 's suggestion.
