### ISSUE TITLE
Jira/client.py KeyError raised when fetch pages. 

### ISSUE THREAD

**Issue by qij3** [pycontribs/jira#378]
Hello,

I think my webapp is having issues in Jira/client.py when try fetch pages.

issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
Mar 30 08:58:16  File "/python2.7/site-packages/jira/client.py", line
 402, in _fetch_pages
Mar 30 08:58:16:     raise KeyError(str(e) + " : " + json.dumps(resource))
Mar 30 08:58:16: KeyError: u"u'issues' : {}"

So basically you would like to do check for items_key as well as if items_key in resource.
`
             next_items_page = [item_type(self._options, self._session, raw_issue_json) for raw_issue_json in
`
`                                 (resource[items_key] if items_key else resource)]
`

Instead probably better to have this:
`
resource[items_key] if items_key and items_key in resource else resource
`

**Comment by hdost** [comment]
This sounds like it might be better in the form of the Pull request
