### ISSUE TITLE
Show "ImportError: No module named HTMLParser" when python scripts are packed with cx_Freeze

### ISSUE THREAD

**Issue by sanxiwang** [pycontribs/jira#38]
I have JIRA 0.39 installed and have the latest six and HTMLParser installed. However, I still got the following error message when my script is packed with cx_Freeze. 
* It works fine when JIRA related code is removed.
* It works fined during debugging (source code level).
Appreciate your comments on this.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
    exec code in m.__dict__
  File "FreeMind.py", line 3, in <module>
  File "C:\Python27\lib\site-packages\jira\__init__.py", line 5, in <module>
    from .config import get_jira
  File "C:\Python27\lib\site-packages\jira\config.py", line 17, in <module>
    from jira.client import JIRA
  File "C:\Python27\lib\site-packages\jira\client.py", line 33, in <module>
    from six.moves import html_parser
  File "C:\Python27\lib\site-packages\six.py", line 199, in load_module
    mod = mod._resolve()
  File "C:\Python27\lib\site-packages\six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "C:\Python27\lib\site-packages\six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named HTMLParser

**Comment by ssbarnea** [comment]
What is this cx_freeze? I am not using Windows. Can you provide more info so we can findout the root cause? what python distro? does it also happen with py3, what are the versions of the installed modules? windows 32 or 64. python 32 or 64?...

/sorin

**Comment by sanxiwang** [comment]
cx_freeze (https://pypi.python.org/pypi/cx_Freeze/4.3.4) is a tool to create standalone executables from Python scripts. I am using Python27 on Windows 64 (Python 64 as well). Here are the version information:
jira-python: 0.39
HTMLParser: 0.02
cx_freeze: 4.3.2
six: 1.9.0

I also did google and find some information. Not sure if this is helpful or not. Please let me know if you need more information on this. Thank you very much.
http://stackoverflow.com/questions/26691973/why-am-i-getting-a-python-importerror-no-module-named-html-parser
The six library uses some advanced import magic. The import of html_parser has to be done in a special way. from six.moves import html_parser usually works. If you have third party code that tries to import from six in an other way you can try to import six and/or six.moves at first before importing anything else.

**Comment by ssbarnea** [comment]
As I am not able to replicate you issue, please try one of the recommended workarounds and let me know which one works for you and I will change the way we are doing the import.

Now we have:
```
from six import string_types, integer_types
from six.moves import html_parser
```
Try few alternatives and let me know, as soon I have confirmation I will release a new version.

**Comment by sanxiwang** [comment]
Was JIRA 0.40 released for this? I tried and it generated the same error.
When you are saying "please try one of the recommended workarounds", what do you refer to?

**Comment by sanxiwang** [comment]
Tried to change
from six.moves import html_parser
to
from HTMLParser import HTMLParser

This error disappears but I got new error down from jira package.
ImportError: No module named 'requests.packages.chardet.sys'

**Comment by ssbarnea** [comment]
Hmm, it seems that the cx_freeze is doing some weird things and is breaking many imports. If you could tell me how to replicate this use case, I may be able to perform some changes to make it work. Sadly, at this moment Travis does not support Windows, I am usually working on OS X and running the unit tests on Travis, which makes the Windows platform almost uncovered by any testing.

Is not that I same anything against supporting Windows, but without someone posting patches, it is harder to have a very good experience using the library on Windows.

**Comment by sanxiwang** [comment]
Not just cx_freeze, I tried another Windows packing tool called PyInstaller (https://pypi.python.org/pypi/PyInstaller/2.1), which is also showing the similar errors. If you are not Windows, then it would be hard to find a way to reproduce this case.

**Comment by sargentstudley** [comment]
For what it's worth, I have an issue with is import as well (I develop on windows) - PyCharm is showing an error with the import. I am able to run the file without incident however. It certainly is a windows specific issue but I am unsure what it is yet.

**Comment by RainerHausdorf** [comment]
Worked for me when using PyInstaller after adding <code>from HTMLParser import HTMLParser</code> somewhere in my Code (guess this could also be written into a PyInstaller hook). For my case this solves the "import-magic" from six. After that there were no other errors.

Using:
<code>
Python 2.7.9
jira==0.43
six==1.9.0
requests==2.6.0
requests-oauthlib==0.4.2
requests-toolbelt==0.3.1
tlslite==0.4.8
oauthlib==0.7.2
ordereddict==1.1
urllib3==1.10.2
</code>

**Comment by ssbarnea** [comment]
@RainerHausdorf If make a pull request, I will be more than happy to integrate it.

**Comment by RainerHausdorf** [comment]
From my point of view, there is nothing you have to change about jira.

Adding the line/hook (outside of jira - cant be inside, otherwise you would make the use of the six-module senseless) is a solution to the user who wants to build their app with PyInstaller.

Background (as I see it):
PyInstaller has some problems to recognize the "import-magic" of six and misses to pack HTMLParser into the build. The manual import with the line <code>from HTMLParser import HTMLParser</code> tells PyInstaller (in a more explicit way than six does) that it is needed.

**Comment by ssbarnea** [comment]
Six may also be used for other stuff that are not so magic and if there is a way to change the library to make it work with pyinstaller without having to add extra stuff, I am willing to update it to improve the UX ;)
