### ISSUE TITLE
jira credentials 

### ISSUE THREAD

**Issue by suresh753** [pycontribs/jira#381]
Hi,
i am using python version 2.7.13
Could anyone please tell me how to save and use jira credentials from .netrc file.

**Comment by Fr3dBear** [comment]
My knowledge on .netrc files is almost not existent, however it looks like the format for the files is somthing like `machine host1.austin.century.com login fred password bluebonnet`. You may be able to just open the file in text format and parse it for the username and password.

Once the username and password is captured, creating a JIRA isntance is as easy as `jiraserver = JIRA(server = "servername", basic_auth=(str(username), str(password)))`

**Comment by suresh753** [comment]
@Fr3dBear thanks for your suggestion

i have tried and it's working

```
import netrc
secrets = netrc.netrc()
username,account,password = secrets.authenticators('SYNLPT120')  
authenticated_jira = JIRA(options={'server': account}, basic_auth=(username, password))
```
netrc file syntax 

![github](https://cloud.githubusercontent.com/assets/21236702/25552509/2d7cd21e-2cb9-11e7-994d-da9d2b049c98.PNG)

**Comment by dennismarwood** [comment]
When I read the docs I got the impression that this jira module had some built in functionality to load the values from the netrc file. And browsing through the code I found a couple of references to netrc to kind of muddy the waters. 

https://github.com/pycontribs/jira/blob/develop/docs/examples.rst says:

> The library is able to load the credentials from inside the ~/.netrc file, so put them there instead of keeping them in your source code.

But you just end up importing netrc and pulling the creds manually from there. Or maybe I am not using it correctly?

**Comment by efskap** [comment]
Much easier this way:

~/.netrc:
```
machine yourjiraserver.com
login suresh
password simahm
```

Then the library can load it automatically.

```
from jira import JIRA
jira = JIRA({'server':'https://myjiraserver.com'})
```
and it just works.
