### ISSUE TITLE
DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7

### ISSUE THREAD

**Issue by stebunovd** [pycontribs/jira#397]
It turns out that 'async' parameter which used in [a couple of methods](https://github.com/pycontribs/jira/search?utf8=✓&q=async&type=) prevents this library to be compatible with the future of Python. These warnings can be seen when running tests under Python 3.6 with `-Wd` option.

I guess this is not urgent since Python 3.7 is not released yet, but at the same time it affects public library API, so probably it makes sense to deprecate this parameter in advance and let developers fix their code.

**Comment by urosjarc** [comment]
Soon python 3.7 will be default version on ubuntu. When will be this issue resolved?

**Comment by ssbarnea** [comment]
I am curious about what it would be the best way to approach this. How did others solve the issue?

**Comment by hdost** [comment]
Currently there is an open PR on pylama https://github.com/klen/pylama/pull/120

**Comment by hdost** [comment]
OpenStack solution: https://github.com/openstack/mistral/commit/4d8b30270ab5edf201d76b09322c374b446d3ec9

**Comment by stebunovd** [comment]
Python 3.7 is out! 

Do you need any help with developing a fix for this issue, or maybe with testing?

**Comment by hdost** [comment]
Superceded by #603
