### ISSUE TITLE
Disable notifications while updating issue

### ISSUE THREAD

**Issue by rkadam** [pycontribs/jira#405]
As per documentation, one can suppress notification for given issue.
```
issue.update(notify=False, description='A quiet description change was made')
```
But this doesn't seem to be working. Notifications are still sent out.

**Comment by mdoar** [comment]
It's working for me. I had to set up tests very carefully to convince myself I was not getting email for the right reasons though.

lib/python2.7/site-packages/jira-1.0.10.dist-info

**Comment by rkadam** [comment]
That's strange. I'd tried it with Python 2.7 and Python 3.0 against JIRA 7.1.

**Comment by fender4645** [comment]
@rkadam that parameter wasn't introduced until after 7.1. Not sure when but if you look at the latest REST docs (https://docs.atlassian.com/jira/REST/server/#api/2/issue-editIssue) it's there but not for 7.1.10 (https://docs.atlassian.com/jira/REST/7.1.10/#api/2/issue-editIssue)

**Comment by rkadam** [comment]
@fender4645, you are right. This parameter was introduced starting 7.2.1. Here is earliest API where I can find the mention of this parameter: https://docs.atlassian.com/jira/REST/7.2.1/#api/2/issue-editIssue

Thank you very much for pointing it at API documentations for different JIRA versions. I think I was reading documentation for latest JIRA version and was expecting it to work.

We can close this as a not a bug!
