### ISSUE TITLE
How to get issues associated to release version

### ISSUE THREAD

**Issue by yashwanthbabu** [pycontribs/jira#408]
For example, If I have a release version, say `1.0.1.v1.0.288`. I have 50 issues associated with that release. How can I get those with this package?

**Comment by yashwanthbabu** [comment]
@ssbarnea Can I know why this is closed without any information? Can I also know why this is invalid? Please mention if there is a feature developed for my issue or let me know are you going to develop. I don't see this feature anywhere in the code. I am also ready to make contributions for this issue

**Comment by ssbarnea** [comment]
That's a bug tracker and it should not be used for support. Use of StackOverflow seems like a better place for asking this.

And btw, yes you can by using a JQL query.
