### ISSUE TITLE
adopt pre-commit.com

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jira#411]
It would be nice to adopt use of pre-commit hooks as documented at http://pre-commit.com/hooks.html

**Comment by hdost** [comment]
@ssbarnea Were you thinking to use all of them or just a subset?

**Comment by ssbarnea** [comment]
Merged, from now on we will be able to add extra pre-commit checks on one-by-one change, making easier to review. Feel free to raise PRs, no need to add extra tickets, can link to this one.
