### ISSUE TITLE
__getattr__ Override prevents graceful accessing object properties 

### ISSUE THREAD

**Issue by smaisidoro** [pycontribs/jira#415]
Overriding the python object method:
```__getattr__``` (https://github.com/pycontribs/jira/blob/develop/jira/resources.py#L157)

prevents gracefully accessing object properties like:
```
some_issue = jira.issue('XX-123')
some_attribute = some_issue.getattr('some_attr', 'default')
```
This raises:
```AttributeError: type object 'PropertyHolder' has no attribute 'getattr'```

**Comment by hdost** [comment]
@pycontribs/pycontribs  I don't know if anyone wants to respond to this.
