### ISSUE TITLE
Contribution guide references Bitbucket repository?

### ISSUE THREAD

**Issue by oogali** [pycontribs/jira#416]
The contribution guide says that bugs/PRs should be filed against the Bitbucket repository, then proceeds to list a Github URL?

Is there a Bitbucket project I should be branching off of, or was that merely just a typo and branches should be done in Github?

**Comment by asqui** [comment]
Good catch! That's a typo. The project is on GitHub now.

I've updated that to refer to GitHub now (eb4cb5f).

Sorry for the confusion!
