### ISSUE TITLE
search_issues modifies fields parameter if it is a list

### ISSUE THREAD

**Issue by gilo-agilo** [pycontribs/jira#418]
I encountered a side effect of ```search_issue``` method. When I'm passing list of fields as list (not as comma separated string), then that method is doing "translation" and replaced 'key' with 'issuekey' in my list.
Later on when I'm trying to get field (key) as I requested, I'm getting error since issuekey field does not exist in Issue object. **As workaround:** I'm cloning my list of fields before passing it to search_issue method.

**Recommendation**
Do not alter fields parameter inside search_issue method if list is passed (or raise an exception if fields is not a string).

Version I'm using is ```jira==1.0.10```

**Comment by hdost** [comment]
@gilo-agilo could you provide a code example?

**Comment by chevell** [comment]
Easy enough to reproduce:

```
my_fields = ['key']
issues = jira.search_issues(jql, fields=my_fields)
# `my_fields` has been modified
assert(my_fields == ['key'])
```

The reason for this is pretty simple: `JIRA.search_issues` modifies the `fields` list you pass to it directly, using the field names from `/rest/api/2/field` to correct any fields where the "friendly" name is being used (e.g. "Key" as the name for "issuekey"). Lists are mutable in python, and you're simply passing a reference to it, so when `JIRA.search_issues` makes any modifications to your list, those modifications are being made to the original list.

To fix this, I would suggest modifying `JIRA.search_issues` to make a copy of the `fields` list. There's already some code at the beginning of `JIRA.search_issues` to handle the case where `fields=None`, so it should be simple enough to modify this:

```
        if fields is None:
            fields = []

        if isinstance(fields, string_types):
            fields = fields.split(",")
```

To this:

```
        if fields is None:
            fields = []
        
        if isinstance(fields, list):
            fields = fields.copy()

        if isinstance(fields, string_types):
            fields = fields.split(",")
```

@gilo-agilo I'll raise a PR for this.
