### ISSUE TITLE
search_issues (Get All) is broken.

### ISSUE THREAD

**Issue by TrueMiller** [pycontribs/jira#423]
## Summary
* search_issues (Returns only the batch size, which is 50,  when the caller expects to the total number of issues back.)
* _fetch_pages (fails due to reliance on optional parameter introduced in JIRA Agile 6.7.6)
* _get_json (response does not contain 'isLast')

## Recommendation
The _fetch_pages seems at quick glance to have multiple intentions that might be more suitable separated into different functions. 

The VAR `is_last` is set once to True and therfore always breaks the while condition "for the case of basic JIRA API".

## Solution 
For this issue a fix most suitable of the current code would be to add an additional variable that translates the client parameter maxResults from a falsy value to a "get_all" truthy value. The truthy value could then branch instruction flow as follows.

```if get_all:
    while page_start < total and len(next_items_page) <= page_size:
    ....
else:
    while not is_last and (total is None or page_start < total) and len(next_items_page) == page_size:`
    ....
```

## Explanation
The _fetch_pages relies upon _get_json functionality. 
```resource = self._get_json(request_path, params=page_params, base=base)```
           
The returned dictionary is expected to have 'isLast' key with a boolean value, but does not, therefore defaults to true.
```if isinstance(resource, dict):
                total = resource.get('total')
                # 'isLast' is the optional key added to responses in JIRA Agile 6.7.6. So far not used in basic JIRA API.
                is_last = resource.get('isLast', True)
                start_at_from_response = resource.get('startAt', 0)
                max_results_from_response = resource.get('maxResults', 1)
            else:
                # if is a list
                total = 1
                is_last = True
                start_at_from_response = 0
                max_results_from_response = 1
```
causing the following conditional statement to be False.
```
if not maxResults:
                page_size = max_results_from_response or len(items)
                page_start = (startAt or start_at_from_response or 0) + page_size
                while not is_last and (total is None or page_start < total) and len(next_items_page) == page_size:
```

## Testing
Atlassian JIRA Project Management Software (v7.3.6)

**Comment by juangermano-okta** [comment]
Isn't this a duplicate of #325?

**Comment by TrueMiller** [comment]
@juangermano-okta Missed that issue. Indeed it is.

**Comment by TrueMiller** [comment]
Duplicate #325
