### ISSUE TITLE
Comparison of issues and ordered set for ResultList rather than list

### ISSUE THREAD

**Issue by romanmatushkin** [pycontribs/jira#43]
Hi guys,

Sorry for my english.
- I've played with the package and found that it behaves a little bit strange, for instance:
  
  ``` python
  In [4]: issue = jira.issue('CDAS-782')
  In [5]: issue2 = jira.issue('CDAS-782')
  
  In [6]: issue == issue2  
  Out[6]: False
  
  In [7]: issues = jira.search_issues('key in (CDAS-782, CDAS-783)')
  In [8]: issues 
  Out[8]: [<JIRA Issue: key=u'CDAS-783', id=u'65593'>,
           <JIRA Issue: key=u'CDAS-782', id=u'65523'>]
  
  In [9]: issue in issues
  Out[9]: False
  ```
  
  That probably might be fixed by implementing of `__eq__` method for `Issue` class, or even for         `Resource` class if that makes sense. Something like the following should be enough:
  
  ``` python
  def __eq__(self, other):
      return self.id == other.id
  ```
- The second thing I'd like to raise with you is using of an ordered set as base class for `ResultList` class as boards and issues are going to be unique across a project. If I understand you decided to use a class inherited from `list` as it's necessary to keep order of issues returned by server 'cause it's important if we make JQL request that ends with `ORDER BY any_field [ASC|DESC]`.
  But lists are not supposed to have unique objects so if we need to keep order and keep uniqueness we should use ordered set instead. In addition it would be great to have some set's benefits (I mean algebra of sets).

It was just a superficial glance and I would appreciate if you share your thoughts.

Thanks,
Roman
##

**Comment by ak-ambi** [comment]
I think it would be good to be able to compare two issues, I would also check whether __class__ attribute is the same if going to implement comparison in base Resource class.

However, I don't get an idea of using set inside ResultList. Will set's benefits will be so needed? Those who need that, can create a set from the content of ResultList.

**Comment by ssbarnea** [comment]
Remember that we need to verify that those issues are both from the same JIRA server, checking only the `id` is not really sufficient.
