### ISSUE TITLE
Updating project roles , replaces it

### ISSUE THREAD

**Issue by iahmad-khan** [pycontribs/jira#431]
Hi , 

I was trying to update the project roles , and when I add a new user to Developers role in my project , the existing users in that role were gone , it replaced them with the new one , can we get just an append operation in this case , so that it doesnt replace/remove the existing stuff and add the new users to the role in the project.

thanks

**Comment by hdost** [comment]
@iahmad-khan Could you provide a minimal example and expected behavior?
