### ISSUE TITLE
Link in Contributing Guidelines

### ISSUE THREAD

**Issue by guymatz** [pycontribs/jira#432]
@asqui The link at the bottom is broken . .   maybe should be https://community.atlassian.com/t5/tag/jira-python/tg-p ?

**Comment by asqui** [comment]
Looks like they changed their URL. Fixed. Thanks for flagging!

**Comment by guymatz** [comment]
Of course.  I hate to do this, but now that I have your attention, is there
any chance you could have a look at this:
https://community.atlassian.com/t5/Questions/Best-steps-to-developing-for-python-jira/qaq-p/632850

It would be so greatly appreciated!!!!!

**Comment by asqui** [comment]
Unfortunately I don't think there's anything written up; I've asked the same question here previously but I don't think there's anything more than the Contributing guide to which this issue refers.

@ssbarnea can confirm.

**Comment by guymatz** [comment]
:-(  It would be really helpful . . .  to me  @ssbarnea ?  Please?
