### ISSUE TITLE
get issue from project

### ISSUE THREAD

**Issue by 467754239** [pycontribs/jira#436]
I can get all the items
But I don't know how to get the corresponding issue from a single project
Hope to get your help

**Comment by yamaturkey** [comment]
try this:
issues_in_proj = jira.search_issues(query, maxResults=50)
where query is your own query.

**Comment by 467754239** [comment]
yes, issues_in_proj = jira.search_issues(query, maxResults=50) is ok

I want to get sub task from a signle issue
Hope to get your help

**Comment by 467754239** [comment]
i see unitest example
issues = self.jira.search_issues('key=%s' % self.issue,
                                         fields='summary,comment')
Is that the way it is?

**Comment by 467754239** [comment]
get all subtask from issue?
Hope to get your help

**Comment by yamaturkey** [comment]
to get all the field?
issue = jira.issue(jira_issue)
print(issue.raw)

or a single field:
issue.fields.customfield_10050

**Comment by chugu** [comment]
467754239 
to get subtasks, I used this:
jira.search_issues("parent = " + issue.key,  maxResults=50)
But I get 1 result when same search in jira returns 4.

**Comment by hdost** [comment]
To get all subtasks of an issue use the following:
```
jira_client = JIRA(...)
issue = jira_client.issue('KEY-XXX')
issue.fields.subtasks
```
obviously fill in the (...) with your parameters.
