### ISSUE TITLE
Add support for creating webhooks

### ISSUE THREAD

**Issue by yamaturkey** [pycontribs/jira#437]
Hi there,

I am new to Jira-Python. Wondering if there is a way to sync up two different issues?

I found webhooks:
https://developer.atlassian.com/jiradev/jira-apis/webhooks

wondering if jira-python will have something similar? thanks~!

Best Regards,
Yamaturkey

**Comment by yamaturkey** [comment]
I see  @guymatz is implementing the Webhook feature. is this something we can use in the near future? thanks~!!

**Comment by hdost** [comment]
For reference #441 , but we just need to look over the implementation.

**Comment by hdost** [comment]
#566
