### ISSUE TITLE
How to use this module to set and get Request participants in Jira Service Desk?

### ISSUE THREAD

**Issue by kirillka57** [pycontribs/jira#438]
I would like to set Jira Service Desk Request participants. 

I tried all kinds of variations of below:

```
options = {'server': 'https://....atlassian.net'}
jira = JIRA(options, basic_auth=('username','password'))
i = jira.issue('TST-11')
i.update(fields={'customfield_12800': [jira.user('my_user_name').name]})
# error: expected object
i.update(fields={'customfield_12800': jira.user('my_user_name').name})
# error: data was not an array
i.update(fields={'customfield_12800': ['my_user_name']})
# error: expected object
i.update(fields={'customfield_12800': 'my_user_name'})
# error: data was not an array
```

At least errors are consistent! :) Any suggestions? If it's not yet implemented may I request it to get implemented?

Thanks, Kirill

**Comment by kirillka57** [comment]
Found similar issues here and a resolution:

anaconda-navigator --reset

(Another suggestion to update anaconda-navigator didn't help, even though I got the update). The funny thing is that I have installed anaconda for the first time, and got this error on the first run of Navigator.

Would be nice if it came after the initial installation in the "reset" state... 

Thanks, Kirill

**Comment by mandeepsinghbaldd** [comment]
@kirillka57 Which option worked for you after anaconda-navigator --reset ?
