### ISSUE TITLE
Delete attachment by ID

### ISSUE THREAD

**Issue by yamaturkey** [pycontribs/jira#442]
def delete_attachment(self, id):
        """Delete attachment by id.

        :param id: ID of the attachment to delete
        """
        url = self._get_url('attachment/' + str(id))
        return self._session.delete(url)

How do I find out what is the id for the attacement? thanks~!

**Comment by Levitron** [comment]
`issue = jira.issue(key)
attachments = issue.fields.attachment
for attachment in attachments:
    print(attachment.filename + ': ' + attachment.id)`

is this what you are looking for?

**Comment by yamaturkey** [comment]
Yes! Exactly what i am looking for! thanks!!!
