### ISSUE TITLE
How to add new account to specific Users Directory?

### ISSUE THREAD

**Issue by Devorkin** [pycontribs/jira#444]
Dear,
I've checked the module Python code and also the Jira REST API v2 and couldn't find a way to add an account to a specific Users directory server.
I've a Jira test  env. and created new Users directory server which has ID 10000
I can create users into this directory via the UI.
But didn't found the needed attribute for it on the code.
Found that there's not ref. to directoryId on the code.
Am I missing anything?

Thanks for your assistance!

**Comment by hdost** [comment]
@Devorkin when you say directory server do you mean something like Microsoft's Active Directory or an LDAP server. If so, then maybe take a look at:
https://confluence.atlassian.com/adminjiraserver071/connecting-to-an-ldap-directory-802592350.html
https://confluence.atlassian.com/adminjiraserver071/configuring-jira-application-options-802593101.html#ConfiguringJIRAapplicationoptions-options
Let me know if there is something else, but to my knowledge when you're working with AD you need to add the to the Directory directly, and applications can only utilize the information provided.
