### ISSUE TITLE
How to update Jira project settings?

### ISSUE THREAD

**Issue by kirillka57** [pycontribs/jira#447]
Hi, 

I need to convert an existing Jira Cloud Software (or Jira Cloud Business) project into Jira Cloud Service Desk and then change a bunch of settings, such as Workflows, Fields, Screens, etc etc. Would appreciate some example of how to achieve that if it's possible to do now. If not, would appreciate adding this functionality in the future.

Thanks, Kirill

**Comment by hdost** [comment]
@kirillka57 Can you explain what you mean? It sounds like this may be outside the scope for this project. The library has the ability to interact with many aspects of the JIRA interface, but I believe what you are looking for is advice beyond simple interactions. If you want documentation on how this works then http://jira.readthedocs.io/en/latest/index.html  should prove useful.

**Comment by kirillka57** [comment]
Hi,

I was just wondering if your python module would (ever) allow one to edit
project settings?

I worked around this limitation by using ret API calls directly, using
Python's requests module... But was winding if you are going to support
those natively...

Thanks, Kirill

**Comment by hdost** [comment]
Contributions are always welcome, as an example here's the create_project function https://github.com/pycontribs/jira/blob/9d1697dd977833b307a271d6be7d350566b37393/jira/client.py#L2738

**Comment by kirillka57** [comment]
Thanks, understood.
