### ISSUE TITLE
Allow cookies to be passed to JIRA session

### ISSUE THREAD

**Issue by ericfrederich** [pycontribs/jira#449]
Other things like proxies and validate are already passed... should allow cookies as well.

This is required for me in our single-sign-on environment

**Comment by ericfrederich** [comment]
There are a bunch of pull requests regarding this.  Please pick one and merge it.

* #460 
* #450 
* #434 
* #425 
* #413 
* #407 
* #393 
* #392 
* #380

**Comment by hdost** [comment]
From what I am seeing #392 and the associated PR #393 is the best implementation

**Comment by hdost** [comment]
@ssbarnea I think we can close this one and after reviewing the mentioned pull requests I think the most relevant is as mentioned above #393

**Comment by hdost** [comment]
Hey @ericfrederich let me know if https://github.com/pycontribs/jira/pull/484 which was recently merged, so I am going to close this.
