### ISSUE TITLE
WARNING:root:hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net' while doing GET

### ISSUE THREAD

**Issue by vaisov** [pycontribs/jira#454]
Recently started getting this error:

`WARNING:root:hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net' while doing GET https://companyid.jira.com/rest/api/2/serverInfo [{u'headers': CaseInsensitiveDict({'Accept-Encoding': 'gzip, deflate, compress', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.2.1 CPython/2.7.6 Linux/4.4.0-93-generic', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}), 'params': None}]
WARNING:root:Got ConnectionError [hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net'] errno:None on GET https://companyid.jira.com/rest/api/2/serverInfo
{}\{}
WARNING:root:Got recoverable error from GET https://companyid.jira.com/rest/api/2/serverInfo, will retry [1/3] in 17.9650767952s. Err: hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net'
`

> I have updated the real hostname to cover the our hostname.

**Comment by hdost** [comment]
`jira.com` is not the correct url. All JIRA cloud instances are hosted at `atlassian.net`

**Comment by vaisov** [comment]
It doesn't work with `atlassian.net`

**Comment by hdost** [comment]
In order to better help:
Can you give me some of the following
* A description of the problem/suggestion.
* How to recreate the bug.

It sounds like you might be doing some host file stuff. What is a template of the host you are directing at. For example the one used in the CI Tests is `https://pycontribs.atlassian.net` the url should follow that format `https://<COMPANY>.atlassian.net` If it does not then you will run into issues.

**Comment by vaisov** [comment]
The thing is that url provided by Atlassian for our company is `<companyname>.jira.com`. Sorry, I forgot to close this issue, as it was solved by updating openssl libs via pip. So it's more of an issue with lib than with your integration.

**Comment by hdost** [comment]
Gotcha, glad to hear it was solved 😄
