### ISSUE TITLE
Verify JIRA server SSL not passed

### ISSUE THREAD

**Issue by jasimmonsv** [pycontribs/jira#455]
https://github.com/pycontribs/jira/blob/0c386cbf7958fd49a81df128527748fe35a6383d/jira/client.py#L223

When trying to connect to a jira server using a self-signed cert, I am unable to pass in the verify keyword argument to avoid cert errors. All the mechanism is in place, but the __init__ function does not allow

When trying to connect to a jira server using a self-signed cert, I am unable to pass in the verify keyword argument.

`JIRA_C = jira.JIRA(server='https://jira.example.com', verify=False, basic_auth=('jirauser', 'changme'))`

**Comment by jasimmonsv** [comment]
I have previously submitted a pull request trying to fix this previously, but has not been accepted:
https://github.com/pycontribs/jira/pull/391

**Comment by asqui** [comment]
In response to your pull request, I was going to say that we should probably "fix" this issue by improving the documentation to make this feature clearer, however looking at the docstring I think this is already pretty clear. Are you happy that this was just a misunderstanding on your part and that there is nothing we can do to improve the situation?

https://github.com/pycontribs/jira/blob/0c386cbf7958fd49a81df128527748fe35a6383d/jira/client.py#L223-L249

**Comment by hdost** [comment]
@jasimmonsv Would the documentation fix mentioned above be sufficient?

**Comment by hdost** [comment]
Closing.

**Comment by jasimmonsv** [comment]
No the documentation does not fix because the verify function still does not exist within the init function and there is no other way defined to bypass the SSL cert checking. I do not know what @asqui was looking at when he suggested the documentation fix, I can only assume that he was looking at the validate variable, which deals with authentication to the server instead of bypassing the SSL cert check.

@hdost this issue needs to be reopened please.

**Comment by ssbarnea** [comment]
I know that requests library decisions of not using or respecting python SSL config are a permanent source of PITA for its users. Recently I come to the conclusion that there is a small hack that can be used to improve SSL experience and it looks like: https://review.openstack.org/#/c/559141/1/jenkins/__init__.py

Let me know what you think about this, I could easily do the some for jira library.
