### ISSUE TITLE
KeyError: u'project'

### ISSUE THREAD

**Issue by exbane** [pycontribs/jira#458]
Hello - i'm attempting to create a script to incorporate in our Cloud based app to create an issue within Jira.

When i run the following code I recieve the below error. 

`new_issue = jira.create_issue(project='OPS', summary="Savage-Test", description="savage-test", issuetype={"name": "Request"}, components=[{"Name": "SysAdmin-VMware"}],fields={'customfield_11107': [{'value': 'Not Applicable'}]})`

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/lib/python2.7/site-packages/jira/jirashell.pyc in <module>()
----> 1 new_issue = jira.create_issue(project='OPS', summary="Savage-Test", description="savage-test", issuetype={"name": "Request"}, components=[{"Name": "SysAdmin-VMware"}],fields={'customfield_11107': [{'value': 'Not Applicable'}]})

/usr/lib/python2.7/site-packages/jira/client.pyc in create_issue(self, fields, prefetch, **fieldargs)
    885         data = _field_worker(fields, **fieldargs)
    886
--> 887         p = data['fields']['project']
    888
    889         if isinstance(p, string_types) or isinstance(p, integer_types):

KeyError: u'project'
```

The customfield_11107 is a required field to create issues within the SysAdmin-VMware component. 

Thoughts?

**Comment by yamaturkey** [comment]
try this:

new_issue = jira.create_issue(fields=root_dict)
root_dict = {
    'project':'OPS',
    'summary':"Savage-Test",
    'description':"savage-test",
    'issuetype':{"name": "Request"},
    'components':[{"Name": "SysAdmin-VMware"}],
    'customfield_11107': [{'value': 'Not Applicable'}]
}

**Comment by exbane** [comment]
Thank you! I'll give it a shot!

**Comment by hdost** [comment]
@exbane Can this be closed?

**Comment by exbane** [comment]
Yep it can be . Thank you!
