### ISSUE TITLE
pickle dumps and loads doesen't work correctly

### ISSUE THREAD

**Issue by lh84** [pycontribs/jira#46]
I don't know exactly what it is, but pickle a Sprint object and load it with pickle doesen't work.
Don't have enough time at the moment to dig deeper into it.

Here is an example code for reproducing:

```
class Board(object):
    """
    my representation of jira board
    """
    def __init__(self, board_id, state='FUTURE'):
        self.board_id = board_id
        self.connection = JIRA(
                options={'server': ... },
                basic_auth=(username, password),
            )
        self.sprints = self.__get_sprints(board_id, state)

    def __get_sprints(self, board_id, state):
        """
        Returns all future sprints for the given board...
        """
        sprints = []
        try:
            for sprint in self.connection.sprints(id=board_id):
                if sprint.state in [state]:
                    sprints.append(sprint)
        except JIRAError, e:
            pass
        return sprints

board = Board(1234)

import cPickle as pickle

pickle.loads(pickle.dumps(board))

```
RESULT:

Traceback:
File ".../lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File ".../planning/sprints/views.py" in planning
  308.                 pickle2.loads(pickle2.dumps(board))
File ".../lib/python2.7/site-packages/jira/resources.py" in __setstate__
  116.         self._parse_raw(raw_pickled)
File ".../lib/python2.7/site-packages/jira/resources.py" in _parse_raw
  242.         dict2resource(raw, self, self._options, self._session)
File ".../lib/python2.7/site-packages/jira/resources.py" in __getattr__
  104.                 raise AttributeError("%r object has no attribute %r" % (self.__class__, item))

Exception Type: AttributeError at /planning/sprint/15
Exception Value: <class 'jira.resources.Sprint'> object has no attribute '_options'

**Comment by ssbarnea** [comment]
v0.43 fixes this.
