### ISSUE TITLE
Backup Endpoint Changed

### ISSUE THREAD

**Issue by guitarhero23** [pycontribs/jira#461]
When trying to run jira.backup() the endpoint returns a 404. Research brought me to https://jira.atlassian.com/browse/JRACLOUD-67169 where they notate that the endpoint changed to /rest/backup/1/export/runbackup. When I updated client.py it seemed to work.

New code for def backup() would be

    def backup(self, filename='backup.zip', attachments=False):
        """Will call jira export to backup as zipped xml. Returning with success does not mean that the backup process finished."""
        if self.deploymentType == 'Cloud':
            url = self._options['server'] + '/rest/backup/1/export/runbackup'
            payload = json.dumps({"cbAttachments": attachments})
            self._options['headers']['X-Requested-With'] = 'XMLHttpRequest'
        else:
            url = self._options['server'] + '/secure/admin/XmlBackup.jspa'
            payload = {'filename': filename}
        try:
            r = self._session.post(url, headers=self._options['headers'], data=payload)
            if r.status_code == 200:
                return True
            else:
                logging.warning(
                    'Got %s response from calling backup.' % r.status_code)
                return r.status_code
        except Exception as e:
            logging.error("I see %s", e)

**Comment by guitarhero23** [comment]
I submitted a pull request with the update

**Comment by hdost** [comment]
The PR has been merged into develop #462
