### ISSUE TITLE
deactivate_user doesn't work on JIRA SERVER.

### ISSUE THREAD

**Issue by fanooel** [pycontribs/jira#470]
deactive_user got responce with "Administrator Access" page and do nothing.

**Comment by solimike** [comment]
I'm seeing this issue, too.  Calling `jira.deactivate_user("foo@example.com")` results in [substituting **example.com** for my real domain]:

```
Error Deactivating foo@example.com: JiraError HTTP 401 url: https://example.atlassian.net/admin/rest/um/1/user/deactivate?username=foo@example.com
	text: User failed to authenticate
	
	response headers = {'Server': 'Atlassian Proxy/0.1.162', 'ATL-vTM-Backend-Time': '440', 'Content-Type': 'text/plain;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Wed, 10 Jan 2018 21:01:24 GMT', 'X-Application-Context': 'application:prod-west:8080', 'IdPlat-Outstanding-Token': 'none', 'ATL-vTM-Time': '440', 'Connection': 'keep-alive', 'Content-Length': '27', 'ATL-vTM-Queue-Time': '0'}
	response text = User failed to authenticate
Failed to deactivate (None)
```

I suspect that it is related to various Jira API (_e.g._ https://jira.atlassian.com/browse/ID-6351) issues triggered at the time that Atlassian Accounts was rolled out (mid-2017).  Has anyone managed to crack this one?

**Comment by hdost** [comment]
@solimike Could you provide a more complete information, a Code Block  + stacktrace or something similar.

**Comment by fanooel** [comment]
When I've added in function "deactivate_user" before try section:
```python
try:
   r = self._gain_sudo_session(userInfo, url) #my code
   r = self._session.post(url, headers=self._options['headers'], data=userInfo)
```
web_sudo sessions- it works fine...

**Comment by ssbarnea** [comment]
@fanooel this starts to make some sense and I think you are getting closer to raise a PR that would fix this. `deactive_user` is one function that would require sudo, so you need to patch it a little bit with some things that should look:

if session.is_sudo: session.gain_sudo()

Please not that we need to be sure that gaining sudo is remembered into the session.

**Comment by fanooel** [comment]
I've changed my post...

**Comment by ssbarnea** [comment]
I expect for the library to be smart enough to auto-attempt to sudo when needed. If this happens by default, you can close the bug. If not, we should aim to fix it / improve the experience.

**Comment by fanooel** [comment]
OK- I should change session class and create pull request- right?

**Comment by fanooel** [comment]
Similar problem we have in 'backup' method. My solution for it look like:
```pythonry:
            r = self._gain_sudo_session('', url) #my code
            my_headers = self._options['headers']  #my code
            my_headers['Content-Type'] = 'application/x-www-form-urlencoded'  #my code
            r = self._session.post(url, headers=my_headers, data=payload)  #my changes in neaders
            if r.status_code == 200:
                return bool(r.text.find('Data exported to') != -1)  #my code
            else:
                logging.warning(
                    'Got %s response from calling backup.' % r.status_code)
                return r.status_code
        except Exception as e:
            logging.error("I see %s", e)
```

**Comment by hdost** [comment]
@ssbarnea :thinking:

**Comment by hdost** [comment]
@fanooel If you have a change, feel free to make a PR.

**Comment by fanooel** [comment]
I'm in!

**Comment by anki90** [comment]
@fanooel I tried your solution mentioned to gain the sudo access. I still get a 401 unauthorized. Any ideas?

**Comment by hdost** [comment]
Since it looks like this is a duplicate and the same info is in #348 closing this one
