### ISSUE TITLE
Unable to create groups

### ISSUE THREAD

**Issue by hdost** [pycontribs/jira#476]
@ssbarnea  There seems to be the inability to create groups in the JIRA instance for ci-admin.

I don't know necessarily the reason for that. If it makes sense to keep the settings that way then we may want to look into at least disabling the delete_groups permission related tests for when running in Travis.

**Comment by dbaxa** [comment]
The APIs around creating, modifying and deleting users & groups in Jira Cloud have changed. iirc site-admin permission is required to make the changes now.
