### ISSUE TITLE
Do you have changelog from each release?

### ISSUE THREAD

**Issue by BuildMonkey** [pycontribs/jira#48]
I'm looking for the changelog for each of the releases but cannot find it. Do you have a place where this is located?

Also, how can we tell when there is a major API change between versions. It looks like just the minor number is being bumped but there are significant differences between 0.16 and 0.38 causing problems with dependency code. It would be nice if the API changes were denoted in the verson string.

Thanks.

**Comment by ssbarnea** [comment]
Unless someone will will improve the release.sh script to generate a changelog file based on commit messages I doubt this will get fixed.
