### ISSUE TITLE
Createmeta for creating a New Issue

### ISSUE THREAD

**Issue by NinjaEngineer** [pycontribs/jira#481]
I am trying to create issues in JIRA on a form that has custom fields. I know the name of the field is custom_field_12345. I looked at the documentation and it says, "Your JIRA may require additional fields for creating issues; see the jira.createmeta method for getting access to that information." 

I used the syntax of adding each of these custom fields as a dictionary entry, and of adding each as an argument to the jira.create_issue(...). However neither of these worked. I then tried debugging, but couldn't figure it out.  

Could this be documented? What am I missing?

**Comment by hdost** [comment]
@NinjaEngineer can you provide a code sample to go along with this issue. It will make it easier to see how best to approach this issue.

Thank you!

**Comment by hdost** [comment]
Closing since there has been no additional information.
