### ISSUE TITLE
Unable to fetch comments

### ISSUE THREAD

**Issue by gopar** [pycontribs/jira#486]
Python Version: 3.6.3
Jira (Library): 1.0.10

When fetching an issues that does have comments and doing `issue.fields.comment` I get an attribute error.
Also doing `issue.raw['fields']['comment']` fails as well.

Any ideas?

**Comment by gopar** [comment]
Queried the API directly and was able to retrieve comments.

**Comment by qneill** [comment]
I had some mind-bending moments trying to fetch comments too.

Reading https://jira.readthedocs.io/en/master/examples.html#comments helped

I had problems converting unicode comments to strings (but that's an off-topic python/unicode issue)

**Comment by hdost** [comment]
@gopar Do @qneill 's comments solve your issue?

**Comment by gopar** [comment]
Sorry, but no. I was using the docs to see how to fetch comments. That's how I realized the comments weren't showing up.

**Comment by hdost** [comment]
@gopar Can you give an example of the error?

**Comment by hdost** [comment]
@gopar 
The documentation http://jira.readthedocs.io/en/master/examples.html#comments mentions how to list the comments. Specifically the below block shows exactly how.
```
jira_client = JIRA(...)
issue = jira_client.issue('KEY-XXX')
issue_a.fields.comment.comments
```
