### ISSUE TITLE
Move subtasks from one parent to another

### ISSUE THREAD

**Issue by hsmj1412** [pycontribs/jira#487]
Dear all,
I try to move some subtasks from one parent to another, but it can not take effect.
Please help me, thanks.

**Comment by hdost** [comment]
@hsmj1412 Can you post an example of what you are trying?

**Comment by hsmj1412** [comment]
@hdost Thanks for replying
The jira I used is intranet, so I could not post the url. And I try to describe it clearly.
There are 3 tasks A, B and C. A is the parent of C, C is the sub-task of A. Now I try to change the relationship. A and C are independent, and to add C under B as a sub-task.
The code:
parent_issue.fields.subtasks.append(issue)
parent_issue.update(fields=parent_issue.fields)
But after update operation, the issue will be cleared

**Comment by hdost** [comment]
So in this scenario I am assuming that `parent_issue` is B and `issue` is C. And in short it sounds like you want to move C from subtask of A to subtask of B. Does that sound correct?

**Comment by hdost** [comment]
Waiting to hear back: https://community.atlassian.com/t5/Answers-Developer-Questions/Can-I-change-sub-task-parent-using-REST/qaq-p/466646#U726986

**Comment by hsmj1412** [comment]
@hdost Thank you! Same as you said, and any way that I can do it is OK to me

**Comment by hdost** [comment]
Closing as this seems to be something that's an issue in the API.
