### ISSUE TITLE
Error when trying to use the API

### ISSUE THREAD

**Issue by RachitKansal** [pycontribs/jira#489]
`requests.exceptions.SSLError: HTTPSConnectionPool(host='jira.xxxxxx.com', port=xxxx): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))`

The error occurs on this line in my code:
jira = JIRA(server=JIRA_URL, basic_auth=(JIRA_USER_NAME, JIRA_PASSWORD))

Please help

**Comment by juangermano-okta** [comment]
Hi @RachitKansal ,

this doesn't look at first glance like an issue in the lib, but a connection issue. Please note that a project's issue tracker is not a place to look for support, but rather to report bugs/issues with the library.

Having said that, let's see if I can help you with this. As you can see from the error message, there's an SSL level issue. I'd recommend that you try to troubleshoot it without using the Jira library first: try connecting to your Jira instance using your browser. If that works, move back into Python. In my experience, EOF can happen when basic agreement about the protocol can't be reached (for example, your Python version is compiled against an openssl version so old that supports only SSLv3 and the server may be configured to support TLSv1.2; or they do, client and server, support the same protocol version, but there's no overlap between ciphers; etc.). Try a request using Python's requests package (it's what Python's JIRA uses). If that fails, search the web for fixes for that (you'll see options like installing requests[security], pyopenssl and stuff like that).

If everything works from a Python console/script using requests, but fails with the Jira lib, then do open a ticket.

**Comment by Achimh3011** [comment]
Any news on the issue? Otherwise I think closing it would be appropriate....
