### ISSUE TITLE
Greenhopper - Sprints with issue details

### ISSUE THREAD

**Issue by brandonfza** [pycontribs/jira#49]
Good day

Is it possible to get all the issues within a Sprint, including all the metadata (reporter,status, assignee etc)?
At the moment all you can get is the complete or incomplete issues in a sprint?
Is there way to do this?

**Comment by ak-ambi** [comment]
I created PR #144, that adds new public JIRA Agile API. I did not implement any new functions, but this one would be easy with GET request '/rest/agile/1.0/sprint/{sprintId}/issue'. So yes, it is doable.

As a workaround, you can use search_issue function with JQL like "Sprint = <sprint_id>"
