### ISSUE TITLE
jira 6.4 default priorities change

### ISSUE THREAD

**Issue by chugu** [pycontribs/jira#495]
Since jira 6.4 default priority for new installs is medium, not major.
https://community.atlassian.com/t5/Jira-questions/JIRA-default-Priorities/qaq-p/207434
This causes some tests to fail.
Fix could check current jira version or allow bother values as acceptable.

**Comment by ssbarnea** [comment]
I am closing this because i do not see any tests failing on CI. Still, if you like to change the
test defaults you are welcome to create a PR. If the PR passes is likely that we will accept the change.
