### ISSUE TITLE
create_issue_link returns Bad request

### ISSUE THREAD

**Issue by vkolova** [pycontribs/jira#503]
I tried using

```
issue = 'TEST-1000'
issue2 = 'TEST-2000'

jira.create_issue_link(
    type="Duplicate",
    inwardIssue=issue,
    outwardIssue=issue2,
    comment={
        "body": "Linking '%s' --&gt; '%s'" % (issue, issue2),
    }
)
```
as well as

```
issue = jira.issue('Issue ID1')
issue2 = jira.issue('Issue ID2')

jira.create_issue_link('Duplicate', issue, issue2, None)

```

and

```
issue = jira.issue('Issue ID1')
issue2 = jira.issue('Issue ID2')

jira.create_issue_link('Duplicate', issue.key, issue2.key, None)
```

but I always get 

> Client Error: Bad Request for url: [...]/rest/api/2/issue/

Am I doing it wrong?

**Comment by hdost** [comment]
I was unable to replicate the behavior, what is your "jira" a reference to?

**Comment by stappersg** [comment]
Please close this _you must debug my program_ issue

**Comment by hdost** [comment]
@stappersg Given that right now this project does not currently have another good way to answer questions. At least one that we are all using enough. I am fine with questions coming through here.

That being said @vkolova did you you solve your problem.

**Comment by vkolova** [comment]
@hdost Yes, I did.

**Comment by hdost** [comment]
@vkolova for documentation purposes could you post a solution?

**Comment by vkolova** [comment]
@hdost , yeah, no problem.
I did it using:

```
issue1 = jira.issue('Issue ID1')
issue2 = jira.issue('Issue ID2')
jira.create_issue_link(type='Duplicate', inwardIssue=issue1.key, outwardIssue=issue2.key)
```
