### ISSUE TITLE
1.10.11 may be an erroneous tag

### ISSUE THREAD

**Issue by Stealthii** [pycontribs/jira#505]
The git tag `1.0.11` points to commit 41183a0, which is not part of the main tree (the same commit looks like it was rebased to `master` as f67cac0). As 1.0.11 is the latest version released on pip I suspect this might be in error, and should be removed.

**Comment by hdost** [comment]
@ssbarnea in addition i did notice there is a 1.10.11, of which I am assuming may be a fluke

**Comment by ssbarnea** [comment]
1.0.11 was also removed from PYPI, do not use this tag, ever.

**Comment by carlwgeorge** [comment]
Can the tag be deleted in GitHub?  It's confusing the latest tag feature in the [refined github](https://github.com/sindresorhus/refined-github) browser extension.
