### ISSUE TITLE
How update customfields ?

### ISSUE THREAD

**Issue by ssu1980** [pycontribs/jira#507]
I writed code, but customfields didn't update
# -*- coding: UTF-8 -*-
from com.atlassian.jira.component import ComponentAccessor
from com.atlassian.jira.issue import CustomFieldManager
from com.atlassian.jira.issue.fields import CustomField
from com.atlassian.jira.issue import ModifiedValue
from com.atlassian.jira.issue.util import DefaultIssueChangeHolder
from com.atlassian.jira.issue.fields.layout.field import FieldLayoutImpl

customFieldManager = ComponentAccessor.getCustomFieldManager();
changeHolder =  DefaultIssueChangeHolder();

ApprovalCount = "customfield_14000";
FieldLayoutItem = FieldLayoutImpl.getFieldLayoutItem("14000");
CustomFieldApprovalCount = customFieldManager.getCustomFieldObject(ApprovalCount);
if issue.getCustomFieldValue(CustomFieldApprovalCount):
	ApprovalCountVal = issue.getCustomFieldValue(CustomFieldApprovalCount)
else:
	ApprovalCountVal = 0	 	
log.warn (ApprovalCountVal);
newApprovalCountVal = ApprovalCountVal + 1;
log.warn (newApprovalCountVal);
issue.setCustomFieldValue(CustomFieldApprovalCount, newApprovalCountVal);

I tried use 
CustomFieldApprovalCount.updateValue(null, issue, ModifiedValue(ApprovalCountVal,newApprovalCountVal), changeHolder);
But error 
CustomFieldApprovalCount.updateValue(null, issue, ModifiedValue(ApprovalCountVal,newApprovalCountVal), changeHolder); NameError: name 'null' is not defined

Could you help me

**Comment by austinbutler** [comment]
It looks like you aren't using this package, you're using something else.
