### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by anamariaradut** [pycontribs/jira#509]
Hi guys, 

I have an authorization problem, maybe you can help me :) 

In our company we have a authorization server that doesn't let me get to the JIRA server without defining its cookies. 

Is there a possibility to set and send the cookies to the server within a specified dict, just like requests.get(url, cookies=cookies)?

Thanks for your support :)

**Comment by Stealthii** [comment]
#484 implements a feature to allow cookie based authentication. You still pass a tuple of (username, password) to the `auth` constructor argument, but the retrieved session cookie will be used in future requests.

This has been merged to `develop` 2 days ago - feel free to try out the feature and see if this fixes your issue.

**Comment by anamariaradut** [comment]
Just Making sure I'm doing this right

jac = JIRA(server,basic_auth=(username,passw),validate=True) ?

Im getting a "You don't have permission" from the server, and its not because of my account because it works just fine when using requests and sending the cookies withit 

Thanks for your help!

**Comment by Stealthii** [comment]
Cool. If that's the case, you're probably suffering from #460. Track that and see if it fixes your issue!

**Comment by anamariaradut** [comment]
Thank you!
