### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by juandag** [pycontribs/jira#51]
OAuth authentication is deprecated by atlassian. 
Is there any way to use JWT with jira-python?

**Comment by ssbarnea** [comment]
Yes, there is a way, try to implement it and I will more than willing to help integrating it. I doubt I will have time for to do it myself in the foreseeable future.

**Comment by ssbarnea** [comment]
This was solved in trunk and will be present in the new release. Still there are no test written for it so I will not be able to guarantee.
