### ISSUE TITLE
Suggestion to move to semantic style versioning

### ISSUE THREAD

**Issue by Stealthii** [pycontribs/jira#511]
The jira package is used extensively by other projects, and has become the defacto python module for JIRA REST communications. Unfortunately, with the release bump versioning currently in place, there are often new features, breaking changes, and new bugs introduced in 'patch' version bumps. (v1.0.11 is a recent example, which contains many new features, and breaking bugs such as #501)

This makes it hard to track regressions when using this module for critical work, and is often pinned to an exact release version for this reason. With travisci and decent code coverage in place right now, I suggest that the package move to a semantic version style so that expectations of major, minor, and patch version bumps are met.

I do not expect that older versions will necessarily receive bug-fixes, but the ability to update to bugfix/patch releases without receiving new features or incompatible changes would be desirable.

**Comment by ssbarnea** [comment]
1.0.11 was a very unfortunate release and I ended up removing it from PYPI.

I will close this bug because we are already expecting to use semantic versioning. Fixing the broken CI tests would also address your concerns.
