### ISSUE TITLE
missing v0.41 tag

### ISSUE THREAD

**Issue by wiggin15** [pycontribs/jira#52]
Hi. This repository contains tags for all the released versions of the package, but not for v0.40 and v0.41. Can you please add tags for the correct revisions? I don't know which commit matches what version. Thanks.

**Comment by wiggin15** [comment]
0.35 through 0.39 are also missing

**Comment by ssbarnea** [comment]
That's because the release script from the root was to properly updated for git, nothing else. I will try to fix it for further releases.

**Comment by ssbarnea** [comment]
Fixed, but only for current and future releases, I don't have time now to look for the missing ones. If someone needs them you are welcome to make a pull request ;)

**Comment by wiggin15** [comment]
I can't reopen this, but it seems that as of >0.43 it is back to the way it was :(
