### ISSUE TITLE
Cookie-based and Basic auth with password to be deprecated - start using basic authentication with an API token, OAuth, or Atlassian Connect

### ISSUE THREAD

**Issue by mansilladev** [pycontribs/jira#528]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests && cookie-based authentication will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by ssbarnea** [comment]
Are these the same as https://github.com/pycontribs/jira/blob/427309b9e7b9e13149e1d39d962940364da03129/jira/client.py#L274 or not?

If not, the answer is that we will support them when someone will raise a PR that works with them. ;)

**Comment by Tagman** [comment]
This is a different kind of token. It seems like these are only available in the cloud solution. Our local JIRA server (7.9.xx) doesn't have a site to generate a special API token.

This API token should replace the password in a request. So maybe no further changes to work with them.

**Comment by Tagman** [comment]
This is a different kind of token. It seems like these are only available in the cloud solution. Our local JIRA server (7.9.xx) doesn't have a site to generate a special API token.

This API token should replace the password in a request. So maybe no further changes are needed to work with them.

**Comment by hdost** [comment]
Based on: https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-basic-authentication/

Like @Tagman said, Anyone using these personal tokens should just used the basic authentication method and nothing should be different.

This is a non-issue.

**Comment by anyayunli** [comment]
API token is still favorable to basic_auth in most cases.
