### ISSUE TITLE
Request sufficient access 

### ISSUE THREAD

**Issue by hdost** [pycontribs/jira#529]
https://github.com/pycontribs/jira/pull/523 disabled tests which should ideally be testing, ideally we need to update user permissions.

Edit: fixed legally => ideally

**Comment by dbaxa** [comment]
@hdost yes we the ci admin user to have sufficient permissions to perform user administration so that the tests can run.

**Comment by ssbarnea** [comment]
I think this was sorted long time ago bug if one of you finds a way to disable the annoying notifications I from Atlassian about approving each new testXXX user, it would be so great.
