### ISSUE TITLE
Reading roles requires project admin edit instead of browse

### ISSUE THREAD

**Issue by ReussDr** [pycontribs/jira#535]
Per the documentation it appears that you need project admin to edit the roles of a project, not read them.  But this code snippet fails:

```python
from jira import JIRA

jira_client = JIRA('https://site.atlassian.net', basic_auth=('username', 'password'), max_retries=0)
jira_projects = jira_client.projects()
data_project = jira_client.project('DATA')

print(jira_client.project_roles(data_project.key))
print(jira_client.project_roles(data_project.id))
```

with error `jira.exceptions.JIRAError: JiraError HTTP 401 url: https://arxantech.atlassian.net/rest/api/2/project/DATA/role
	text: You cannot edit the configuration of this project.`

if you do not have Administer Project permission.

**Comment by AnkeshThakur** [comment]
It has been a while. Is there any resolution to this? I'm facing the same issue. I'm not admin. Any workaround?
