### ISSUE TITLE
Client certificate not being passed

### ISSUE THREAD

**Issue by el-pablo** [pycontribs/jira#558]
My company is using mutual certificate authentication for our Jira instance. There's an option in the API to specify a client_cert parameter, but when I use it is ignored.

This is how I'm doing it:

```
from jira import JIRA
jira = JIRA({"server":'https://jirahostname.co.uk', "client_cert":'/path/to/mycert.pem'})

```
Which gives me an SSL handshake error.

I've tried adding this at line 453 of client.py:

`self._session.cert = self._options['client_cert']
`
and it fixes the issue, but I'm a complete novice with Python and wondered whether this is just a hack and that there is something that I'm doing wrong.

If I've genuinely found a bug I'm happy to raise a pull request, but given my complete amateur status I thought I'd ask here first!

Thanks

**Comment by hdost** [comment]
Hey @el-pablo I believe you may just be having an issue with syntax.
Try:
```
from jira import JIRA
jira = JIRA('https://jirahostname.co.uk', options={'client_cert':'/path/to/mycert.pem'})

```

**Comment by el-pablo** [comment]
Thanks for the response @hdost - I just tried that and it doesn't seem to have helped....

**Comment by hdost** [comment]
What does it seem to be giving you?

**Comment by el-pablo** [comment]
I get the following, which I believe is because it is not sending a certificate.

```
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='jirahostname.co.uk', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:833)'),))] errno:None on GET https://jirahostname.co.uk/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
```

**Comment by el-pablo** [comment]
I went down that little rabbit hole, but in the end adding the line:

`self._session.cert = self._options['client_cert']`

in the client.py __init__ function seems to fix it just fine...

**Comment by el-pablo** [comment]
I can send a pull request if it helps?

**Comment by hdost** [comment]
PRs are always welcome :)

________________________________________

*Harold Dost* | @hdost

**Comment by j5awry** [comment]
would this also fix:

https://github.com/pycontribs/jira/issues/311

**Comment by fdcds** [comment]
Duplicate of #637 and #311?
