### ISSUE TITLE
Get the epic assigned to issues using search_issues

### ISSUE THREAD

**Issue by federicoorlandini** [pycontribs/jira#563]
Hi,

I'm using your library to be able to compute statistics on the next sprint.
I need to compute some data grouping the issues by Epic but I cannot find any property Epic (or something similar) in the items returned by the search_issues method.
Is there any other way to get the epic for the issues? I would avoid to execute a Jira API call for each issue.
Thanks for your help.
Kind regards,
Federico

**Comment by hdost** [comment]
Hey @federicoorlandini Epic is actually a custom field, so if you're looking for it you can run something like this assuming `authed_jira` is an instance of the `JIRA()` class. 
```
# To find where Epic Link lives
fields = auth_jira.fields()
for f in fields:
  if "Epic" in f['name']:
    print(f)
```
This should print out Epic Link as one of 4. This field is most likely returned as part of the standard search. Therefore assuming `issues` is the result of `search_issues()` then you can just use `issues[1].fields.customfield_XXXXX`. Replacing the XXXXX with whatever number you saw from the previous step.

If it does not return then just use the fields argument to return that as one of the fields. Though you then need to specify all fields that you want as a result of the request.

**Comment by federicoorlandini** [comment]
Hi @hdost,
thank you very much, it works!
