### ISSUE TITLE
proposal: dropping develop branch and use only master

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jira#565]
I think that in the last years the use of two branches, master and develop proved to be more of a confusion factor and caused more maintenance work.

I would like to propose dropping use of develop branch and using directly master.

Please use github up/down voting buttons on this as I don't want to make a decision without getting enough feedback from a signifiant number of contributors (probably 5 at least).

**Comment by hdost** [comment]
I'm good with it, we should just make one last merge, and then drop it.

**Comment by hdost** [comment]
This is done.

**Comment by asqui** [comment]
Develop branch still exists. Should we delete this to avoid future confusion?

**Comment by hdost** [comment]
There's one breaking change that needs to be merged from it at this point
and it can be deleted after that. Otherwise if someone wants to cherry pick
the one commit from #577 and put it on it's own PR then we can delete
develop.

________________________________________

Harold Dost | @hdost

**Comment by asqui** [comment]
Ah, I didn't appreciate that #577 is still based off `develop`.

What is blocking merging of #577; is it just that the build is red, or something else?

(Just trying to get a feel for how long it might be keeping the `develop` branch alive for.)

**Comment by hdost** [comment]
Like I said, I can just cherry pick the change and open a new PR, then we
could delete develop, but that won't happen until Monday.

________________________________________

Harold Dost | @hdost

**Comment by asqui** [comment]
Now that master is green, any objections if I just go ahead and merge #577 and #605 and delete `develop` branch?

**Comment by hdost** [comment]
Only if our next release should have breaking changes, @ssbarnea thoughts?

________________________________________

Harold Dost | @hdost

**Comment by asqui** [comment]
Ah, I was under the impression that we already have breaking changes on master but I appear to be mistaken.

So is the model that breaking PRs get queued up and wait for the next breaking release, at which point we merge all PRs tagged with the "SemVer: breaking-change" label?

Only problem with this model is that long-lived branches may develop more merge conflicts over time, but I can't see any way to avoid this.
