### ISSUE TITLE
Add notify API to python lib

### ISSUE THREAD

**Issue by urosjarc** [pycontribs/jira#582]
Could this feature be implemented?
> https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-api-3-issue-issueIdOrKey-notify-post

I could not see any API in pyJira documentations.

**Comment by stappersg** [comment]
The deep link from https://github.com/pycontribs/jira/issues/582#issue-326003026 needs an update ...

**Comment by hdost** [comment]
@urosjarc

**Comment by stappersg** [comment]
@urosjarc  the request is for updating the original (deep)link that was posted in may 2018. Not a request for creating a pull request. (the link is some kind of broken)

In other words: Please make clear what was the API change that you have spotted.

**Comment by urosjarc** [comment]
Link is updated! Thank you!
