### ISSUE TITLE
Linking Issues with is blocked by type

### ISSUE THREAD

**Issue by diogorb** [pycontribs/jira#585]
At /rest/api/2/issueLinkType there is only the BLOCKS as main link type.
Depending on wich side is INWARD, the relation name is changed (blocks or is blocked by):
```
{
id: "10000",
name: "Blocks",
inward: "is blocked by",
outward: "blocks",
self: "https://XXXXX.atlassian.net/rest/api/2/issueLinkType/10000"
}
```
I need to create a relation of IS BLOCKED BY from ISSUE A to ISSUE B and i´m using like this:
```
    jira.create_issue_link(
        type="is blocked by",
        inwardIssue=linked_issue,
        outwardIssue=issue.key,
        comment={
            "body": "Linking '%s' --&gt; '%s'" % (issue.key, linked_issue),
        }
    )
```
I checked that at your implementation when a type is the same as INWARD, you change the issueIN with issueOUT:
```
elif lt.inward == type:
                    # so that's the reverse, so we fix the request
                    type = lt.name
                    inwardIssue, outwardIssue = outwardIssue, inwardIssue
                    break
```
Result, i can´t make a relation called is blocked by where i need to. The is blocked by side is always been changed to "DESTINATION SIDE"

**Comment by hdost** [comment]
So based on the current implementation, and how your create_issue_link is currently called. To fix in the immediate future. Change to:
```
jira.create_issue_link(
        type="is blocked by",
        inwardIssue=linked_issue.key,
        outwardIssue=issue.key,
        comment={
            "body": "Linking '%s' --&gt; '%s'" % (issue.key, linked_issue),
        }
)
```
The prime issue that I see when calling the code is that inwardIssue and outwardIssue take keys and not strings. Which in and of itself could use an enhancement.

**Comment by diogorb** [comment]
I forgot to say that i can't create links in IssueB, but i can create links
to IssueB. In other words, if i open issueB from UI i haven't access to
create links. I will send later the error that occurs when trying to create
the link.

Diogo Rocha Barbosa
71 992907099
Skype: diogofalemais

Em qua, 30 de mai de 2018 10:59, Harold Dost <notifications@github.com>
escreveu:
