### ISSUE TITLE
Integration testing on https://pycontribs.atlassian.net/

### ISSUE THREAD

**Issue by coddingtonbear** [pycontribs/jira#61]
Hey there!

I have a project -- [jirafs](https://github.com/coddingtonbear/jirafs) -- that relies upon interacting with a JIRA instance using pycontribs/jira.  I've wanted to have more-solid integration tests for quite a while now, and I've been looking around to see if I could find a JIRA instance to use for integration testing, but they're a little bit hard to come by.

Just a moment ago, I happened across the fact that you have an instance that you use specifically for that purpose -- I wonder if I could convince you into providing me access to a project on https://pycontribs.atlassian.net/ for doing my own integration testing of jirafs?

Cheers!

**Comment by ssbarnea** [comment]
Yes, you can but be sure that you use different project names and that you do not abuse the system. Probably you already have the credentials.

/sorin

**Comment by coddingtonbear** [comment]
Awesome; I'm glad to hear that you'll let me!  I'd really hate to be a bother, but there doesn't seem to be anything in the UI that lets me create a project, so I tried doing so via the API (via pycontribs/jira) and received an error:

```
>>> j.create_project('JIRAFS', 'Jirafs Integration Testing')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/jira/client.py", line 2211, in create_project
    r = self._session.post(url, data=payload, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/jira/resilientsession.py", line 81, in post
    return self.__verb('POST', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jira/resilientsession.py", line 74, in __verb
    raise_on_error(r, verb=verb, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.utils.JIRAError: JiraError HTTP 400
	text: You must have global administrator rights in order to modify projects.
	url: https://pycontribs.atlassian.net/rest/project-templates/1.0/templates
```

It doesn't look like I have the permissions necessary, I'm sorry to say.

**Comment by coddingtonbear** [comment]
Worked around via https://github.com/coddingtonbear/jirafs/issues/21.
