### ISSUE TITLE
Delete branches for closed Pull Requests

### ISSUE THREAD

**Issue by asqui** [pycontribs/jira#610]
We have a lot of old branches hanging around in this repo:
https://github.com/pycontribs/jira/branches/all

I noticed this when making a fresh clone, and was surprised at the number of branches that appeared in my cloned repo.

Any objections if I go through and delete all branches relating to Closed and Merged pull requests? This would get rid of 8 out of 17 branches.

In addition we have some branches without related PRs (some of them quite old) created by @ssbarnea, @ybezverkhnyev, and @dbaxa. Do we need these?

Going forward, should we keep feature branches in our own clones in order to keep the main repo clean?

**Comment by hdost** [comment]
No objections here

________________________________________

Harold Dost | @hdost

**Comment by ybezverkhnyev** [comment]
Hi Daniel,

Please feel free to go ahead and delete my branch.
Thanks.

Yaroslav

**Comment by ssbarnea** [comment]
Yep, we will do this but don't put too much pressure on this one. I already closed some of them and I will be closing other. Better to focus on closing PRs as merged or abandon (with nice message to ask creator to re-create it if needed).

We are very close to have 0 open PRs. 

Also now that we have master green, it would be a good opportunity to raise PRs that are fixing specific existing bugs, or that are addressing those disables unit tests.

**Comment by asqui** [comment]
We're down to 5 branches including `master` so that's good enough for me. I just wanted to sanity-check with others before deleting a bunch of branches.

In terms of more productive contributions, I have some changes that I really want to contribute for making it easier to deal with custom fields, but I just don't have the time that this needs right now. Maybe maybe in a month or two :-(
