### ISSUE TITLE
User.delete() fails with 400 response on jira-cloud (test instance)

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jira#612]
**Describe the bug**
User.delete() fails with 400 response on jira-cloud (test instance)

**To Reproduce**
```
j = JIRA('https://pycontribs.atlassian.net', basic_auth=(username, password), async=False)

# for p in j.projects():
#     print(p)
#     try:
#         p.delete()
#     except Exception as e:
#         print(e)

for g in j.groups():
    print("group: %s" % g)
    if str(g).startswith('test'):
        j.gr
    for u in j.group_members(g):
        print("  user: %s" % u)
        if str(u).startswith('test'):
            uo = j.user(u)
            print("Deleting %s" % uo)
                uo.delete()

**Comment by Achimh3011** [comment]
I tried it directly on the HTTP level and as far as I can see it is a Jira issue. The request is documented as EXPERIMENTAL on https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-user-delete so maybe we should not expect too much from it yet...

I'll try to check with a local instance in the next days whether the problem persists.
