### ISSUE TITLE
missing v0.47 tag

### ISSUE THREAD

**Issue by wiggin15** [pycontribs/jira#62]
Hi. This repository is missing several version tags, including one for the latest version, 0.47. Can you please add tags for the correct revisions, and make sure future versions have tags too? It's an important practice. Thanks.

**Comment by ssbarnea** [comment]
This is because the release script in the root is broken. Some help would be welcomed on fixing it as I am really busy these days.

/sorin

**Comment by metashock** [comment]
@ssbarnea I've tried the release script and it looks like it is working. (Of course I created my own fork and commented the upload part). What kind of issues do you see? Would help to fix them.

**Comment by asqui** [comment]
Fixes to the release script aside, could you go ahead and push all previously missed tags for posterity?

I just had a lot of fun reverse-engineering the 0.35 tag, which is missing...

**Comment by ssbarnea** [comment]
Sorry, will not have time to fix the missing release this but I will make a new and tagged release. Releases should be made only from the main branch.

**Comment by asqui** [comment]
> "Sorry, will not have time to fix the missing release this but I will make a new and tagged release."

It would appear the new release has once again not been tagged...
