### ISSUE TITLE
`time.sleep(4)` at end of `Resource.update`?

### ISSUE THREAD

**Issue by aetherknight** [pycontribs/jira#622]
**Describe the bug**

The `jira.resources.Resource.update` method contains a `time.sleep(4)` near the end of its method, that looks like it is always executed, and I think this introduces a lot of performance issues:

https://github.com/pycontribs/jira/blob/master/jira/resources.py#L294-L296

```python
        # TODO(ssbarnea): compare loaded data in order to verify if resource was updated indeed
        # we had random test failures (probably) due to caching
        time.sleep(4)
```

* For non-async code, this adds 4 seconds to every resource updated. For example, if I wish to update every issue that matches some query, that could take a significant amount of time since it adds 4*N seconds. For say, 10 issues, that would add 40 seconds to the total time to update.
* This seems to apply even when using the experimental async feature? (I'm not sure whether the issue's fields/state is reliable after starting an async update, but that's another behavior)

It looks like this sleep was introduced in order to help make CI tests pass. However, it also looks like it negatively impacts normal use of the library.

**Expected behavior**

I would expect that this delay should either be configurable, or only enabled for CI testing (although this may be problematic since that would mean that the code behaves differently in a significant way between CI and normal uses).

**Additional Context**

For my use, I've written an app that responds to webhooks by doing some queries and then updating some related issues and fields. However, if there are more than a handful of issues to update, this sometimes takes a long time, causing my app to run into default timeouts (eg, gunicorn defaults to a 30 second timeout). I can up gunicorn's timeout to 60 seconds, but there are still 60 second-per-request limits since I'm using Google AppEngine for ease of deployment.

**Comment by chevell** [comment]
This explains a lot, I ran into some similar speed issues when running synchronously. Barring a functional reason for it, @aetherknight it seems worth opening a PR to remove. 

Note: there's also a `time.sleep(1)` in `jira.JIRA.create_version`, which again introduces 1*N delays that may become apparent in large calls (for example, generating a large volume of test data via the API). The only other place `time.sleep` is used in this library is in `jira.resilientsession.ResilientSession.__recoverable`, but its use there (to enforce an exponential backoff in retrying after session failures) seems reasonable. That being the case I would expect to see a PR address both `jira.resources.Resource.update` and `jira.JIRA.create_version`. 

It would be great to get some guidance from @ssbarnea who likely has much more background on why these delays were originally required, and what the expected side effects of removing them might be.

**Comment by guitarhero23** [comment]
Yes I just changed this in mine to no sleep and a 33 second script finished in 14 seconds

**Comment by aetherknight** [comment]
Any progress on this? or is it being marked wontfix because noone has discussed it in a while?

**Comment by ssbarnea** [comment]
The label is wrong, it should be stale instead of wonfix but I did not had time to fix that. I am very busy with other projects so I need to delay work on JIRA. Still, if there are PRs that are passing CI, I will help you merge them. If review/merge is needed ping me on irc on #pycontribs channel.

**Comment by adehad** [comment]
d328ab834c2e3dce19c0433cc933623b063bc0dd
