### ISSUE TITLE
maxResults behaviour is inconsistent with Jira API

### ISSUE THREAD

**Issue by dchevell** [pycontribs/jira#623]
**Describe the bug**
`JIRA._fetch_pages` has the ability to iterate through paged results. This function uses `maxResults` to determine whether to iterate through all pages, or whether to return the first page only. This means that in order to fetch all pages of results instead of just the first page, `maxResults` must be set to `None`.

In Jira's API, `maxResults` only defines how many items to return *per page*, and has no relationship to how many pages of results are available or how many pages can be returned. It is not intended to control the total number of results available from an API call: total results are limited by `total` parameter. `maxResults` is primarily intended to manage the memory requirements of returning too many issues at once (e.g. with a low max heap you might reduce `maxResults` to 25, resulting in more pages but less memory usage per page).

Because `maxResults` has no relation to the number of pages available in Jira itself, its current use in determining whether to page through results is inconsistent with the Jira API and doesn't make much sense.

**To Reproduce**
This is most obvious when using `JIRA.search_issues`, where `maxResults=50` is the default value. Paging through issues must be performed manually, unless you set `maxResults=None` (in which case, Jira *still* uses its default `maxResults` value of 50, only now `JIRA.search_issues` will handle paging for you).

 
```
>>> jira = JIRA(JIRA_SERVER, basic_auth(JIRA_USER, JIRA_PASS))
>>> jql_str = """project=MYPROJ""" # some JQL that will return more than 50 issues
>>> ### Query for issues using default options
>>> len(jira.search_issues(jql))
50
>>> ### Query for issues setting no default value for max results per page
>>> len(jira.search_issues(jql, maxResults=None))
1000
```

**Expected behavior**
Setting `maxResults` should not affect automatic paging behaviour. There may be legitimate reasons to want to limit results to 25 per page (say a small max heap in the JVM), whilst retaining automatic paging.

**Suggested solution**
Putting aside the use of `maxResults` to define unrelated behaviour, if it is desired to only return one page of results then defining an explicit `iter_pages=True` option in the function signature that can be overridden via the module's public interfaces would serve that purpose.

Note: Correct or not I realise this would constitute a breaking change, so it would make sense to address this in the 2.0 release required to address Python 3.7 compatibility.

Also, full disclosure: I work for Atlassian's Premier Support team (and I love your work here!) I've been using this library for a while now and have always hand written paging code. I was planning to open a PR to add the feature when I found out it already exists. Happy to send a PR to address this issue, and to provide an `iter_pages` option to use in the current logic rather than removing that logic altogether.

**Version Information**
Python Interpreter: 3.7
jira-python: jira-2.0.0.0rc1
OS: macOS

**Comment by chevell** [comment]
Tangentially related: In my hand-written paging code, I always turned this into a generator that would yield issues from each page of results, and it was **awesome**. It meant that if I was looking for some particular item in my results, I could break once I found it and not have to incur the cost of loading subsequent pages. Whether or not you address the concern raised here, what are your thoughts on making `JIRA._fetch_pages` a generator in pycontribs/jira 2.0? Again, happy to raise a separate PR for that.

**Comment by dchevell** [comment]
Given that pycontribs/jira 2.0.0 has now been released, there may be more friction in fixing this issue as it's a breaking API change.

**Comment by dchevell** [comment]
Is it possible to get feedback on this from the maintainers? In its current state, this library's API is broken - but the incorrect behaviour has been around so long that people probably rely on it. A major version change was the only reasonable place to fix that behaviour, but now 2.0 has been released I'm not as confident in this sort of bad behaviour being addressed.

**Comment by hdost** [comment]
@ssbarnea what are your thoughts on this?

**Comment by dchevell** [comment]
Any guidance on this? I'm hesitant to simply open a PR to fix the behaviour, because it changes the package API and semantic versioning would call for updating to 3.0

**Comment by dchevell** [comment]
Is there any plan to address this issue in a future major release (i.e. 3.0)?

**Comment by hdost** [comment]
I'd have to look at the code to make a good pr for this, but i think there's no reason why we couldn't do a 3.0 bump. What i think right now would be best is to have it just act as the API does. 
I should have some time in The next couple weeks to look over it.
