### ISSUE TITLE
Printing all comments

### ISSUE THREAD

**Issue by sk75** [pycontribs/jira#644]
Referring to the issue I opened earlier - https://github.com/pycontribs/jira/issues/642. And this documentation was helpful - http://jira.readthedocs.io/en/master/examples.html#comments

I am trying to print the comments in a Jira issue using below code. It just prints the issue id. How do I print the text. Any help is appreciated. Thanks!

issue=jira.issue(issues[5].key)
commenta = jira.comments(issue)
commenta
Output is: 
\[\<JIRA Comment: id='39471'\>, \<JIRA Comment: id='39478'\>, \<JIRA Comment: id='39481'\>, \<JIRA Comment: id='39490'\>, \<JIRA Comment: id='39497'\>\]

**Comment by hdost** [comment]
consider using the `dir` command as an example with your code above take `dir(commenta[0])` this will show you what the available fields are for the class Comment.

**Comment by hdost** [comment]
Also all objects are based off the properties which are represented in the API. https://developer.atlassian.com/cloud/jira/platform/rest/

**Comment by sk75** [comment]
Thanks for the above link.

**Comment by sk75** [comment]
The answer is: 
commenta[0].body
(see rest of the code above)
