### ISSUE TITLE
issue.update doesn't work without hackery

### ISSUE THREAD

**Issue by fastcat** [pycontribs/jira#65]
```
i.update(assignee={'name':'foo'})
...
JIRAError: HTTP 400: "one of 'fields' or 'update' required"
http://jiraserver/jira/rest/api/2/issue/497258
```

```
i.update(fields={'assignee':{'name':'foo'}})
...
JIRAError: HTTP 400: "one of 'fields' or 'update' required"
http://jiraserver/jira/rest/api/2/issue/497258
```

```
i.update(fields={'fields':{'assignee':{'name':'foo'}}})
...
# works
```

JIRA server in this case is running 6.3.x.  As far as I can tell, this syntax structure has been required ever since the issue PUT REST API was added.

**Comment by ssbarnea** [comment]
Accepting pull requests! I would like even simple models like: update(assignee: userid)

/sorin

**Comment by fastcat** [comment]
I'll see if I can work something up ... I'm a bit of a n00b in python still.

As part of working around this, I also figured out the convoluted syntax for adding a comment as part of the update, which seems like something that might be handy to include as an argument to that method to fill in the shorthand.  The syntax is roughly: ```'update':{'comment':[{'add':{'body':'blah blah blah'}}]}```

**Comment by fastcat** [comment]
I think my original problem was actually caused by trying to mix fields and update, because this is working now ... but making Issue.update support that seems like a good idea

**Comment by Tossrock** [comment]
+1. Trying to update a field is next to impossible in the current version without finding this hack.

**Comment by ssbarnea** [comment]
I agree with you that it should be easier but due to the lack of time I will close this. I will try to merge any pull request, so you are welcomed to improve the API or just the documentation.
