### ISSUE TITLE
Tempo API to obtain worklogs for a custom period of time

### ISSUE THREAD

**Issue by karolszk** [pycontribs/jira#668]
Hi! 

First I would like thank you for a such great python library! :)
Is it possible to obtain an access to Tempo plugin in python? 
I am looking for obtaining aggregated worked hours for a specific period of time for a groups of people.

Regards, Karol Szk

**Comment by guitarhero23** [comment]
Tempo has free trials, can you just install a free trial and work with that? Also if you need multiple free trials you could technically do a new Jira trial after that, I think you can install addons during a trial though I'm tno 100% sure on that
