### ISSUE TITLE
The docs refer to Dash support, but link is broken.

### ISSUE THREAD

**Issue by mattkatz** [pycontribs/jira#687]
**Describe the bug**
The public website lists a dash docset.
The link produces a 404.
The rst for the dash file also refers to https://jira.readthedocs.io/en/latest/docset/jira.tgz
That also produces a 404

**To Reproduce**
1. Click the link titled dash feed on https://jira.readthedocs.io/en/latest/index.html

**Expected behavior**
I would expect a link into the dash docset.

**Comment by hdost** [comment]
@ssbarnea so you want to support dash? If not propose we just remove the link

**Comment by ssbarnea** [comment]
https://s3-eu-west-1.amazonaws.com/pycontribs/docsets/jira.tgz should work for now, fix the link

**Comment by mattkatz** [comment]
Hey - so I just wanted to let @ssbarnea  know that I get an access denied on trying to access that URL https://s3-eu-west-1.amazonaws.com/pycontribs/docsets/jira.tgz

**Comment by ssbarnea** [comment]
I will take care of this bug, fixing it. I am using dash daily.

**Comment by mattkatz** [comment]
I missed stalebot killing this, but dash link is still broken
