### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by rominf** [pycontribs/jira#689]
**Is your feature request related to a problem? Please describe.**
PyCharm doesn't provide me type hints for `jira` library.

**Describe the solution you'd like**
It would be nice to have type hints in `jira` library. `jira` library supports Python 2.7, which doesn't support type hints, therefore, I suggest you include stub files.

**Additional context**
There are tools for generating stub files: https://mypy.readthedocs.io/en/stable/existing_code.html#automate-annotation-of-legacy-code, although, I have not tested them yet.

**Comment by hdost** [comment]
I believe I handled this.

**Comment by rominf** [comment]
Nice! But it seems that MyPy doesn't support docstrings in this format. Do you consider creating stub files?
