### ISSUE TITLE
GDPR: JIRA API changes regarding users

### ISSUE THREAD

**Issue by petroswork** [pycontribs/jira#697]
According to [this](https://developer.atlassian.com/cloud/jira/platform/api-changes-for-user-privacy-announcement/?_ga=2.175026080.366259731.1533136712-1276219155.1503476605), the API regarding users will change, several attributes will be removed, one will be added and some may change value/behaviour.

This will require changes to documentation and possibly the methods that depend on the `key` or other attribute to be deprecated. Some likely changes to the code are in class `Resource`, `_READABLE_IDS` and the `add_user` method.

**Comment by hdost** [comment]
Sounds like many of the changes are around user attributes, most of which are checked for in the API. I think the action for this to make the work lighter is to break it down for by their tracking issues and then further subdivide in the case of the issue being to large.

**Comment by petroswork** [comment]
Also, `current_user()` seems to be affected, as it reads the `X-AUSERNAME` header, while it should be using the `X-AACCOUNTID` header instead.

**Comment by CSimpiFoN** [comment]
I suppose these changes were not implemented yet, but the deadline is closing in very fast. Also it seems some changes were already made on Atlassian's side that brake the authentication of this module in some cases.

**Comment by ssbarnea** [comment]
One can always [open a bounty](https://www.bountysource.com/) to try to motivate people ;)

**Comment by myuwono** [comment]
@ssbarnea @CSimpiFoN I've opened #780 for the authentication module.
