### ISSUE TITLE
Updating/Deleting Comments --> "Got recoverable error from PUT/DELETE"

### ISSUE THREAD

**Issue by Tagman** [pycontribs/jira#698]
**Describe the bug**
When trying to update an existing comment by using its ID, the server always responds with an 401 - Unauthorized.

**To Reproduce**
```
import jira_worker
worker = jira_worker.Worker()
server = worker._server
server.comment("OLATCE-6353", 201593)
<JIRA Comment: id='201593'>
comment = server.comment("OLATCE-6353", 201593)
old = comment.body
new = old + "\nTESTING!!!!"
comment.update(body=new)

```
I have written a wrapper around the library, to initialize a server. Still the calls in this example all use the api objects. The Auth is done with basic_auth. The code is this:
```	
def _initialize(self):
		"""Init server with values from the config"""

		serverURL = self._config['server']['server_url']
		username = self._config['server']['username']
		password = self._config['server']['password']
		jira = JIRA(server=serverURL, basic_auth=(username, password))
		logging.debug("Jira server: {0} initialised".format(serverURL))
		return jira
```
 Adding new comments works with the same object. And the correct user is used. The response headers suggest that the request is not sent with the authenticated user but instead as anoymous.

Is this maybe related to [ISSUE-528](https://github.com/pycontribs/jira/issues/528) ?

**Expected behavior**
The comment should contain the new string.

**Stack Trace**
```
WARNING:root:Got recoverable error from PUT <BASE_URL>/rest/api/2/issue/65293/comment/201593, will retry [1/3] in 14.085268728018857s. Err: 401 401
WARNING:root:Got recoverable error from PUT <BASE_URL>/rest/api/2/issue/65293/comment/201593, will retry [2/3] in 11.216269152043568s. Err: 401 401
WARNING:root:Got recoverable error from PUT <BASE_URL>/rest/api/2/issue/65293/comment/201593, will retry [3/3] in 36.92498948404944s. Err: 401 401
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/chhar/projects/python/envs/autoFlow/lib/python3.6/site-packages/jira/resources.py", line 525, in update
    super(Comment, self).update(data)
  File "/home/chhar/projects/python/envs/autoFlow/lib/python3.6/site-packages/jira/resources.py", line 232, in update
    self.self + querystring, data=data)
  File "/home/chhar/projects/python/envs/autoFlow/lib/python3.6/site-packages/jira/resilientsession.py", line 157, in put
    return self.__verb('PUT', url, **kwargs)
  File "/home/chhar/projects/python/envs/autoFlow/lib/python3.6/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/chhar/projects/python/envs/autoFlow/lib/python3.6/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 401 url: <BASE_URL>/rest/api/2/issue/65293/comment/201593
	text: You do not have the permission to see the specified issue.
	
	response headers = {'Date': 'Wed, 26 Sep 2018 12:56:54 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-AREQUESTID': '896x40968x1', 'X-ASEN': 'SEN-2021575', 'X-AUSERNAME': 'anonymous', 'Cache-Control': 'no-cache, no-store, no-transform', 'WWW-Authenticate': 'OAuth realm="https%3A%2F%2Fwww.bps-system.de%2Fdevel"', 'Content-Type': 'application/json;charset=UTF-8', 'Vary': 'User-Agent', 'Keep-Alive': 'timeout=60, max=697', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked'}
	response text = {"errorMessages":["You do not have the permission to see the specified issue.","Login Required"],"errors":{}}
```

**Comment by Tagman** [comment]
Testing this on a local JIRA server running on docker. It works as expected. I am doing the same steps.
Does the update and delete method for comments need any special permission?

On my local system, I am doing the operation with the first user, so the administrator. On our live system, we have a special user for all these things. He has the rights to delete and edit any comment, and we can do this over the UI with no problem. Even giving him admin rights didn't change anything.

The JIRA Server runs behind a tomcat server. Might this on be blocking the PUT and DELETE requests? Against this speaks, that the error message is from JIRA, so the request needs to get through to the server somehow.

**Comment by Tagman** [comment]
Okay, new information. Our live JIRA server URL is redirected through a DNS. While creating the JIRA object I use our direct URL. Adding a comment throught jira.add_comment(..) works because the direct URL is refrenced inside the jira object, while grabing the comment the indirect URL as shown in the error message is referenced inside the comment object.

I guess the URL is grabbed from the JSON response. Is it possible to use the URL specified while creating the JIRA object?

As a workaround I will try to replace the URL string of the comment  with the direct URL. Hope this works.

**Comment by ssbarnea** [comment]
Jira will not work well under multipe DNS names, whatever you would try to do, it will still fail in many places. Assure that URL that you use is the same as the one configured in JIRA and it will work. Yep, you can use proxies, but don't try to change the domain name with them.
