### ISSUE TITLE
Clone an issue

### ISSUE THREAD

**Issue by ultrabug** [pycontribs/jira#699]
**Is your feature request related to a problem? Please describe.**
I need to be able to clone an issue, just like I can do in the interface "Clone" feature

**Describe the solution you'd like**
issue.clone() helper

**Describe alternatives you've considered**
Copying the fields of an issue, but I didn't find a proper way to do it.

**Comment by ultrabug** [comment]
I see this: https://jira.atlassian.com/browse/JRASERVER-25812

I guess statement has not changed since then? if so, feel free to close this issue, thanks.

**Comment by hdost** [comment]
While that would make things a lot easier, I don't necessarily see reason
that a method could not be created, but I am not sure it would be a
straight forward one.

I think that expectations would be that the clone happens in the same way
as it does in the JIRA ui.

Maybe a clone_simple()

**Comment by ultrabug** [comment]
Indeed @hdost it should not be too hard I guess for someone with experience and QA practice on this project.

The JIRA UI uses the `CloneIssueDetails.jspa` endpoint which unfortunately returns a HTML like this:

```
<div class="jira-dialog-content">
        <div class="dialog-title hidden"></div>    
</div>
```

So it's not handy to get the created issue ID/key from this.

**Comment by hdost** [comment]
There's no guarantees on the interface with non API endpoints, and even
less communication as to the changes that happen on that front. We only
implement against the documented REST API.

________________________________________

*Harold Dost* | @hdost

**Comment by ultrabug** [comment]
@hdost which is why I'm asking this question since I didn't find any API endpoint to handle issue cloning.

So unless it becomes available on the API, only option is to use the `CloneIssueDetails.jspa` and hope for the best :(

**Comment by stappersg** [comment]
Our solution boils down to
```
    jirases = JIRA(ses_options)
    r = jirases.create_issue(fields=nextissue)
    r = jirases.create_issue_link('Cloners', r.key, issue['key'])
```
where `issue` and `nextissue` are dictionaries with ticket information.

Cheers
Geert Stappers
DevOps engineer at hendrikx-itc.nl

**Comment by hdost** [comment]
@ultrabug if you want to make a patch that adds a client function `copy_issue` that does something similar to above, we could make that work. Just add a test to verify the code works. , Should be

**Comment by ultrabug** [comment]
@stappersg thanks, that's interesting but I'd like to know how you constructed `nextissue` and `issue` please?

@hdost for now I just monkey patch the client using:

```python
def clone_issue(self, issue):
        url = self._options["server"] + "/secure/CloneIssueDetails.jspa"
        self._options["headers"][
            "Content-Type"
        ] = "application/x-www-form-urlencoded; charset=UTF-8"
        userInfo = {
            "decorator": "dialog",
            "id": issue.id,
            "inline": "true",
            "summary": issue.fields.summary,
        }
        try:
            r = self._session.post(
                url, headers=self._options["headers"], data=userInfo
            )
            if r.status_code != 200:
                raise Exception(
                    "Got response from Cloning %s: %s" % (issue.id, r.status_code)
                )
        except Exception as e:
            raise Exception("Error Cloning %s: %s" % (issue.id, e))
```

Then I refresh the original issue and explore `inwardIssue` to find my cloned issue. This is dirty so indeed if I get something better to work, I'll propose it thanks.
