### ISSUE TITLE
Send search request as POST for large queries

### ISSUE THREAD

**Issue by zgoda-mobica** [pycontribs/jira#701]
**Is your feature request related to a problem? Please describe.**
Jira API allows search requests to be performed either as GET or POST, with POST suggested for queries that can't be encoded as query params. I have a query with ~60k clauses, ~60 bytes each after encoding as query param.

**Describe the solution you'd like**
For queries that can't be encoded as query params use POST request with JSON payload instead of GET.

**Comment by ssbarnea** [comment]
I totally agree with your proposal. Now you only need to make a PR to address it.

**Comment by zgoda** [comment]
For over a year I used only POST requests for search in Jira and did not notice any issues. I think this should be default - it's hard to know what's the url size boundary and in theory this depends on servlet container implementation (can't say as I use only Tomcat).
