### ISSUE TITLE
Provide a function for retrieving user permissions

### ISSUE THREAD

**Issue by rominf** [pycontribs/jira#705]
**Is your feature request related to a problem? Please describe.**
I'm writing a bot to create issues from Telegram. The bot is logged to Jira as administrator, therefore it can create issues in any projects. I want to retrieve and check the permissions of a specific user.

**Describe the solution you'd like**
I propose to add a function that wraps https://docs.atlassian.com/software/jira/docs/api/REST/7.12.0/#api/2/user-findUsersWithAllPermissions.

**Comment by SeanTurner026** [comment]
Is there any way to check permissions currently? I'm automating releases in Jira across multiple Jira projects, and want to check that the user running the automation tool has Admin access in each project.
