### ISSUE TITLE
<jira.client.JIRA object at 0x109e681d0> is not JSON serializable or can't pickle weakref objects with pickle module

### ISSUE THREAD

**Issue by pavan538** [pycontribs/jira#71]
i am working on my web application where it integrates jira, confluence, fisheye-crucible.
when i submit my username and password i am able to return  the object using
```
jclient=JIRA(server,basic_auth=(username,password)
```
I don't like to create jclient object for every request , when the  user using for different operations.
so i like to save the object in user session in django.

when i try to serialize the  jclient object for further use it is not serializing and gets the following errors with different serializer's.

with json:
```
<jira.client.JIRA object at 0x109e681d0> is not JSON serializable
```
with pickle:
```
can't pickle weakref objects with pickle module
```

with dill:
```
ctypes objects containing pointers cannot be pickled
```

How can i used this app in my web application where i create a single JIRA object through out the user session in django.

**Comment by ssbarnea** [comment]
I bet you are not using latest release.

**Comment by pavan538** [comment]
I am using 0.48 version.
