### ISSUE TITLE
deactivate_user() returns True, but user remains active if he is a project lead

### ISSUE THREAD

**Issue by kdeyko** [pycontribs/jira#711]
**Describe the bug**
deactivate_user() returns True, but user remains active if he is a project lead in some project. GUI will not let you to deactivate project lead and returns clear error.

**To Reproduce**
```
from jira import JIRA
jira = JIRA(jira_url, basic_auth=(username, password))
jira.deactivate_user('user') # user should be project lead
# Returns True
# exit code 0
```

**Expected behavior**
Program should return clear error.

**Version Information**
Python Interpreter: 3.7.0
jira-python: 2.0.0
OS: Windows 10

**Comment by hdost** [comment]
Duplicate of #348
