### ISSUE TITLE
Support Custom Field Management 

### ISSUE THREAD

**Issue by rahiparikh** [pycontribs/jira#717]
**Description**
Allow Jira library to manipulate (add/update/delete) custom fields. 

**Usecase**
Allowing users to create/modify custom fields on the fly would allow one to update required metadata for an issue before creating issue itself.

**Comment by wesinator** [comment]
I'm looking for this as well, when creating issues.
Tried adding it like a component to the issue fields
`'customfieldname': [{"name": "blah"}]`
this didn't work

is there a way to add custom field when creating issue ?

**Comment by JasonKempSEL** [comment]
Custom fields are specified like any other field when creating an issue, but using their ID:
`"customfield_12345": "value",` . What each custom field needs for a value depends on its type.

There is no API endpoint in Jira (to my knowledge) for actually creating/updating custom fields so this library cannot support that.

**Comment by wesinator** [comment]
> Custom fields are specified like any other field when creating an issue, but using their ID:
> `"customfield_12345": "value",` . What each custom field needs for a value depends on its type.
> 
> There is no API endpoint in Jira (to my knowledge) for actually creating/updating custom fields so this library cannot support that.

thanks. that's odd 
I guess I shouldn't be surprised given Atlassian's lack of support for developers and convoluted products.

**Comment by asqui** [comment]
We are using this helper class to handle mapping between custom field ids and their names:
```
class CustomFields(object):
    """
    Allows you to map a custom field name to it's internal ID.
    e.g. TOP Visible -> customfield_10414
    """

    def __init__(self, jiraClient):
        self.fields = {}  # name -> (id, type)
        self.fieldIds = {}  # id -> name
        for field in jiraClient.fields():
            name, fieldId, fieldType = field['name'], field['id'], field.get('schema', {}).get('type')
            self.fields[name] = (fieldId, fieldType)
            self.fieldIds[fieldId] = name

    def _getField(self, fieldName):
        try:
            fieldId, fieldType = self.fields[fieldName]
        except KeyError as e:
            raise KeyError("Unknown custom field name: '%s'\n"
                           "Known field names are: %s" % (str(e), self.fields.keys()))
        return fieldId, fieldType

    def id(self, fieldName):
        fieldId, _ = self._getField(fieldName)
        return fieldId

    def name(self, fieldId):
        try:
            return self.fieldIds[fieldId]
        except KeyError as e:
            raise KeyError("Unknown custom field id: '%s'\n"
                           "Known field ids are: %s" % (str(e), self.fieldIds.keys()))

    def type(self, fieldName):
        _, fieldType = self._getField(fieldName)
        return fieldType
```

This could theoretically be integrated into the library to allow for seamless support of custom fields.

e.g. Pre-process field names provided by user code to the library, discern if each is a valid field name, if not, attempt to map to a name like customfield_12345.
Post-process field names coming from jira, map the names like customfield_12345 to user-facing custom field names before returning data to the user.

Unfortunately I've not had time to fashion this idea into a PR.
