### ISSUE TITLE
Add a method to modify a version that has already been created

### ISSUE THREAD

**Issue by Rumbles** [pycontribs/jira#721]
**Is your feature request related to a problem? Please describe.**
I want to start using this tool to manage a deployment process, but one step involves creating a version, and another step would be to mark that version as released if the build is sucessful. Currently I see no way of modifying a version once it has been created.

**Describe the solution you'd like**
Add a method to modify a version

**Describe alternatives you've considered**
I thought of calling the API directly, or deleting the version and then creating the new version with the right status, but neither of these would be great in my opinion

**Additional context**
I have already prepared a fork that would fix this issue, PR to follow

I don't think the way I have done it is necessarily the cleanest way to do it, maybe someone could point me in the right direction if you're not happy with it.

**Comment by Rumbles** [comment]
@ssbarnea has asked for more information, I have been asked to create a workflow that the significant part of this involves 2 steps:

- Each evening when we complete an automatic build we create a new release, this release will be used the next day to track any work, as we need to put a version number on JIRA tickets.
 - Each evening we build a new release with all the commits from that day, if the build is successful the version is marked as released. We then need to create a new version for the following days work.

I was looking at using this tool to do these steps, but while I could see a way to do this in the JIRA API, there was only a way to create a new release in this python JIRA project, no way to modify a version that already exists (that I could see in the documentation).

I need a way to change a release from Unreleased to Released or visa versa.

I have added that functionality with my pull request.

If you need any more specific details, please let me know what info you need, thanks!

**Comment by mhienle** [comment]
Am I missing something here? To me it looks like this functionality is already there. When you call `create_version`, you get the `Version` object (see [here](https://github.com/pycontribs/jira/blob/master/jira/client.py)) which has an `update` method (see [here](https://github.com/pycontribs/jira/blob/master/jira/resources.py)).

**Comment by Rumbles** [comment]
If it's there @mhienle I couldn't see anything for it in the documentation

Do you know where it is documented?

I saw the update method in the code, but I don't see how you use it.

**Comment by mhienle** [comment]
I thought of something like
```python
version = jira.create_version(...)  # https://jira.readthedocs.io/en/master/api.html#jira.JIRA.create_version
...  # do stuff
version.update(released=True)  # not documented
```
In the first line, you could also pass `released=True` or `released=False` to the function `create_version`, so I guess passing `released=True` to `version.update` should work (though I haven't tried).

Not sure if there should be more documentation. Also, the test for `update_version` could show a bit more examples.

**Comment by Rumbles** [comment]
Thanks, I'll see if I can get that to work later

**Comment by Rumbles** [comment]
Thanks @mhienle  that does indeed work, but it would be really helpful for people starting to use this tool for that to be documented, since it's not in the client it doesn't appear on readthedocs, so without reading through the code there isn't an easy way to know how to do that
