### ISSUE TITLE
Expose documentation

### ISSUE THREAD

**Issue by hdost** [pycontribs/jira#725]
**Is your feature request related to a problem? Please describe.**
Currently there is a lot of documentation strings which are not available to the users. Leading to confusion as mentioned in #722 

**Describe the solution you'd like**
I think that if we had something more like how boto3 exposes https://github.com/boto/boto3/blob/develop/docs/source/reference/services/index.rst in our doc/api.rst this would expose all of the desired documentation without needing to add a new section individually for each class added. 

**Describe alternatives you've considered**
We could just add each class , but if Sphinx can handle it I figure we should use it. 

**Additional context**
N/a

**Comment by adehad** [comment]
@hdost #1023 does what I think you are looking for here. If you are able to pop by for a review that would be great
