### ISSUE TITLE
Captcha challendge handling

### ISSUE THREAD

**Issue by rominf** [pycontribs/jira#733]
**Is your feature request related to a problem? Please describe.**
I'm trying to login to https://jira-dev.kama.gs/ but I'm getting an error:
```
jira.exceptions.JIRAError: JiraError HTTP 403 url: https://jira-dev.kama.gs/rest/api/2/serverInfo
text: CAPTCHA_CHALLENGE; login-url=https://jira-dev.kama.gs/login.jsp
...
```

**Describe the solution you'd like**
I propose you to include a link to an image to the exception and add a method for supplying an answer for captcha (link to the image is sent to the man, he solves the captcha, sends the answer back the program, program calls `e.solve_captcha(answer)` and Jira authenticates the program).

**Describe alternatives you've considered**
-

**Additional context**
I didn't find a method for solving the captcha in the Jira API, but I think it's not hard to implement without it.

**Comment by ssbarnea** [comment]
It is outside the scope of this library to deal with CAPTCHA_CHALLENGE. If you encounter it please contact jira admins and find a way to avoid it, like using tokens.
