### ISSUE TITLE
jira.add_attachment() can not support Chinese 

### ISSUE THREAD

**Issue by huatiedan** [pycontribs/jira#736]
when use jira.add_attachment() method,the fileName param can not support Chinese, when use chinese , the attachment can not update.

**Comment by lzakharov** [comment]
The same is true for Cyrillic. 

I get HTTP **500** Internal Server **Error** when running `jira.add_attachment(issue=issue, attachment=attachment, filename='документ.pdf')` :
```
JIRAError: JiraError HTTP 500 url: https://JIRA.SERVER/rest/api/2/issue/GC-996/attachments
	
	response headers = {'Server': 'nginx/1.12.0', 'Date': 'Fri, 11 Jan 2019 18:27:18 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-AREQUESTID': '1287x20464280x1', 'X-ASESSIONID': 'x3nqrn', 'X-ASEN': 'SEN-L10306871', 'X-Seraph-LoginReason': 'OK', 'X-AUSERNAME': 'l.zaharov', 'Cache-Control': 'no-cache, no-store, no-transform', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent'}
	response text = 


```

**Comment by ssbarnea** [comment]
I am closing this report as it seems incomplete. You should better make PR that reproduces the bug, even if you do not know how to solve.

I suspect that the encoding issue could be server side related. Still, if you can upload the same file to the server using the browser is likely to be in the python client.

In any case a bug report without the response from the server is not useful.
