### ISSUE TITLE
jira 4.4.5 get version and field

### ISSUE THREAD

**Issue by CodeJuvenile** [pycontribs/jira#739]
we use pip install this tools "jira",after over, i find the client.py like have a little problem:
1. "self._version = tuple(si['versionNumbers']) " , our version is 4.4.5 ,param's name is 'version' not 'versionNumbers' ,I don't know what it does.make it commented code, run Smoothly！
2. like this : 
      for f in self.fields():
         if 'clauseNames' in f:
             for name in f['clauseNames']:
                 self._fields[name] = f['id']
this is source,but our jira do not have /rest/api/2.0.alpha1/fields,make it commented code, run Smoothly！

**Version Information**
Python Interpreter: 2.7
jira-python: 2.00
OS: ubuntu 18.0.4
Other Dependencies:

**Comment by ssbarnea** [comment]
Support for python 2.7 was dropped.
