### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshfriend** [pycontribs/jira#75]
I ran into issues caused by the bug that was fixed in #57 today. It would be awesome to have this fixed in the version on PyPI. [It looks like there has been a bunch of other changes since 0.43 as well](https://github.com/pycontribs/jira/compare/0.43...master).

**Comment by joshfriend** [comment]
Also, the PyPI version is 0.47, but the highest tag here is 0.43.

**Comment by joshfriend** [comment]
related: #81

**Comment by dbaxa** [comment]
Can we close this issue now that #81 and #62 have been fixed?

**Comment by joshfriend** [comment]
Yup. Thanks!
