### ISSUE TITLE
projectKeyOrID not available as argument for boards init

### ISSUE THREAD

**Issue by kentsanggds** [pycontribs/jira#752]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**

projectKeyOrID is not available as an argument for jira.boards

This is the error I get when I try to pass in `projectKeyOrID` - 

```
File "/Users/xxx/.virtualenvs/yyy/lib/python3.6/site-packages/jira/client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
TypeError: boards() got an unexpected keyword argument 'projectKeyOrID'
```

To work around this as it appears to be supported I'm doing this in the `requirements.txt` file - 

```
-e git://github.com/pycontribs/jira.git@master#egg=jira
```

but it's obviously not the best way to get it working.

****

**To Reproduce**

In the `requirements.txt` use this to install jira client

```
jira==2.0.0
```

then in the main code do something like this - 

```
boards = self.jira.boards(projectKeyOrID=project.id)
```

1. Any additional steps or considerations that happen before or after.

**Expected behavior**
No exceptions when passing in projectKeyOrID to boards init

**Stack Trace**
```
  File "/Users/xxx/.virtualenvs/yyy/lib/python3.6/site-packages/jira/client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
TypeError: boards() got an unexpected keyword argument 'projectKeyOrID'
```

**Version Information**
Python Interpreter: 3.6
jira-python: 2.0.0
OS: Mac OS
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by greenberge** [comment]
I had the same problem. My workaround was as follows:

```
boards = self.jira.boards(projectKeyOrID=project.id)
board_i_want = [board for board in boards if board.location.locationKey == 'KEY']
```
This is obviously not ideal if you have a large amount of boards, but it unblocked my progress. 

Ideally, the code would match the[ docs](https://jira.readthedocs.io/en/master/api.html?highlight=boards)

**Comment by bprager** [comment]
There is a mismatch at the pip installed package "2.0.0" and the github repo:

Github version in https://github.com/pycontribs/jira/blob/master/jira/client.py line 3626: `def boards(self, startAt=0, maxResults=50, type=None, name=None, projectKeyOrID=None):`
In pip installed version ```
$pip freeze | grep jira
jira==2.0.0
``` in client.py line 3035: `def boards(self, startAt=0, maxResults=50, type=None, name=None):`

**Comment by bprager** [comment]
> There is a mismatch at the pip installed package "2.0.0" and the github repo:
> 
> Github version in https://github.com/pycontribs/jira/blob/master/jira/client.py line 3626:
> `def boards(self, startAt=0, maxResults=50, type=None, name=None, projectKeyOrID=None):`
> In pip installed version
> 
> ```
> $pip freeze | grep jira
> jira==2.0.0
> ``` 
in client.py line 3035: 
> `def boards(self, startAt=0, maxResults=50, type=None, name=None):`
> ```

**Comment by bprager** [comment]
The function is updated in release 2.0.1rc2. I am still testing but it appears not to be working correctly yet. (I am getting all boards for all projects regardless of the project ID.)

**Comment by saisujit** [comment]
Old GreenHopper API's are not supported and are not taking any parameters. if you run jira.boards you get output without parameter conditions.

**Comment by vpolimenov** [comment]
has this been resolved now? :eyes:
