### ISSUE TITLE
can't take worklog

### ISSUE THREAD

**Issue by Volosatiyslon** [pycontribs/jira#754]
can't got worklog entries

my code is:

```
from jira import JIRA
jira = JIRA(basic_auth=('robot', 'somepass'), options={'server': 'someurl'})
issue = jira.issue('INT-117')
worklogentry=issue.fields.worklog.worklogs[0]
```

when I try to run it i got

```
Traceback (most recent call last):
  File "jiratest.py", line 4, in <module>
    worklogentry=issue.fields.worklog.worklogs[0]
AttributeError: type object 'PropertyHolder' has no attribute 'worklog'
```
JIRA 7.9.2
pip -list: jira 2.0.0
python 2.7 and 3.7
running on macOS

**Comment by ankitg1989** [comment]
The same code is working for me.

**Comment by Terseus** [comment]
I can confirm that my `fields` property from any issue doesn't have a `worklog` attribute.

I've inspected all the attributes in `fields` and the worklogs aren't there at all.

However I found that I can use [`JIRA.worklogs`](https://jira.readthedocs.io/en/master/api.html#jira.JIRA.worklogs) to get the worklogs passing it an [`Issue`](https://jira.readthedocs.io/en/master/api.html#issue) instance from [`search_issues`](https://jira.readthedocs.io/en/master/api.html#jira.JIRA.search_issues).

I'm using the Jira Cloud product.
