### ISSUE TITLE
Shadowing outer "logging" in client.py

### ISSUE THREAD

**Issue by jhermann** [pycontribs/jira#755]
jira/client.py:342:86: W0621: Redefining name 'logging' from outer scope (line 23) (redefined-outer-name)

You're shadowing the logging module with a bool, leading to this:

    logging.error("invalid server_info: %s", si)
    AttributeError: 'bool' object has no attribute 'error'

I'd propose running pylint across the whole codebase.

Versions: Python 3.5.2, jira 2.0.0

**Comment by studioj** [comment]
Saw some fixes in here
https://github.com/pycontribs/jira/pull/1023
