### ISSUE TITLE
Need a way to match the migration process to accountID

### ISSUE THREAD

**Issue by tr1cks** [pycontribs/jira#770]
It can be achieved according to https://developer.atlassian.com/blog/2019/01/speed-up-your-jira-confluence-migrations-accountid/ by two ways:

1. Possibility to add header "x-atlassian-force-account-id: true" into each request.
2. Adding it to default headers.

**Comment by Plazmaz** [comment]
Quick workaround for this:
`jira._session.headers['x-atlassian-force-account-id'] = 'true'`

**Comment by ssbarnea** [comment]
@Plazmaz Make a PR to add this header to the library so we can see what happens.

**Comment by Plazmaz** [comment]
@ssbarnea Done. #772
