### ISSUE TITLE
find("filter/favourite") throws AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by mattmaniflaf** [pycontribs/jira#773]
I could not find a means of accessing a complete list of filters.

I know "filter/favourites" will return a list of filters, however when calling find() with this resource type an AttributeError is thrown, because a "list" object does not contain an "items" attribute.

"filter/favourite" REST call will return a list of favourite filters, however find() presumes all returned data is a dictionary, yet in this scenario it's a list.

Offending code is in resources.py:
326         def _parse_raw(self, raw):
327             self.raw = raw
328             if not raw:
329                 raise NotImplementedError("We cannot instantiate empty resources: %s" % raw)
330  ->         dict2resource(raw, self, self._options, self._session)

The call to dict2resource() resumes "raw" is a dictionary, where as in my scenario it's a list

Two questions arise :
 - Am I using the find() API call correctly ?
 - Is there another means of retrieving a list of filters, regardless of whether they are favourites or not ?

**Comment by mihaics3** [comment]
@mattmaniflaf the find defined https://github.com/pycontribs/jira/blob/master/jira/client.py#L731 refers to a resource on the server and not searching inside the filter list.

If you use a JIRA Server that supports v3 REST API you can use https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-api-3-filter-get to get all filters or https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-filter-search-get to search for specific filters.
