### ISSUE TITLE
update_filter() does not update favourite status

### ISSUE THREAD

**Issue by mattmaniflaf** [pycontribs/jira#774]
The favourite parameter to update_filter() API seems to be ignored.

I created a filter :
  (pdb) new_filt = create_filter(name="Myfilter", description="My New filter", jql="assignee in (MattMan)", favourite=False)
  (pdb) new_filt.favourite
  False

Attempt to change to True:
   (pdb) new_filt = update_filter("10001", favourite=True)
   (pdb) new_filt.favourite
    False

When I look at the filter in the UI it shows as not a favourite, and the only way to set as a favourite is to do so via UI.

**Comment by mihaics3** [comment]
@mattmaniflaf  I think that the problem is on JIRA side. I've tried calling the REST API's as in documentation using curl and it doesn't work. An interesting thing about the UI - the v1.0 REST API is used to set the favourite, not v2.

Note: the tests that I've made are against JIRA Server v7.4.4.
