### ISSUE TITLE
Unable to login to Jira using HTTP BASIC

### ISSUE THREAD

**Issue by KaterynaStreltsovaDevPro** [pycontribs/jira#775]
Cloud trial jira is used for  testing purposes, python 3.7:

        jira = JIRA('https://bugtesting1.atlassian.net')
        auth_jira = JIRA(basic_auth=('*******@dev-***.net', '******'))
        issue = jira.issue('TEST-1')

I tried to use email + password and email +Api token as the account has 2-step verification
(https://confluence.atlassian.com/cloud/api-tokens-938839638.html)

Got error:
WARNING:root:Got recoverable error from GET http://localhost:2990/jira/rest/api/2/serverInfo, will retry [3/3] in 6.62363911791183s. Err: HTTPConnectionPool(host='localhost', port=2990): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03AE5330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
WARNING:root:HTTPConnectionPool(host='localhost', port=2990): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03AE5D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) while doing GET http://localhost:2990/jira/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
Traceback (most recent call last):
  File "C:\Users\kateryna.streltsova\Documents\Automation-Utils\venv_auto_utils\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\kateryna.streltsova\Documents\Automation-Utils\venv_auto_utils\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\kateryna.streltsova\Documents\Automation-Utils\venv_auto_utils\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Version Information**
Python Interpreter: 3.7
jira-python: 2.0.0
OS:  Windows
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by gopar** [comment]
I've seen this pop up before. Make sure to use the email in which you registered for Jira and not any other one which you might be using. This might solve your problem.

**Comment by ykharabi** [comment]
I tried the suggested solution by gopar, but I still have the same error, any other hints 
br,
