### ISSUE TITLE
Can't connect to Jira Server instance using auth

### ISSUE THREAD

**Issue by msilverglate** [pycontribs/jira#779]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
Can't connect to my JIRA API(I am able to do so using CURL)

**To Reproduce**
from jira import JIRA
options = {
    'server': 'https://myJiraServer', 'verify': False, 'auth': ('username', 'password')}
jira = JIRA(options)

issue = jira.issue('SSD_KB-949')
1. Any additional steps or considerations that happen before or after.

**Expected behavior**
Able to connect
**Stack Trace**
```
	text: You do not have the permission to see the specified issue.
	
	response headers = {'X-AREQUESTID': '1098x898422x1', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-ASEN': 'SEN-13433261', 'X-AUSERNAME': 'anonymous', 'Cache-Control': 'no-cache, no-store, no-transform', 'WWW-Authenticate': 'OAuth realm="_myrealm_"', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 15 Apr 2019 22:18:19 GMT'}
	response text = {"errorMessages":["You do not have the permission to see the specified issue.","Login Required"],"errors":{}}
```

**Version Information**
Python Interpreter: <VERSION>PyCharm
jira-python: <VERSION> 3.7
OS: <OPERATING SYSTEM> Windows
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by alexa-ai** [comment]
Documentation indicates to use "basic_auth" instead of "auth". I get "text: Issue does not exist or you do not have permission to see it" error message irrespective of "auth" or "basic_auth"

**Comment by caerwyn** [comment]
I'm using 
        self.hosted_jira = JIRA( server='https://jira.atlassian.com/', basic_auth=(jira_user, jira_api_token) )

where I was using username/password before.
It works like that for me.

thanks for the suggestions.

**Comment by msilverglate** [comment]
I was able to connect using JIRA(options, basic_auth= 'username', 'password').
I had been including the options (server url and verify=false) directly rather than in an options dictionary variable.  We are using a local server instance hence jira_api_token is not an option.  I think it would be useful to include an example like this in the documentation. It was only upon rereading section 6.1 at https://jira.readthedocs.io/en/master/api.html that I understood how the parameters needed to be constructed.

**Comment by alexa-ai** [comment]
Thanks @caerwyn . I was able to connect using api token. 

@msilverglate : I tried password option. It did not work. Maybe because I use JIRA Cloud. Not sure if I must use api token for cloud instances.

**Comment by Windynik** [comment]
@caerwyn Thank you soo much! you saved me a whole day of time.

**Comment by prajwal-c1** [comment]
I tried all the above but , None works can anyone help.
'server':'https:/myname.atlassian.net
