### ISSUE TITLE
Provide specific instructions for development setup

### ISSUE THREAD

**Issue by guymatz** [pycontribs/jira#788]
**Is your feature request related to a problem? Please describe.**
I don't know how to best setup an environment in order to be able to contribute to the jira library.   Some specific instructions for getting the codebase for development would be appreciated.  Or maybe a link to how best to go about this?  For example, do I just 'git clone'?  The something with 'python setup.py'?  I've heard about 'pip install -e' but I don't know how to use and google searches don't turn up much . . .

**Describe the solution you'd like**
I would like specific instructions for contributing added to the "setup" portion of projects Readme

**Describe alternatives you've considered**
I've tried googling this and asking everyone I know but have turned up nothing

**Additional context**
N/A

**Comment by asqui** [comment]
+1

Also, previously discussed in #133
