### ISSUE TITLE
You must specify a valid project lead

### ISSUE THREAD

**Issue by unformatt** [pycontribs/jira#791]
**Describe the bug**
Started getting this error recently when creating a project. I get this error during a unit test in which no code has changed on my end. I'm using v2.0.0 of this jira library and I also tried with `master` branch code.

**To Reproduce**

```python
from jira import JIRA
api = JIRA(url, basic_auth=(user, passw))
new_project = api.create_project(
            key='PROJ',
            name='My New Project',
            template_name='Scrum software development'
        )
```

**Expected behavior**
`create_project` should return new project object

**Stack Trace**
```
Traceback (most recent call last):
  File "env/lib/python2.7/site-packages/jira/client.py", line 3484, in create_project
    r = self._session.post(url, data=payload, headers=headers)
  File "env/lib/python2.7/site-packages/jira/resilientsession.py", line 154, in post
    return self.__verb('POST', url, **kwargs)
  File "env/lib/python2.7/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "env/lib/python2.7/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
JIRAError: JiraError HTTP 400 url: https://boardgenius.atlassian.net/rest/project-templates/latest/templates
    text: You must specify a valid project lead.

    response headers = {'X-AREQUESTID': 'bc3b5749-0224-4007-ab26-a9074bef1a16', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Transfer-Encoding': 'chunked', 'X-AACCOUNTID': 'xxx', 'X-Seraph-LoginReason': 'OK', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'ATL-TraceId': '75561a26377ea413', 'Server': 'AtlassianProxy/1.13.6.2', 'Connection': 'close', 'Cache-Control': 'no-cache, no-store, no-transform', 'Date': 'Wed, 15 May 2019 14:30:47 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Timing-Allow-Origin': '*'}
    response text = {"errorMessages":[],"errors":{"projectLead":"You must specify a valid project lead."}}
```

**Version Information**
Python Interpreter: 2.7.15
jira-python: 2.0.0 & master branch
OS: macOS & Linux
Other Dependencies: n/a

**Additional context**
n/a

**Comment by unformatt** [comment]
When jira lib fills in lead's username via `current_user`,  it's passing the lead user's email address rather than the username. 

https://github.com/pycontribs/jira/blob/master/jira/client.py#L3446

If I pass username it works. Still investigating whether:

1) Jira API used to allow the email address and has changed their API.
2) `current_user` method was returning username but is no longer because of change in Jira API.

I'm using basic auth and recently got an email from Atlassian saying they are phasing it out. Not sure if this is a side effect.

**Comment by unformatt** [comment]
In `JIRA`, `self._serverInfo['username']` is None. I'm using basic auth and recently got an email from Atlassian saying they are phasing it out. Not sure if this is a side effect. Still investigating...

**Comment by unformatt** [comment]
If we could search users by `accountId`, we could get the missing username. But it seems the `User` resource is hardcoded to only search by `username`

```python
class User(Resource):
    """A JIRA user."""

    def __init__(self, options, session, raw=None):
        Resource.__init__(self, 'user?username={0}', options, session)
        if raw:
            self._parse_raw(raw)
```

**Comment by ssbarnea** [comment]
Closing as I am unable to reproduce with code in master.
