### ISSUE TITLE
allow to perform transitions using their names instead of id

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jira#8]
transition_issue requires the transition id, but we should allow people to use their names even if Atlassian API does not allow this (we can convert the name to ID inside our library).

**Comment by fabio-silva-movile** [comment]
Hi Sorin, are you working on this? Can I contribute to develop this improvement?

**Comment by sargentstudley** [comment]
For what its worth, i am looking at this too. Maybe we can all collaborate?

**Comment by ssbarnea** [comment]
You are more than welcome to do so!

/sorin

**Comment by fabio-silva-movile** [comment]
Change purposed on https://github.com/pycontribs/jira/pull/35

**Comment by ssbarnea** [comment]
v0.40 solved this.
