### ISSUE TITLE
Fetching a jira user by username is deprecated

### ISSUE THREAD

**Issue by NiCalderon** [pycontribs/jira#802]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
As per [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/#examples), this is not supported anymore.

In class User, in the constructor, the parent class is initizalized with a [`user?username={0}`](https://github.com/pycontribs/jira/blob/master/jira/resources.py#L839) resource.

One of our script used to access `issue.fields.reporter.emailAddress`, but after switching to OAUTH (not sure if coincidence due to similar deprecation timeline or an actual trigger), we started getting traceback [here](https://github.com/pycontribs/jira/blob/master/jira/resources.py#L188) (don't have the logs on hand, will try to add later).

**To Reproduce**
```
jira = JIRA(...)
jira.issue('<id>').fields.reporter.emailAddress
```
1. Might be related to our enabling of OAUTH

**Expected behavior**
The User Resource should be loaded and its properties available.

**Stack Trace**
```
Someting that boils down to reporter being non subscriptable, will update when I get the actual message
```

**Version Information**
Python Interpreter: 3.6
jira-python: ?, but analysed master code statically, will update when I reproduce on master
OS: Ubuntu 19.04
Other Dependencies:
Jira with deprecated `username` parameter on various operations.

**Additional context**
Despite those being deprecated, username and userKey are still being returned. It appears Atlassian's deadlines are somewhat relaxed.

**Comment by auxsvr** [comment]
This looks similar to https://github.com/pycontribs/jira/issues/697.
