### ISSUE TITLE
maxResults seems to be locked on 100

### ISSUE THREAD

**Issue by hcpeter** [pycontribs/jira#805]
Hi,

First of all - thank you for this fantastic tool! 

I'm currently using version 2.0.0 with Jira Cloud. My primary use case is to open a jirashell and do quick and dirty info scraping, mainly with the help of `search_issues`. When I double checked the results (running the same JQL in the Jira) I noticed that in jirashell I always get back maximum 100 results - even if I specify the `maxResults` parameter. According to Jira, I should have 288 results. Am I missing something (maybe pagination?) More interestingly, the `total` is correct.

**To Reproduce**
Run any query with search_issue which will give back more than 100 results
```
issues = jira.search_issues('jql....', maxResults = 332)
len(issues) #100 
issues.total #288
```

**Expected behavior**
The ResultList should contain all the issues.

**Version Information**
Python Interpreter: python 3.7.3
jira-python: 2.0.0
OS: macOS Mojave
IPython (Optional): 7.5.0

I'd appreciate any help!
Best regards,
Peter

**Comment by dnagl** [comment]
I found an issue Jira where this problem is discussed. [Jira Issue](https://jira.atlassian.com/browse/JRACLOUD-67570)  
Maybe this can help you out.

**Comment by asmaier** [comment]
Won't fix? That is unfortunate. I would expect a client to do the necessary pagination handling for me.

**Comment by egeland** [comment]
Try with `maxResults=False`, should give you more than 100...

**Comment by hcpeter** [comment]
I'm closing this issue because `maxResults=False` working fine for me. Thanks, @egeland for the tip!
