### ISSUE TITLE
Exception on self._resource format with Board.find(id)

### ISSUE THREAD

**Issue by steveteske** [pycontribs/jira#810]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
A KeyError exception occurs when calling Board.find(id) on a valid board id.  Issues and sprints queries work fine. Only the board query fails.

**To Reproduce**

1. Create a JIRA server with valid base_url
2. Retrieve a list of boards
3. Using a value board id, call find on the board instance with the valid board id.

```
        def test_board_query_with_parameters(self):
            server = JIRA(server='https://my.url.removed.com',
                          basic_auth=[user, password],
                          options={'agile_rest_path': 'agile'})

            boards = server.boards(name="My Scrum Board")
            agile_board = boards[0]
            issues = agile_board.find(sprint_board.id)
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**
The board.find() method should return a list of issues found on the board.

**Stack Trace**
```
Error
Traceback (most recent call last):
  File "/opt/python-3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python-3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/user/src/mgv_stats/tests/mgv_stats/test_jira_library_capabilities.py", line 62, in test_board_query_with_parameters
    issues = sprint_board.find(sprint_board.id)
  File "/home/user/src/mgv_stats/ve/lib/python3.6/site-packages/jira/resources.py", line 199, in find
    path = self._resource.format(id)
KeyError: 'id'
```

**Version Information**
Python Interpreter: Python 3.6.2
jira-python: <VERSION>
OS: Linux 3.10.0-957.12.2.el7.x86_64 
IPython (Optional): <VERSION>
Other Dependencies:
None

**Additional context**

I think I found the offending lines of code.

The `self._resource` variable is set in the constructor to `board/{id}` as shown below in resource.py

```
class Board(GreenHopperResource):
    """A GreenHopper board."""

    def __init__(self, options, session, raw=None):
        path = 'rapidview/{0}' if options['agile_rest_path'] == self.GREENHOPPER_REST_PATH else 'board/{id}'
        GreenHopperResource.__init__(self, path, options, session, raw)

```
Path is passed to GreenHopperResource and then to Resource which ultimately sent the self._resource variable.
```
class GreenHopperResource(Resource):
    ...
    def __init__(self, path, options, session, raw):
        self.self = None
        Resource.__init__(self, path, options, session, self.AGILE_BASE_URL)
        ...
```
```
class Resource(object):
   ...
    def __init__(self, resource, options, session, base_url=JIRA_BASE_URL):
        self._resource = resource
        self._options = options
        self._session = session
        self._base_url = base_url
        ...
```

Then in `class Resource` the following code breaks because the `format` command is looking for a named parameter called `id`. 

```
    def find(self, id, params=None):

        if params is None:
            params = {}

        if isinstance(id, tuple):
            path = self._resource.format(*id)
        else:
            path = self._resource.format(id)
        url = self._get_url(path)
        self._load(url, params=params)
```

There are two options to fix this.

1.  change the constructor and replace `board{id}` with `board{0}`
2.  change the find method to use `path = self._resource.format(id=*id)` for the tuple case and `path = self._resource.format(id=ed` for non-tuple case.

I'd like to make this change and submit.  Can I do that.  Expeditiously?

Here is a setup of test cases  that provide evidence of my findings.

```
import unittest


class TestFormatFailure(unittest.TestCase):

    def test_format_parameter_working(self):
        resource = 'board/{0}'

        def find(id):
            return resource.format(id)

        find(22)

    def test_format_parameter_working_internal_named_parameter(self):
        resource = 'board/{id}'

        def find(id):
            return resource.format(id=id)

        find(22)

    @unittest.expectedFailure
    def test_format_parameter_failing(self):
        resource = 'board/{id}'

        def find(id):
            return resource.format(id)

        find(22)

    @unittest.expectedFailure
    def test_format_parameter_failing_named_parameter(self):
        resource = 'board/{id}'

        def find(id):
            return resource.format(id)

        find(id='24')
```

**Comment by jfboismenu** [comment]
Hi, I'm not sure you should be able to find the issues on the board that easily.

The JIRA test API expects you to hit the endpoint `/rest/agile/board/<board-id>/issue` in order to retrieve the list of issues. I've actually [implemented](https://github.com/pycontribs/jira/pull/834) this today and submitted a PR for it.

**Comment by steveteske** [comment]
In a sandbox environment, I modified the code by replacing `id` with `0` in this line of code...
`        path = 'rapidview/{0}' if options['agile_rest_path'] == self.GREENHOPPER_REST_PATH else 'board/{id}'
`
and find works.

-Steve
