### ISSUE TITLE
Can't get worklogged user's email

### ISSUE THREAD

**Issue by dulajsan** [pycontribs/jira#811]
When I print the attributes of the worklog object I found these methods and attributes.

**SE_URL', '_READABLE_IDS', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__',
'__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_base_url', '_default_headers', '_get_url', '_load', '_options', '_parse_raw', '_resource', '_session', 'author', 'created', 'delete',
'find', 'id', 'issueId', 'raw', 'self', 'started', 'timeSpent', 'timeSpentSeconds', 'update', 'updateAuthor', 'updated']**

Since I wanted to get the worklogged user's email, here I accessed the author attribute. But for some worklogs it returns the full name of the user, for some worklogs, it returns the email. that full name is not unique for users as well.

**My code Block:**

```
 worklogs = jira.worklogs(issue.key)
        for worklog in worklogs:
            print(worklog.author)
            print(dir(worklog))

```

Expected result for author attribute is unique something for user. It will be better i can access the email. But there is no attribute called email in the worklog object.

**Version Information**
Python Interpreter: 3.6.8
jira-python: 2.0.0
OS:  windows 10

**Comment by ssbarnea** [comment]
This is no longer supported from serverside due to privacy regulations.
