### ISSUE TITLE
Unused parameter `type` in create_project method

### ISSUE THREAD

**Issue by rs-ds** [pycontribs/jira#823]
The argument `type` in the `create_project` method is not used anywhere: https://github.com/pycontribs/jira/blob/87413c87b27ff75a0e6e454c1482ff05fd86aeaf/jira/client.py#L3405

I also believe that 
```
project_type_key = templates[template_name]['projectTypeKey']
```

should be replaced with 

```
project_type_key = type if type else templates[template_name]['projectTypeKey']
```

Please let me know if this is the right change to make and I will send a PR.

**Comment by ssbarnea** [comment]
Fixed in master
