### ISSUE TITLE
List copy() method not supported in Python 2.7

### ISSUE THREAD

**Issue by cameronshinn** [pycontribs/jira#826]
**Description**
The latest release doesn't fully support Python 2.7 because there is a line of code that attempts to use the list copy method that [wasn't added until Python 3.3](https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types). This issue was fixed in [this commit](https://github.com/pycontribs/jira/commit/701882cb7284a629105c400d230b810d2f5ed962#diff-12827fc5aab7f1c957381e453bdfe85a), but isn't in a stable release yet, so Python 2.7 users on 2.0.0 will get this error still.

**To Reproduce**
```
any_list = ["bug", "issue", "fix"]
jira_obj.search_issues("a jql string", fields=any_list) # Passing a list into fields throws error
```

**Expected behavior**
Should support queries using a list as the field argument without throwing an error.

**Stack Trace**
```
File "C:\Python27\lib\site-packages\jira\client.py", line 2084, in search_issues
    fields = fields.copy()
AttributeError: 'list' object has no attribute 'copy' 
```

**Version Information**
Python Interpreter: 2.7
jira-python: 2.0.0
OS: Windows 10

**Comment by ssbarnea** [comment]
Support for python 2.7 was dropped.

**Comment by con-f-use** [comment]
What was the last version, that supported python 2?
