### ISSUE TITLE
Speedup Handshake

### ISSUE THREAD

**Issue by philippmayrth** [pycontribs/jira#84]
Hi *,

This tool is a smart way to get my work done FAST, thanks to the developers.

I´m using this module in combination with CG, so the handshake is invoked every time, this costs 15 sec for every invocation and I use the scripts a lot.

Do you have any suggestion how I could avoid always doing the handshake or just speed that up a bit (I cat use OAuth so I use PW). I already thought about something like shared memory but as I often run multiple scripts at the same time I don't think thats such a great idea and just makes the code more difficult to read.

Thanks for your response

**Comment by ssbarnea** [comment]
Yes, just use basic authentication and HTTPS, this would be faster and as safe as it can be. Few calls do even support async operations.
