### ISSUE TITLE
Add support for new createmeta endpoints

### ISSUE THREAD

**Issue by klopacinski-atlassian** [pycontribs/jira#840]
Hi,
Jira versions starting with 8.4.0 have new createmeta REST endpoints, described in the following documents:

[https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html](https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html)
[https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples)

The old createmeta endpoints have been deprecated and are scheduled for removal in the next platform release (i.e. Jira 9.0). They can also be disabled by the Jira instance's administrator starting with 8.4.0.

**Comment by mew1033** [comment]
It appears that support for the new createmeta endpoints is still missing. Will this be added before Jira 9 is released?

**Comment by dragonmoose** [comment]
Hi!

Is this anything that is being looked into? We'll need to make sure this works before updating to Jira 9, or else we'll have to use the REST API directly.

All the best,
Elias
