### ISSUE TITLE
Issue instance is not hashable

### ISSUE THREAD

**Issue by regisz** [pycontribs/jira#842]
Description: Issue instance is not hashable

Python Interpreter: 3.5.6
jira-python: 2.0.0
OS: Debian GNU/Linux 9.9 (stretch)

Steps To Reproduce:
    1. jira_server = JIRA(server = "...", basic_auth = ("...", "..."))
    2. issue = jira_server.issue("REL-111")
    3. hash(issue)

Stack Trace:
    TypeError: unhashable type: 'Issue'

So, the __hash__ method is missing from Issue class.

**Comment by renogen** [comment]
I have the same problem. 

If you don't fix it, can you point me to a way to repair it for myself?

Thanks!
