### ISSUE TITLE
from jira import JIRA

### ISSUE THREAD

**Issue by stuntpants** [pycontribs/jira#847]
Using with python2 on a linux os
when i run the script i get the below error
File "nessus2jira.py", line 12 in <module>
from jira import JIRA

I have a jira folder however within this folder there is no JIRA file to call on.

any help would be great

Mike

**Comment by hdost** [comment]
I would rename of otherwise remove the jira folder since it is likely conflicting with the installed API.

**Comment by stossy** [comment]
@stuntpants I had a similar problem.

The v2.0.0 package is broken - https://pypi.org/project/jira/

Use one of the release candidates, I switched to:
https://pypi.org/project/jira/3.0a2/

if you look in your virtualenv/app/lib/python3.x/site-packages/jira/
pip never installs the correct code, init is blank

in requirements.txt, do:
`jira==3.0a2`
