### ISSUE TITLE
Update issue without fetching it

### ISSUE THREAD

**Issue by patrikturi** [pycontribs/jira#868]
I want to update the fields of an issue but I don't want to fetch the issue data from the server because I already have it from a webhook. Is this possible?

eg. instead of:
```issue.update(fields={'customfield_1111': 2})```

call something like:
```jira.update_issue('PROJ-123', fields={'customfield_1111': 2})```

**Comment by JasonKempSEL** [comment]
The way I have done this in the past is to manually create an Issue object:

```python
from jira.resources import Issue

issue_obj = Issue(jira_obj._options, jira_obj._session, raw=issue_json_from_webhook)
issue_obj.update(fields)
```

**Comment by patrikturi** [comment]
Thanks, that does it for me.
