### ISSUE TITLE
Bump release to something later than 2.0.0

### ISSUE THREAD

**Issue by lan17** [pycontribs/jira#876]
**Is your feature request related to a problem? Please describe.**
I started using 2.0.0 but I found it has a bunch of issues that seem to be fixed in 3+ versions.  An example is not retrying `401` responses.  

2.0.0, however, is currently a blessed release, but its rather old. 

**Describe the solution you'd like**
Publish something close to the latest on master as a blessed stable release in PyPi.

**Describe alternatives you've considered**
I could use a forked version or force to use 3+ version, but that is still bound to confuse new people as the default when `pip install jira` is 2.0.0

**Comment by tucked** [comment]
I was just about to +1 this, but I quickly double-checked on PyPI and found that 3.0.1 was released ~1hr ago! 🎉
