### ISSUE TITLE
cannot update field:label

### ISSUE THREAD

**Issue by treewolf** [pycontribs/jira#889]
I looked at past issues, I haven't found any fix.
I want to edit a label on an issue.

`issue.update(fields={'labels':['test']})`

## What I expect:
The label is edited and is result is shown.

## What happens:
Recieve a **http.response 400** and message **Field 'labels' cannot be set. It is not on the appropriate screen, or unknown.**

I have permissions to edit the label. When editing  any other field, eg Description, the update is made and everything is golden.

**Comment by JasonKempSEL** [comment]
@treewolf , ensure that you have Labels on the edit screen for the issue. Labels are editable in the web interface regardless of if they're on the edit screen or not, but they must be in the screen to edit it in the API.

**Comment by treewolf** [comment]
@JasonKempSEL thank you for replying. yes, the labels are on the screen:
![Screen Shot 2020-01-09 at 14 17 47](https://user-images.githubusercontent.com/12214656/72109595-0de47200-32eb-11ea-9702-3ec6aa067957.png)

**Comment by treewolf** [comment]
Update: I think I am a little confused on the "screens" part. The flow to edit a label for me, on web gui, is:
`click edit crayon icon -> goes to an edit page -> enter and save -> goes back.`

So am i correct in saying that if i was using REST api, i would need the link to the "goes to an edit page" step?

I am using python api, so how would i be able to differentiate pages based off the method?

**Comment by JasonKempSEL** [comment]
The image you posted is of the web view of the issue--not the actual screen definitions. Like I said, Labels are there and always editable even if they aren't on the screen. The edit pencil being always visible is a sign that labels is not actually on the edit screen for the issue type. (I don't know why this is; just a weird quirk)

Your second view is of the python API, which wraps the REST API. That is this library and not actually part of Jira. **Your original Python call is correct**, and will work once the screen in Jira is configured correctly.

You'll have to get one of your Jira Admins to check the Screen Scheme for that issue type. Ensure that Labels are on the screen associated with the Edit operation for that issue type:

https://confluence.atlassian.com/adminjiraserver/project-screens-schemes-and-fields-938847220.html
https://confluence.atlassian.com/adminjiraserver/associating-a-screen-with-an-issue-operation-938847289.html
https://confluence.atlassian.com/adminjiraserver/defining-a-screen-938847288.html

**Comment by treewolf** [comment]
Thanks for posting the links, I understand the issue now.
@JasonKempSEL Thank you for being very helpful!

**Comment by treewolf** [comment]
Solution: Admin configs
