### ISSUE TITLE
assign_issue does not work when in strict GDPR mode

### ISSUE THREAD

**Issue by csullivannet** [pycontribs/jira#903]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
Our Jira is in strict GDPR mode and only supports querying users by `accountId`. The [`_get_user_accountid`](https://github.com/pycontribs/jira/blob/5c27f6ddafffc6110be1db4749fa67025852bcb6/jira/client.py#L1562) function fails in this instance.

**To Reproduce**
```
  issue = jira.create_issue(fields=issue_dict)
  assignee = 'my-user'
  jira.assign_issue(issue, assignee)
  assign(issue, assignee)
```
1. Further, we determine who to assign to dynamically. As the username is no longer returned by the API, we are not able to give [`assign_issue`](https://github.com/pycontribs/jira/blob/5c27f6ddafffc6110be1db4749fa67025852bcb6/jira/client.py#L1572) the username.

**Expected behavior**
To be able to pass the `accountId` directly to [`assign_issue`](https://github.com/pycontribs/jira/blob/5c27f6ddafffc6110be1db4749fa67025852bcb6/jira/client.py#L1572).

**Stack Trace**
```
(jira-tool)csullivan@cs-x1[±|master {1} U:2 ✗]:~/jira-tool $ ./jira-tool.py 
Traceback (most recent call last):
  File "./jira-tool.py", line 284, in <module>
    main()
  File "./jira-tool.py", line 271, in main
    ticket = jira.open(my_int, 'csullivan', my_float)
  File "/home/csullivan/jira-tool/api/jira.py", line 55, in open
    jira.assign_issue(issue, assignee)
  File "/home/csullivan/.pyenv/jira/lib/python3.7/site-packages/jira/client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
  File "/home/csullivan/.pyenv/jira/lib/python3.7/site-packages/jira/client.py", line 1311, in assign_issue
    url, data=json.dumps(payload))
  File "/home/csullivan/.pyenv/jira/lib/python3.7/site-packages/jira/resilientsession.py", line 157, in put
    return self.__verb('PUT', url, **kwargs)
  File "/home/csullivan/.pyenv/jira/lib/python3.7/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/csullivan/.pyenv/jira/lib/python3.7/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://mycompany.atlassian.net/rest/api/latest/issue/ISSUE-8888/assignee
	text: 'accountId' must be the only user identifying query parameter in GDPR strict mode.
	
	response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Tue, 18 Feb 2020 17:15:11 GMT', 'ATL-TraceId': 'atltraceid', 'X-AACCOUNTID': 'xaacountid', 'X-AREQUESTID': 'xarequestid', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'Timing-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Connection': 'close'}
	response text = {"errorMessages":["'accountId' must be the only user identifying query parameter in GDPR strict mode."],"errors":{}}
```

**Version Information**
Python Interpreter: 3.7.5
jira-python: `master`
OS: Fedora29
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by csullivannet** [comment]
I've proposed a fix via this PR: https://github.com/pycontribs/jira/pull/904

**Comment by vlad-gursky** [comment]
@csullivannet 
Where in Jira web console can we check switch of  "strict GDPR" ? Is it option or hardcoded by Atlassian in Jira for all?

"...
Our Jira is in strict GDPR mode..."

**Comment by cdaniluk** [comment]
Is there some reason why the PR associated with this issue isn't merged? Atlassian deprecated username in Jira Cloud over 2 years ago. I see the build is failing on that PR, but the build is also failing on master for reasons that seem unrelated.

**Comment by bhanuchandra217** [comment]
Hi Team,

jiraAssignIssue idOrKey: 'TEST-2', site: 'jira', userName: 'banuchandra'
am getting the below error for the above code can someone pls explain this
Error Message: {"errorMessages":["'accountId' must be the only user identifying query parameter in GDPR strict mode."],"errors":{}}

**Comment by adehad** [comment]
@bhanuchandra217 please raise a new issue following the template

**Comment by bhanuchandra217** [comment]
have tried multiple times with multiple issues but still getting the same error

**Comment by adehad** [comment]
@bhanuchandra217 I mean, can you use the GitHub Issue reporting system to make a new report of the issue: https://github.com/pycontribs/jira/issues/new/choose
