### ISSUE TITLE
Invalid username or password recursively retries and locks Jira account

### ISSUE THREAD

**Issue by treewolf** [pycontribs/jira#923]
When a username or password is incorrect, the request will be tried 3 times, and only throw an exception after the third time, which would then lock the account. Is there a way to catch the very first 401 error?

```python3
try:
  jira = JIRA(options=self.jira_options[server_type], basic_auth=(
    self.jira_creds[server_type]['user'], self.jira_creds[server_type]['password']))
  return jira
except:
  print('Incorrect username or password')
```

output
```
WARNING:root:Got recoverable error from GET <domain>, will retry [1/3] in 13.579639837287738s. Err: 401 
WARNING:root:Got recoverable error from GET <domain> will retry [2/3] in 34.4860722264685s. Err: 401 
^C
```

 Expected output:

```
'Incorrect username or password'
```

**Comment by umanamente** [comment]
Use `max_retries` argument:
`jira = JIRA(..., max_retries=0)`

**Comment by treewolf** [comment]
@umanamente  This worked, Thank you. I re-checked the documentation 

`class jira.JIRA(server=None, options=None, basic_auth=None, oauth=None, jwt=None, kerberos=False, kerberos_options=None, validate=False, get_server_info=True, async_=False, async_workers=5, logging=True, max_retries=3, proxies=None, timeout=None, auth=None)`

and i realized it was already there, i think it just went over my head. Thanks again!
