### ISSUE TITLE
Handle 429 rate limiting messages from Jira

### ISSUE THREAD

**Issue by jmunson** [pycontribs/jira#925]
**Is your feature request related to a problem? Please describe.**
 Atlassian recommends usage of rate limiting with Jira in this blog post: https://confluence.atlassian.com/adminjiraserver/improving-instance-stability-with-rate-limiting-983794911.html

This would result in getting a 429 status code.  [From what I can tell](https://github.com/pycontribs/jira/blob/91461fd736cd9a37cc136e07402c6f0b1e60170b/jira/resilientsession.py#L100) this library will never retry these requests.

**Describe the solution you'd like**
Use the existing exponential backoff logic to (eventually) retry a request that was ratelimited.

**Describe alternatives you've considered**
I have not really considered any alternative here. 

**Additional context**

Admittedly this may be handled elsewhere and I may have missed it,  I have not rolled out the ratelimiting yet so I do not have real world testing here.

**Comment by Royxia319** [comment]
could you share detail code for how you handle this? I want to test it.

**Comment by malaskow** [comment]
hi, any news with that?

**Comment by StefanoBoriero** [comment]
Hello, I'd be interested in this as well so I tried to contribute with a PR: happy for it be reviewed!
