### ISSUE TITLE
create issue failed

### ISSUE THREAD

**Issue by Helloyanxuan** [pycontribs/jira#934]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**

def create_issue():
    issue_dict = {
        'project': {'id': 10000},
        'summary': 'New issue from jira-python',
        'description': 'Look into this one',
        'issuetype': {'name': 'Bug'},
    }
    issues = jac.create_issue(fields=issue_dict)

jira.exceptions.JIRAError: JiraError HTTP 400 url: http://193.112.176.130:8000/rest/api/2/issue
	text: valid issue type is required
	
	response headers = {'X-AREQUESTID': '855x414x1', 'X-ASESSIONID': '10pyb79', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-ASEN': 'SEN-L15365559', 'X-Seraph-LoginReason': 'OK', 'X-AUSERNAME': 'franky', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Tue, 28 Apr 2020 06:15:47 GMT', 'Connection': 'close'}
	response text = {"errorMessages":[],"errors":{"issuetype":"valid issue type is required"}}

**To Reproduce**
```
Code block
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**

**Stack Trace**
```
A code block with the any trace messages.
```

**Version Information**
Python Interpreter: <VERSION>
jira-python: <VERSION>
OS: <OPERATING SYSTEM>
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by tonyfud** [comment]
I also have the same problem, how to solve it

**Comment by tonyfud** [comment]
https://community.atlassian.com/t5/Jira-Software-questions/quot-issuetype-quot-quot-issue-type-is-required-quot-on-rest-API/qaq-p/1208804
