### ISSUE TITLE
jira Person fields is returning UnknownResource

### ISSUE THREAD

**Issue by davibaldin** [pycontribs/jira#939]
Project resource with lead JIRA UnknownResource

My working code is returning UnknownResource from assignee and lead fields datatype. 

obj.lead = <JIRA UnknownResource: displayName='Davi Doe'>

Code:
 jp = self.getJira().project('KEY')
print (jp.lead.key)
...

**Version Information**
Python Interpreter: 3.6
jira-python: 2.0.0
OS: Linux

**Comment by randchange** [comment]
I believe that Jira has has deprecated the username and user key fields to provide GDPR compliant services.  This quote is from their REST API migration guide:

> Changes to how users are identified: Personal data that is used to identify users, such as the username and userKey, will be removed from the REST APIs. Users will be identified by their Atlassian account ID (accountId) instead.

I have prototyped a change that seems to work by adding the resource_class_map in resources.py the following code:

`r'user\?accountId.+$': User,`

In my case, I left the old resource reference for User and just added the new one although I suspect the old one can be removed as no longer needed.

**Comment by randchange** [comment]
After checking out the master branch, there is a fix already there in the 2.0.1.rc1 release, but which has not yet been formally released. I am not sure of the maintainer's release schedule.

**Comment by studioj** [comment]
@davibaldin @randchange care to check if version 3.0.1 fixes your problem?

if using jira server please take this issue into account #1035
