### ISSUE TITLE
how to set multiple options when intializing jira.JIRA object

### ISSUE THREAD

**Issue by bvccaneer** [pycontribs/jira#94]
Hi,

on our JIRA we have a plugin that can be accessed by REST API.
the difference in the "call" is the JIRA_BASE_URL
so e.g. instead of https://{my_jira_server}/rest/api/2/{issue_id}
I need to call https://{my_jira_server}/rest/{something_different_than_api}/1.0/{issue_key}

how to access issue through such REST API?

I've tried following without success:
    from jira import JIRA
    
    access_jira = JIRA("https://{my_jira_server}", basic_auth=({user}, {password}), options={'rest_path':u'something_different_than_api', 'rest_api_version':u'1.0'})

unfortunately only one of the options is set and second parameter is not taken into account.
e.g. 404 is returned with following url called:

    jira.utils.JIRAError: JiraError HTTP 404
	    text: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: {my_jira_server}/rest/api/1.0/serverInfo</message></status>
	    url: https://{my_jira_server}/rest/api/1.0/serverInfo

or if I leave rest_api_version set to "2" then:
    jira.utils.JIRAError: JiraError HTTP 404
        <title>Oops, you&#39;ve found a dead link. - JIRA</title>
        url: https:/{my_jira_server}/rest/{something_different_than_api}/2/{issue_key}

how to make this things to work?

Thanks in advance,
bvccaneer

**Comment by ssbarnea** [comment]
Please read the documentation at http://jira.readthedocs.org/en/latest/ and you will see that all the options can be specified inside the options dictionary. 
Also, never put the credentials in the code, just put them inside the `~/.netrc` file. I am even considering putting a warning when someone is using these options or dropping this.
