### ISSUE TITLE
[question] Possible to create project-versions?

### ISSUE THREAD

**Issue by simkin** [pycontribs/jira#947]
Could someone advise if it is possible to create project versions with this module? Reason I ask is that when I create a new issue this sometimes fails because the version(s) do not (yet) exists in the project. I hope to build in an exception catcher that creates the version in these cases.

e.g. i hope that I can loop through versions/fixVersions and get them created in a target project
```
    new = jira.create_issue(project=project,
                            issuetype={'name': 'Bug'},
                            summary=parent.fields.summary,
                            versions=[{'name': v.name} for v in parent.fields.versions],
                            fixVersions=[{'name': v.name} for v in parent.fields.fixVersions],
                            components=[{'name': 'unknown'}],
                            reporter={'name': parent.fields.reporter.name},
                            priority={'id': bug_prio},
                            description=parent.fields.description)
```

Edit: see https://jira.readthedocs.io/en/master/api.html?highlight=create_version#jira.JIRA.create_version

**Comment by JasonKempSEL** [comment]
Yes, you'll want to look at the `create_version` method. Do be aware the user you've logged in with needs project admin to create versions.
