### ISSUE TITLE
How to create/change user on ci JIRA

### ISSUE THREAD

**Issue by fender4645** [pycontribs/jira#95]
I've added a new method (jira.modify_user) and I'm trying to write some tests for it in tests.py. It looks like I can't modify a user as I get the following error:

    JIRAError: JiraError HTTP 400
	    text: This user can not be renamed because that operation is unsupported by the underlying user directory or JIRA is acting as a Crowd Server.

Is there any way I can create a local user that can be modified on the ci instance?

**Comment by ssbarnea** [comment]
I guess you are referring to the hosted JIRA (Cloud) that we are using for testing so I guess that's not supported.
