### ISSUE TITLE
Setting timeout parameter has no effect

### ISSUE THREAD

**Issue by JiKook31** [pycontribs/jira#950]
**Describe the bug**
I tried to set timeout parameter in Jira variable, but nothing has changed. 

**To Reproduce**
```
jira = JIRA(timeout=6000)
```
When you run the code and some error rises up, the number of seconds for retrying is always random and is not what was set in the parameter.

**Expected behavior**
In case of error it should output something like this:
WARNING:root:Got recoverable error from GET https://jira-server/rest/api/2/serverInfo, will retry [1/3] in 6s. Err: 401 
Maybe I misunderstood this parameter and it controls something else? Any help would be appreciated.

**Version Information**
Python Interpreter: 3.7
jira-python: 2.0.0
OS: MacOS

**Comment by victorbordo** [comment]
Experiencing this issue too. 

**Version Information**
Python Interpreter: 3.8.4
jira-python: 2.0.0
OS: macOS Catalina 10.15.4

**Comment by adehad** [comment]
I think this is a misunderstanding of the parameter.

You are observing the exponential back-off during retries, which is what happens after a timeout. The timeout parameter is applied per request to the API.

e.g.
1. Request send to Jira API, waits `timeout`
2. `timeout` waited, but no response - returned a timeout exception - e.g. HTTP 408
3. The package retries the request (i.e. goes back to 1.) with an exponentially increasing duration each time it needs to retry the same request.
