### ISSUE TITLE
allow access to custom fields of an issue

### ISSUE THREAD

**Issue by stardust85** [pycontribs/jira#954]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Access values of custom fields. At least for read. Probably by providing a dict called custom_fields. something like my_issue.get_custom_fields()

**Describe alternatives you've considered**
Using requests directly.

**Comment by JasonKempSEL** [comment]
Custom fields are available in the object already: `issue.fields.customfield_123456`

**Comment by stardust85** [comment]
Aha, good to know, thanks
