### ISSUE TITLE
Access Jira Software Cloud API

### ISSUE THREAD

**Issue by guigros** [pycontribs/jira#974]
**Is your feature request related to a problem? Please describe.**
Hi all,
I'm opening this issue but I'm not sure it is an actual problem. I've looked at the code and the documentation and I did not find my answers.
Would it be possible to access [those endpoints](https://developer.atlassian.com/cloud/jira/software/rest/intro/) with this Python library ?
I'd like to call [this endpoint](https://developer.atlassian.com/cloud/jira/software/rest/api-group-builds/#api-builds-0-1-bulk-post) to update Build information on Jira.

**Comment by adehad** [comment]
The short answer is no.

The longer answer is, kinda:
1. The JIRA client provides some helpful wrapping and functions to interact with the API, and there is _some_ support for the Cloud version of the API, however, it is not complete.
2. The Build endpoint, from what I can see is not supported, however, you are able to subclass the main `JIRA` class to implement your own functions for interacting with the API.


I'm going to close this this issue, but if you have any further questions please use the 'Discussions' tab and we can try and answer anything over there
