### ISSUE TITLE
Hardcoded API version kills backwards compatibility

### ISSUE THREAD

**Issue by milbrain** [pycontribs/jira#981]
**Describe the bug**
When doing requests against the Jira REST API, many methods explicitly use v3 of the REST API (`/rest/api/3/...`). However version 3 is still in beta, unsupported for Jira Server and thus unnecessarily reduces backwards-compatibility. This bug also persists in `master`. I suggest changing `3` to latest, as was used in python jira version 2.0

**To Reproduce**
1. Set up Jira Server (e.g. 8.12.1)
```
import jira

j = jira.JIRA(...)
perm = j.permissionschemes() # exception: 404 URL not found https://my.jira.url/rest/api/3/permissionscheme

# now lets try to replace it by 2
url = 'https://my.jira.url/rest/api/2/permissionscheme'
r = j._session.get(url)
data = jira.utils.json_loads(r)["permissionSchemes"]
print(data) # prints data perfectly fine.
```

**Version Information**
Python Interpreter: 3.9.0rc1
jira-python: 3.0a2
OS: Windows 10
Jira: Jira Server 8.12.1

**Suggested fix**
Replace all 'api/3/' with 'api/latest/' via regex. Should be easy peasy.

**Comment by milbrain** [comment]
I realized that the whole 3.0a2 release is not compatible with Jira Server (not only the API Version number, but also the project parameters). That's a shame. Would have been nice to read that in some kind of description somewhere :D 
^That's for you fellow googlers who might find this post. **jira-python 3.0 is not compatible with Jira Server**

**Comment by adehad** [comment]
Following #1017, the pipeline passes for Jira Server, I've also replaced these hard-coded API urls to use the ones that are provided on instantiating the class.
