### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by nickjmv** [pycontribs/jira#985]
Any roadmap when the latest version will be released on PyPI? https://pypi.org/project/jira/

**Comment by naqushab** [comment]
+1 - any timeline for v3? thank you!

**Comment by RedneckEdamame** [comment]
Are there blockers to releasing 3.0 to PyPi? I'm happy to chip in to help package it.

**Comment by jpyams** [comment]
See also #967 and #969

**Comment by yunhao-qing** [comment]
Same, we need Pypi for production.

**Comment by BossColo** [comment]
Why has this been neglected for so long?

**Comment by studioj** [comment]
@BossColo please see https://github.com/pycontribs/jira/issues/896

Last week CI is back up and running but only for JIRA server

**Comment by studioj** [comment]
closing as duplicate https://github.com/pycontribs/jira/issues/967
