### ISSUE TITLE
How to set User-Agent header in requests

### ISSUE THREAD

**Issue by hmarsolla** [pycontribs/jira#988]
The Jira instance my company runs has a Cloudflare firewall that needs a specific User-Agent header to be used in each request. 
I saw some old answers in StackOverflow that people would pass the headers via the options argument, like this:

```javascript
jira_options = {
    'headers' : {
                        'X-Atlassian-Token': 'no-check',
                        'Cache-Control': 'no-cache',
                        'Content-Type': 'application/json',
                        'User-Agent': "my-user-agent"
                }
}

client= JIRA(jira_options, ...)
```

But as I read the code, it seems like **options** argument would not use the **headers** for anything.

How can I pass this User-Agent header so I can effectively make my requests? Without it, I receive a 403 error...

**Comment by skaiaa** [comment]
Adding headers would be extremely useful. I have a case where I need to login to Jira using token bearer (header like this "authentication" : "Bearer <TOKEN>"). There is no auth option for it and because I cannot add this header manually, I'm stuck.

**Comment by danielflira** [comment]
Apparently on JIRA constructor it makes a copy of JIRA.DEFAULT_OPTIONS dictionary then it uses options parameter to update internal options, try something like:

```python
jira = JIRA(options={"headers": {"my-header": "my value"}})
```

**Comment by hmarsolla** [comment]
@danielflira this was the right answer! Thank you :)
