### ISSUE TITLE
Does this library support adding watchers to an issue?

### ISSUE THREAD

**Issue by naiquevin** [pycontribs/jira#99]
As per the API documentation - https://docs.atlassian.com/jira/REST/latest/#d2e393, the `/rest/api/2/issue/{issueIdOrKey}/watchers` endpoint accepts `application/json` but example input is "fred" (which seems wrong to me, but that's a different issue!)

From the code, `jira.resources.Watchers` doesn't have an "add" method. However, it inherits `update` method from it's superclass `Resource` so I tried the following and it fails.

```
issue.fields.watches.update(username='vineet')
```

**Comment by asqui** [comment]
Did you mean `issue.fields.watchers`, rather than `watches` (or is that just a typo in your comment)?

**Comment by naiquevin** [comment]
@asqui: It's not a typo. I just confirmed it with the latest version of the lib (0.50)
<img width="1036" alt="screen shot 2015-07-15 at 10 12 03 pm" src="https://cloud.githubusercontent.com/assets/584860/8704162/fc0d0a46-2b3e-11e5-9657-11298ef146cc.png">

@ssbarnea: Why has this issue been closed?

**Comment by naiquevin** [comment]
@ssbarnea: Care to tell the reason behind closing this issue? Is this not the right place to ask the question or is there anything wrong with the question?
