### ISSUE TITLE
add support for JIRA / Confluence Server Personal Access Tokens

### ISSUE THREAD

**Issue by valentijnscholten** [pycontribs/jira#993]
**Is your feature request related to a problem? Please describe.**
In JIRA Server 8.14 and Confluence Server 7.9 atlassian has (finally) added tokens as a way to authenticate to the REST API. Much better then people using their company wide ldap password for this (and storing it in places).

**Describe the solution you'd like**
I think we should support this new authentication method as JIRA Datacenter will also use it and stay beyond 2024. And basic authentication with passwords will be deprecated by atlassian.

**Describe alternatives you've considered**
Add support for https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Additional context**
Please note these personal access tokens are slightly different from the JIRA Cloud api tokens (thank you atlassian).

Cloud: `curl -H "Authorization: Basic <base64(<username>:<yourToken>>)" https://{jiraBaseUrl}/rest/api/`

Server: `curl -H "Authorization: Bearer <yourToken>" https://{jiraBaseUrl}/rest/api/`

**Comment by oaustegard** [comment]
There's a PR for this here: https://github.com/pycontribs/jira/pull/991 Worth a review by someone with write access?

**Comment by oaustegard** [comment]
> There's a PR for this here: #991 Worth a review by someone with write access?

Yeah I see how this conflicts with https://github.com/pycontribs/jira/issues/896 - until the build is fixed this won't be reviewed

Meanwhile a workaround for anyone looking to use Personal Access Tokens is here: https://github.com/pycontribs/jira/issues/989#issuecomment-772683446

**Comment by valentijnscholten** [comment]
> There's a PR for this here: #991 Worth a review by someone with write access?

Thanks, didn't see that one.

**Comment by studioj** [comment]
@valentijnscholten we assume this is closed in below pre-release could you confirm?

https://github.com/pycontribs/jira/releases/tag/3.1.0rc1

**Comment by valentijnscholten** [comment]
yes (untested)

**Comment by adehad** [comment]
For completeness:

```python
# Jira Cloud uses the 'Basic' Auth header
jira_cloud_token_auth = JIRA(basic_auth=('email', 'API token'))

# Jira Server/Data Center/Self Hosted uses the 'Bearer' Auth header
jira_server_token_auth = JIRA(token_auth='API token')

```
