### ISSUE TITLE
Share Issue feature

### ISSUE THREAD

**Issue by feraamorim** [pycontribs/jira#999]
Hi,

Is there a way to share an issue? I cant find it in the documentation, I think this is not implemented yet...

![Screenshot_1](https://user-images.githubusercontent.com/7452021/108512676-55844e00-72a0-11eb-8a26-2024d91c0067.png)

**Comment by studioj** [comment]
@feraamorim i don't think this is possible via the jira api

https://community.atlassian.com/t5/Jira-Software-questions/Api-for-share-Issue/qaq-p/1395843

you can always add users to the watchers as suggested in above link

https://jira.readthedocs.io/en/latest/api.html#jira.JIRA.add_watcher
